//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VECTO3GUI2020.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BusStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BusStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VECTO3GUI2020.Properties.BusStrings", typeof(BusStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airdrag Area 0.
        /// </summary>
        internal static string AirdragArea0 {
            get {
                return ResourceManager.GetString("AirdragArea0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airdrag Modified.
        /// </summary>
        internal static string AirdragModifiedEnum {
            get {
                return ResourceManager.GetString("AirdragModifiedEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to APT Eco Roll Release Lockup Clutch.
        /// </summary>
        internal static string ATEcoRollReleaseLockupClutch {
            get {
                return ResourceManager.GetString("ATEcoRollReleaseLockupClutch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compressor Drive.
        /// </summary>
        internal static string CompressorDrive {
            get {
                return ResourceManager.GetString("CompressorDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrected Actual Mass.
        /// </summary>
        internal static string CurbMassChassis {
            get {
                return ResourceManager.GetString("CurbMassChassis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eco Roll Type.
        /// </summary>
        internal static string EcoRollTypeNullable {
            get {
                return ResourceManager.GetString("EcoRollTypeNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Stop Start.
        /// </summary>
        internal static string EngineStopStartNullable {
            get {
                return ResourceManager.GetString("EngineStopStartNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrance Height.
        /// </summary>
        internal static string EntranceHeightInMm {
            get {
                return ResourceManager.GetString("EntranceHeightInMm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tech. Perm. Max. Laden Mass.
        /// </summary>
        internal static string GrossVehicleMassRating {
            get {
                return ResourceManager.GetString("GrossVehicleMassRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooling.
        /// </summary>
        internal static string HeatPumpTypeCoolingDriverCompartment {
            get {
                return ResourceManager.GetString("HeatPumpTypeCoolingDriverCompartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cooling.
        /// </summary>
        internal static string HeatPumpTypeCoolingPassengerCompartment {
            get {
                return ResourceManager.GetString("HeatPumpTypeCoolingPassengerCompartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating.
        /// </summary>
        internal static string HeatPumpTypeHeatingDriverCompartment {
            get {
                return ResourceManager.GetString("HeatPumpTypeHeatingDriverCompartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heating.
        /// </summary>
        internal static string HeatPumpTypeHeatingPassengerCompartment {
            get {
                return ResourceManager.GetString("HeatPumpTypeHeatingPassengerCompartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height Integrated Body.
        /// </summary>
        internal static string HeightInMm {
            get {
                return ResourceManager.GetString("HeightInMm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legislative Category.
        /// </summary>
        internal static string LegislativeClass {
            get {
                return ResourceManager.GetString("LegislativeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Length.
        /// </summary>
        internal static string LengthInMm {
            get {
                return ResourceManager.GetString("LengthInMm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seats Lower Deck.
        /// </summary>
        internal static string NumberPassengerSeatsLowerDeck {
            get {
                return ResourceManager.GetString("NumberPassengerSeatsLowerDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seats Upper Deck.
        /// </summary>
        internal static string NumberPassengerSeatsUpperDeck {
            get {
                return ResourceManager.GetString("NumberPassengerSeatsUpperDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standing Lower Deck.
        /// </summary>
        internal static string NumberPassengersStandingLowerDeck {
            get {
                return ResourceManager.GetString("NumberPassengersStandingLowerDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standing Upper Deck.
        /// </summary>
        internal static string NumberPassengersStandingUpperDeck {
            get {
                return ResourceManager.GetString("NumberPassengersStandingUpperDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictive Cruise Control.
        /// </summary>
        internal static string PredictiveCruiseControlNullable {
            get {
                return ResourceManager.GetString("PredictiveCruiseControlNullable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class Bus.
        /// </summary>
        internal static string RegisteredClass {
            get {
                return ResourceManager.GetString("RegisteredClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ng Tank System.
        /// </summary>
        internal static string TankSystem {
            get {
                return ResourceManager.GetString("TankSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred Airdrag Area.
        /// </summary>
        internal static string TransferredAirDragArea {
            get {
                return ResourceManager.GetString("TransferredAirDragArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodywork Code.
        /// </summary>
        internal static string VehicleCode {
            get {
                return ResourceManager.GetString("VehicleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Width.
        /// </summary>
        internal static string WidthInMm {
            get {
                return ResourceManager.GetString("WidthInMm", resourceCulture);
            }
        }
    }
}
