//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VECTO3GUI2020.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GUILabels {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GUILabels() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VECTO3GUI2020.Properties.GUILabels", typeof(GUILabels).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airdrag Data.
        /// </summary>
        public static string _consolidateAirdragData {
            get {
                return ResourceManager.GetString("_consolidateAirdragData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bus Auxiliaries Data.
        /// </summary>
        public static string _consolidateBusAuxiliariesData {
            get {
                return ResourceManager.GetString("_consolidateBusAuxiliariesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADAS.
        /// </summary>
        public static string _consolidatedADAS {
            get {
                return ResourceManager.GetString("_consolidatedADAS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        public static string _consolidatedComponents {
            get {
                return ResourceManager.GetString("_consolidatedComponents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HVAC Data.
        /// </summary>
        public static string _consolidatedHVACBusAuxiliariesData {
            get {
                return ResourceManager.GetString("_consolidatedHVACBusAuxiliariesData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Electric Consumer Data.
        /// </summary>
        public static string _consolidateElectricConsumerData {
            get {
                return ResourceManager.GetString("_consolidateElectricConsumerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VECTO.
        /// </summary>
        public static string DefaultTitle {
            get {
                return ResourceManager.GetString("DefaultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Airdrag Entries.
        /// </summary>
        public static string IsAirdragEntriesValid {
            get {
                return ResourceManager.GetString("IsAirdragEntriesValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Tank System.
        /// </summary>
        public static string IsTankSystemValid {
            get {
                return ResourceManager.GetString("IsTankSystemValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Complete Job.
        /// </summary>
        public static string NewCompleteJob {
            get {
                return ResourceManager.GetString("NewCompleteJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Interim/Completed Job.
        /// </summary>
        public static string NewInterimOrCompletedJob {
            get {
                return ResourceManager.GetString("NewInterimOrCompletedJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Primary Job with Interim Input.
        /// </summary>
        public static string NewPrimaryAndInterimJob {
            get {
                return ResourceManager.GetString("NewPrimaryAndInterimJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Manufacturing Steps.
        /// </summary>
        public static string no_manufacturing_stages {
            get {
                return ResourceManager.GetString("no manufacturing stages", resourceCulture);
            }
        }
    }
}
