//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VECTO3GUI2020.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VECTO3GUI2020.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adjustable Auxiliary Heater.
        /// </summary>
        internal static string AdjustableAuxiliaryHeater {
            get {
                return ResourceManager.GetString("AdjustableAuxiliaryHeater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airdrag Area.
        /// </summary>
        internal static string AirDragArea {
            get {
                return ResourceManager.GetString("AirDragArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airdrag Area 0.
        /// </summary>
        internal static string AirdragArea0 {
            get {
                return ResourceManager.GetString("AirdragArea0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air Electric Heater.
        /// </summary>
        internal static string AirElectricHeater {
            get {
                return ResourceManager.GetString("AirElectricHeater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angledrive Type.
        /// </summary>
        internal static string AngledriveType {
            get {
                return ResourceManager.GetString("AngledriveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary Heater Power.
        /// </summary>
        internal static string AuxHeaterPower {
            get {
                return ResourceManager.GetString("AuxHeaterPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axle Configuration.
        /// </summary>
        internal static string AxleConfiguration {
            get {
                return ResourceManager.GetString("AxleConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axlegear Ratio.
        /// </summary>
        internal static string AxleGearRatio {
            get {
                return ResourceManager.GetString("AxleGearRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brake Lights LED.
        /// </summary>
        internal static string BrakelightsLED {
            get {
                return ResourceManager.GetString("BrakelightsLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification Number.
        /// </summary>
        internal static string Certification_Number {
            get {
                return ResourceManager.GetString("Certification Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification Method.
        /// </summary>
        internal static string CertificationMethod {
            get {
                return ResourceManager.GetString("CertificationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification Number.
        /// </summary>
        internal static string CertificationNumber {
            get {
                return ResourceManager.GetString("CertificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curb Mass Chassis.
        /// </summary>
        internal static string CurbMassChassis {
            get {
                return ResourceManager.GetString("CurbMassChassis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dayrunning Lights LED.
        /// </summary>
        internal static string DayrunninglightsLED {
            get {
                return ResourceManager.GetString("DayrunninglightsLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension.
        /// </summary>
        internal static string Dimension {
            get {
                return ResourceManager.GetString("Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displacement.
        /// </summary>
        internal static string Displacement {
            get {
                return ResourceManager.GetString("Displacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doordrive Technology.
        /// </summary>
        internal static string DoorDriveTechnology {
            get {
                return ResourceManager.GetString("DoorDriveTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Double Glazing.
        /// </summary>
        internal static string DoubleGlazing {
            get {
                return ResourceManager.GetString("DoubleGlazing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        internal static string Efficiency {
            get {
                return ResourceManager.GetString("Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Idle Speed.
        /// </summary>
        internal static string EngineIdleSpeed {
            get {
                return ResourceManager.GetString("EngineIdleSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entrance Height.
        /// </summary>
        internal static string EntranceHeight {
            get {
                return ResourceManager.GetString("EntranceHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Vehicle Mass.
        /// </summary>
        internal static string GrossVehicleMass {
            get {
                return ResourceManager.GetString("GrossVehicleMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Vehicle Mass Rating.
        /// </summary>
        internal static string GrossVehicleMassRating {
            get {
                return ResourceManager.GetString("GrossVehicleMassRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head Lights LED.
        /// </summary>
        internal static string HeadlightsLED {
            get {
                return ResourceManager.GetString("HeadlightsLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Pump Mode.
        /// </summary>
        internal static string HeatPumpMode {
            get {
                return ResourceManager.GetString("HeatPumpMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Pump Mode Driver.
        /// </summary>
        internal static string HeatPumpModeDriverCompartment {
            get {
                return ResourceManager.GetString("HeatPumpModeDriverCompartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Pump Mode Passenger.
        /// </summary>
        internal static string HeatPumpModePassengerCompartment {
            get {
                return ResourceManager.GetString("HeatPumpModePassengerCompartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Pump Type.
        /// </summary>
        internal static string HeatPumpType {
            get {
                return ResourceManager.GetString("HeatPumpType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Pump Type Driver.
        /// </summary>
        internal static string HeatPumpTypeDriverCompartment {
            get {
                return ResourceManager.GetString("HeatPumpTypeDriverCompartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heat Pump Type Passenger.
        /// </summary>
        internal static string HeatPumpTypePassengerCompartment {
            get {
                return ResourceManager.GetString("HeatPumpTypePassengerCompartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idling Speed.
        /// </summary>
        internal static string IdlingSpeed {
            get {
                return ResourceManager.GetString("IdlingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interior Lights LED.
        /// </summary>
        internal static string InteriorLightsLED {
            get {
                return ResourceManager.GetString("InteriorLightsLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legislative Class.
        /// </summary>
        internal static string LegislativeClass {
            get {
                return ResourceManager.GetString("LegislativeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        internal static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low Entry.
        /// </summary>
        internal static string LowEntry {
            get {
                return ResourceManager.GetString("LowEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        internal static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Address.
        /// </summary>
        internal static string ManufacturerAddress {
            get {
                return ResourceManager.GetString("ManufacturerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Adress.
        /// </summary>
        internal static string ManufacturerAdress {
            get {
                return ResourceManager.GetString("ManufacturerAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Torque Declared.
        /// </summary>
        internal static string MaxTorqueDeclared {
            get {
                return ResourceManager.GetString("MaxTorqueDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        internal static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passengers Lower Deck.
        /// </summary>
        internal static string NumberOfPassengersLowerDeck {
            get {
                return ResourceManager.GetString("NumberOfPassengersLowerDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passengers Upper Deck.
        /// </summary>
        internal static string NumberOfPassengersUpperDeck {
            get {
                return ResourceManager.GetString("NumberOfPassengersUpperDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Heating Technology.
        /// </summary>
        internal static string OtherHeatingTechnology {
            get {
                return ResourceManager.GetString("OtherHeatingTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position Lights LED.
        /// </summary>
        internal static string PositionlightsLED {
            get {
                return ResourceManager.GetString("PositionlightsLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictive Cruise Control.
        /// </summary>
        internal static string PredictiveCruiseControl {
            get {
                return ResourceManager.GetString("PredictiveCruiseControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission Type.
        /// </summary>
        internal static string PTOTransmissionType {
            get {
                return ResourceManager.GetString("PTOTransmissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated Power.
        /// </summary>
        internal static string RatedPowerDeclared {
            get {
                return ResourceManager.GetString("RatedPowerDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated Speed Declared.
        /// </summary>
        internal static string RatedSpeedDeclared {
            get {
                return ResourceManager.GetString("RatedSpeedDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        internal static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Class.
        /// </summary>
        internal static string RegisteredClass {
            get {
                return ResourceManager.GetString("RegisteredClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retarder Ratio.
        /// </summary>
        internal static string RetarderRatio {
            get {
                return ResourceManager.GetString("RetarderRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retarder Type.
        /// </summary>
        internal static string RetarderType {
            get {
                return ResourceManager.GetString("RetarderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll Resistance Coefficient.
        /// </summary>
        internal static string RRC {
            get {
                return ResourceManager.GetString("RRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to overwrite 
        /// .
        /// </summary>
        internal static string SaveExecute_Do_you_want_to_overwrite {
            get {
                return ResourceManager.GetString("SaveExecute_Do_you_want_to_overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seperate Air Distribution Ducts.
        /// </summary>
        internal static string SeparateAirDistributionDucts {
            get {
                return ResourceManager.GetString("SeparateAirDistributionDucts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System Configuration.
        /// </summary>
        internal static string SystemConfiguration {
            get {
                return ResourceManager.GetString("SystemConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tank System.
        /// </summary>
        internal static string TankSystem {
            get {
                return ResourceManager.GetString("TankSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred Airdrag Area.
        /// </summary>
        internal static string TransferredAirDragArea {
            get {
                return ResourceManager.GetString("TransferredAirDragArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission Type.
        /// </summary>
        internal static string TransmissionType {
            get {
                return ResourceManager.GetString("TransmissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twin Tyres.
        /// </summary>
        internal static string TwinTyres {
            get {
                return ResourceManager.GetString("TwinTyres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Category.
        /// </summary>
        internal static string VehicleCategory {
            get {
                return ResourceManager.GetString("VehicleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Code.
        /// </summary>
        internal static string VehicleCode {
            get {
                return ResourceManager.GetString("VehicleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Declaration Type.
        /// </summary>
        internal static string VehicleDeclarationType {
            get {
                return ResourceManager.GetString("VehicleDeclarationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Type Approval Number.
        /// </summary>
        internal static string VehicleTypeApprovalNumber {
            get {
                return ResourceManager.GetString("VehicleTypeApprovalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Identification Number.
        /// </summary>
        internal static string VehicleViewModel_v1_0_VIN {
            get {
                return ResourceManager.GetString("VehicleViewModel_v1_0_VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Identification Number.
        /// </summary>
        internal static string VIN {
            get {
                return ResourceManager.GetString("VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Water Electric Heater.
        /// </summary>
        internal static string WaterElectricHeater {
            get {
                return ResourceManager.GetString("WaterElectricHeater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Heat Recovery.
        /// </summary>
        internal static string WHRType {
            get {
                return ResourceManager.GetString("WHRType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
