//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VECTO3GUI2020.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VECTO3GUI2020.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Adjustable Auxiliary Heater ähnelt.
        /// </summary>
        public static string AdjustableAuxiliaryHeater {
            get {
                return ResourceManager.GetString("AdjustableAuxiliaryHeater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Declared CdxA ähnelt.
        /// </summary>
        public static string AirDragArea {
            get {
                return ResourceManager.GetString("AirDragArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Airdrag Area 0 ähnelt.
        /// </summary>
        public static string AirdragArea0 {
            get {
                return ResourceManager.GetString("AirdragArea0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Air Electric Heater ähnelt.
        /// </summary>
        public static string AirElectricHeater {
            get {
                return ResourceManager.GetString("AirElectricHeater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Angledrive Type ähnelt.
        /// </summary>
        public static string AngledriveType {
            get {
                return ResourceManager.GetString("AngledriveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Auxiliary Heater Power ähnelt.
        /// </summary>
        public static string AuxHeaterPower {
            get {
                return ResourceManager.GetString("AuxHeaterPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Axle Configuration ähnelt.
        /// </summary>
        public static string AxleConfiguration {
            get {
                return ResourceManager.GetString("AxleConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Axlegear Ratio ähnelt.
        /// </summary>
        public static string AxleGearRatio {
            get {
                return ResourceManager.GetString("AxleGearRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Brake Lights LED ähnelt.
        /// </summary>
        public static string BrakelightsLED {
            get {
                return ResourceManager.GetString("BrakelightsLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Certification Number ähnelt.
        /// </summary>
        public static string Certification_Number {
            get {
                return ResourceManager.GetString("Certification Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Certification Method ähnelt.
        /// </summary>
        public static string CertificationMethod {
            get {
                return ResourceManager.GetString("CertificationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Certification Number ähnelt.
        /// </summary>
        public static string CertificationNumber {
            get {
                return ResourceManager.GetString("CertificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Curb Mass Chassis ähnelt.
        /// </summary>
        public static string CurbMassChassis {
            get {
                return ResourceManager.GetString("CurbMassChassis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dayrunning Lights LED ähnelt.
        /// </summary>
        public static string DayrunninglightsLED {
            get {
                return ResourceManager.GetString("DayrunninglightsLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dimension ähnelt.
        /// </summary>
        public static string Dimension {
            get {
                return ResourceManager.GetString("Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Displacement ähnelt.
        /// </summary>
        public static string Displacement {
            get {
                return ResourceManager.GetString("Displacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Doordrive Technology ähnelt.
        /// </summary>
        public static string DoorDriveTechnology {
            get {
                return ResourceManager.GetString("DoorDriveTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Double Glazing ähnelt.
        /// </summary>
        public static string DoubleGlazing {
            get {
                return ResourceManager.GetString("DoubleGlazing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Efficiency ähnelt.
        /// </summary>
        public static string Efficiency {
            get {
                return ResourceManager.GetString("Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Engine Idle Speed ähnelt.
        /// </summary>
        public static string EngineIdleSpeed {
            get {
                return ResourceManager.GetString("EngineIdleSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Entrance Height ähnelt.
        /// </summary>
        public static string EntranceHeight {
            get {
                return ResourceManager.GetString("EntranceHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gross Vehicle Mass ähnelt.
        /// </summary>
        public static string GrossVehicleMass {
            get {
                return ResourceManager.GetString("GrossVehicleMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gross Vehicle Mass Rating ähnelt.
        /// </summary>
        public static string GrossVehicleMassRating {
            get {
                return ResourceManager.GetString("GrossVehicleMassRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Head Lights LED ähnelt.
        /// </summary>
        public static string HeadlightsLED {
            get {
                return ResourceManager.GetString("HeadlightsLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heat Pump Mode ähnelt.
        /// </summary>
        public static string HeatPumpMode {
            get {
                return ResourceManager.GetString("HeatPumpMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heat Pump Mode Driver ähnelt.
        /// </summary>
        public static string HeatPumpModeDriverCompartment {
            get {
                return ResourceManager.GetString("HeatPumpModeDriverCompartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heat Pump Mode Passenger ähnelt.
        /// </summary>
        public static string HeatPumpModePassengerCompartment {
            get {
                return ResourceManager.GetString("HeatPumpModePassengerCompartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heat Pump Type ähnelt.
        /// </summary>
        public static string HeatPumpType {
            get {
                return ResourceManager.GetString("HeatPumpType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heat Pump Type Driver ähnelt.
        /// </summary>
        public static string HeatPumpTypeDriverCompartment {
            get {
                return ResourceManager.GetString("HeatPumpTypeDriverCompartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heat Pump Type Passenger ähnelt.
        /// </summary>
        public static string HeatPumpTypePassengerCompartment {
            get {
                return ResourceManager.GetString("HeatPumpTypePassengerCompartment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height ähnelt.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Idling Speed ähnelt.
        /// </summary>
        public static string IdlingSpeed {
            get {
                return ResourceManager.GetString("IdlingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Interior Lights LED ähnelt.
        /// </summary>
        public static string InteriorLightsLED {
            get {
                return ResourceManager.GetString("InteriorLightsLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Legislative Class ähnelt.
        /// </summary>
        public static string LegislativeClass {
            get {
                return ResourceManager.GetString("LegislativeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Length ähnelt.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Low Entry ähnelt.
        /// </summary>
        public static string LowEntry {
            get {
                return ResourceManager.GetString("LowEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manufacturer ähnelt.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manufacturer Address ähnelt.
        /// </summary>
        public static string ManufacturerAddress {
            get {
                return ResourceManager.GetString("ManufacturerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Manufacturer Adress ähnelt.
        /// </summary>
        public static string ManufacturerAdress {
            get {
                return ResourceManager.GetString("ManufacturerAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Max. Torque Declared ähnelt.
        /// </summary>
        public static string MaxTorqueDeclared {
            get {
                return ResourceManager.GetString("MaxTorqueDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Model ähnelt.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passengers Lower Deck ähnelt.
        /// </summary>
        public static string NumberOfPassengersLowerDeck {
            get {
                return ResourceManager.GetString("NumberOfPassengersLowerDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Passengers Upper Deck ähnelt.
        /// </summary>
        public static string NumberOfPassengersUpperDeck {
            get {
                return ResourceManager.GetString("NumberOfPassengersUpperDeck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Other Heating Technology ähnelt.
        /// </summary>
        public static string OtherHeatingTechnology {
            get {
                return ResourceManager.GetString("OtherHeatingTechnology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Position Lights LED ähnelt.
        /// </summary>
        public static string PositionlightsLED {
            get {
                return ResourceManager.GetString("PositionlightsLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Predictive Cruise Control ähnelt.
        /// </summary>
        public static string PredictiveCruiseControl {
            get {
                return ResourceManager.GetString("PredictiveCruiseControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transmission Type ähnelt.
        /// </summary>
        public static string PTOTransmissionType {
            get {
                return ResourceManager.GetString("PTOTransmissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rated Power ähnelt.
        /// </summary>
        public static string RatedPowerDeclared {
            get {
                return ResourceManager.GetString("RatedPowerDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Rated Speed Declared ähnelt.
        /// </summary>
        public static string RatedSpeedDeclared {
            get {
                return ResourceManager.GetString("RatedSpeedDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ratio ähnelt.
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Registered Class ähnelt.
        /// </summary>
        public static string RegisteredClass {
            get {
                return ResourceManager.GetString("RegisteredClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Retarder Ratio ähnelt.
        /// </summary>
        public static string RetarderRatio {
            get {
                return ResourceManager.GetString("RetarderRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Retarder Type ähnelt.
        /// </summary>
        public static string RetarderType {
            get {
                return ResourceManager.GetString("RetarderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roll Resistance Coefficient ähnelt.
        /// </summary>
        public static string RRC {
            get {
                return ResourceManager.GetString("RRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to overwrite 
        ///  ähnelt.
        /// </summary>
        public static string SaveExecute_Do_you_want_to_overwrite {
            get {
                return ResourceManager.GetString("SaveExecute_Do_you_want_to_overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Seperate Air Distribution Ducts ähnelt.
        /// </summary>
        public static string SeparateAirDistributionDucts {
            get {
                return ResourceManager.GetString("SeparateAirDistributionDucts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die System Configuration ähnelt.
        /// </summary>
        public static string SystemConfiguration {
            get {
                return ResourceManager.GetString("SystemConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tank System ähnelt.
        /// </summary>
        public static string TankSystem {
            get {
                return ResourceManager.GetString("TankSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transferred Airdrag Area ähnelt.
        /// </summary>
        public static string TransferredAirDragArea {
            get {
                return ResourceManager.GetString("TransferredAirDragArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Transmission Type ähnelt.
        /// </summary>
        public static string TransmissionType {
            get {
                return ResourceManager.GetString("TransmissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Twin Tyres ähnelt.
        /// </summary>
        public static string TwinTyres {
            get {
                return ResourceManager.GetString("TwinTyres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle Category ähnelt.
        /// </summary>
        public static string VehicleCategory {
            get {
                return ResourceManager.GetString("VehicleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle Code ähnelt.
        /// </summary>
        public static string VehicleCode {
            get {
                return ResourceManager.GetString("VehicleCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle Declaration Type ähnelt.
        /// </summary>
        public static string VehicleDeclarationType {
            get {
                return ResourceManager.GetString("VehicleDeclarationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle Type Approval Number ähnelt.
        /// </summary>
        public static string VehicleTypeApprovalNumber {
            get {
                return ResourceManager.GetString("VehicleTypeApprovalNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle Identification Number ähnelt.
        /// </summary>
        public static string VehicleViewModel_v1_0_VIN {
            get {
                return ResourceManager.GetString("VehicleViewModel_v1_0_VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle Identification Number ähnelt.
        /// </summary>
        public static string VIN {
            get {
                return ResourceManager.GetString("VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Water Electric Heater ähnelt.
        /// </summary>
        public static string WaterElectricHeater {
            get {
                return ResourceManager.GetString("WaterElectricHeater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Waste Heat Recovery ähnelt.
        /// </summary>
        public static string WHRType {
            get {
                return ResourceManager.GetString("WHRType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Width ähnelt.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
