//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VECTO3GUI2020.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VECTO3GUI2020.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airdrag Area.
        /// </summary>
        public static string AirDragArea {
            get {
                return ResourceManager.GetString("AirDragArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angledrive Type.
        /// </summary>
        public static string AngledriveType {
            get {
                return ResourceManager.GetString("AngledriveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axle Configuration.
        /// </summary>
        public static string AxleConfiguration {
            get {
                return ResourceManager.GetString("AxleConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axlegear Ratio.
        /// </summary>
        public static string AxleGearRatio {
            get {
                return ResourceManager.GetString("AxleGearRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification Number.
        /// </summary>
        public static string Certification_Number {
            get {
                return ResourceManager.GetString("Certification Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification Method.
        /// </summary>
        public static string CertificationMethod {
            get {
                return ResourceManager.GetString("CertificationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certification Number.
        /// </summary>
        public static string CertificationNumber {
            get {
                return ResourceManager.GetString("CertificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Curb Mass Chassis.
        /// </summary>
        public static string CurbMassChassis {
            get {
                return ResourceManager.GetString("CurbMassChassis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension.
        /// </summary>
        public static string Dimension {
            get {
                return ResourceManager.GetString("Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displacement.
        /// </summary>
        public static string Displacement {
            get {
                return ResourceManager.GetString("Displacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        public static string Efficiency {
            get {
                return ResourceManager.GetString("Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Idle Speed.
        /// </summary>
        public static string EngineIdleSpeed {
            get {
                return ResourceManager.GetString("EngineIdleSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Vehicle Mass.
        /// </summary>
        public static string GrossVehicleMass {
            get {
                return ResourceManager.GetString("GrossVehicleMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Vehicle Mass Rating.
        /// </summary>
        public static string GrossVehicleMassRating {
            get {
                return ResourceManager.GetString("GrossVehicleMassRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Idling Speed.
        /// </summary>
        public static string IdlingSpeed {
            get {
                return ResourceManager.GetString("IdlingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legislative Class.
        /// </summary>
        public static string LegislativeClass {
            get {
                return ResourceManager.GetString("LegislativeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Manufacturer {
            get {
                return ResourceManager.GetString("Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Address.
        /// </summary>
        public static string ManufacturerAddress {
            get {
                return ResourceManager.GetString("ManufacturerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer Adress.
        /// </summary>
        public static string ManufacturerAdress {
            get {
                return ResourceManager.GetString("ManufacturerAdress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. Torque Declared.
        /// </summary>
        public static string MaxTorqueDeclared {
            get {
                return ResourceManager.GetString("MaxTorqueDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predictive Cruise Control.
        /// </summary>
        public static string PredictiveCruiseControl {
            get {
                return ResourceManager.GetString("PredictiveCruiseControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission Type.
        /// </summary>
        public static string PTOTransmissionType {
            get {
                return ResourceManager.GetString("PTOTransmissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated Power.
        /// </summary>
        public static string RatedPowerDeclared {
            get {
                return ResourceManager.GetString("RatedPowerDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rated Speed Declared.
        /// </summary>
        public static string RatedSpeedDeclared {
            get {
                return ResourceManager.GetString("RatedSpeedDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        public static string Ratio {
            get {
                return ResourceManager.GetString("Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retarder Ratio.
        /// </summary>
        public static string RetarderRatio {
            get {
                return ResourceManager.GetString("RetarderRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retarder Type.
        /// </summary>
        public static string RetarderType {
            get {
                return ResourceManager.GetString("RetarderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll Resistance Coefficient.
        /// </summary>
        public static string RRC {
            get {
                return ResourceManager.GetString("RRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to overwrite 
        /// .
        /// </summary>
        public static string SaveExecute_Do_you_want_to_overwrite {
            get {
                return ResourceManager.GetString("SaveExecute_Do_you_want_to_overwrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transmission Type.
        /// </summary>
        public static string TransmissionType {
            get {
                return ResourceManager.GetString("TransmissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twin Tyres.
        /// </summary>
        public static string TwinTyres {
            get {
                return ResourceManager.GetString("TwinTyres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Category.
        /// </summary>
        public static string VehicleCategory {
            get {
                return ResourceManager.GetString("VehicleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Identification Number.
        /// </summary>
        public static string VehicleViewModel_v1_0_VIN {
            get {
                return ResourceManager.GetString("VehicleViewModel_v1_0_VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle Identification Number.
        /// </summary>
        public static string VIN {
            get {
                return ResourceManager.GetString("VIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waste Heat Recovery.
        /// </summary>
        public static string WHRType {
            get {
                return ResourceManager.GetString("WHRType", resourceCulture);
            }
        }
    }
}
