<Project DefaultTargets = "Build" xmlns="http://schemas.microsoft.com/developer/msbuild/2003" >
	<Target Name="CustomClean">
		<Message Text="Removing old files $(ProjectDir)bin\" Importance="high" />
		<Message Text="Removing old files $(ProjectDir)obj\" Importance="high" />
		<RemoveDir Directories="$(ProjectDir)bin\"/>
		<RemoveDir Directories="$(ProjectDir)obj\"/>
	</Target>

	<Target Name="Packaging" AfterTargets="DispatchToInnerBuilds" Condition="('$(Configuration)'=='Deploy') Or ('$(Configuration)' == 'MockupDeploy')">
		<Message Text="Packaging in $(Configuration) Configuration $(VersionPrefix)" Importance="high" />
		<PropertyGroup>
			<CurrentDate>$([System.DateTime]::Now.ToString(yyy_MM_dd))</CurrentDate>
			<DeployPath>$(SolutionDir)Deploy\$(CurrentDate)-VECTO-$(Version)\</DeployPath>
			<NuGetPath>$(SolutionDir)Nuget\$(CurrentDate)-VECTO-NuGet-$(Version)\</NuGetPath>
			<ReleasePath>$(SolutionDir)Release\</ReleasePath>
		</PropertyGroup>
  		<RemoveDir Directories="$(SolutionDir)Deploy" Condition="Exists('$(SolutionDir)Deploy')"/>
		<RemoveDir Directories="$(SolutionDir)Nuget" Condition="Exists('$(SolutionDir)Nuget')"/>
		<RemoveDir Directories="$(NuGetPath)" Condition="Exists('$(NuGetPath)')"/>
		<MakeDir Directories="$(DeployPath)"/>
		<MakeDir Directories="$(NuGetPath)"/>
		<MakeDir Directories="$(ReleasePath)"/>

		<ItemGroup Condition="'$(Configuration)'=='Deploy'">
			<!-- All files for net48 -->
			<Net48VECTO Include="$(SolutionDir)VECTO\bin\Release\net48\*.exe*"/>
			<Net48VECTO Include="$(SolutionDir)VECTO\bin\Release\net48\*.dll*"/>
			<Net48VECTO Include="$(SolutionDir)VECTO\bin\Release\net48\nlog.config"/>
			<Net48HashingTool Include="$(SolutionDir)HashingCmd\bin\Release\net48\*.exe"/>
			<Net48HashingTool Include="$(SolutionDir)HashingCmd\bin\Release\net48\*.dll*"/>
			<Net48HashingTool Include="$(SolutionDir)HashingTool\bin\Release\net48\*.exe*"/>
			<Net48HashingTool Include="$(SolutionDir)HashingTool\bin\Release\net48\*.dll*"/>
			<Net48VectoCommandLine Include="$(SolutionDir)VectoConsole\bin\Release\net48\*.exe*"/>
			<Net48VectoCommandLine Include="$(SolutionDir)VectoConsole\bin\Release\net48\*.dll*"/>
			<Net48VectoMultistep Include="$(SolutionDir)VECTO3GUI2020\bin\Release\net48\*.exe*"/>
			<Net48VectoMultistep Include="$(SolutionDir)VECTO3GUI2020\bin\Release\net48\*.dll*"/>
			<Net48XMLConverterCmdLine Include="$(SolutionDir)XMLConverterCmdLine\bin\Release\net48\*.exe*"/>
			<Net48XMLConverterCmdLine Include="$(SolutionDir)XMLConverterCmdLine\bin\Release\net48\*.dll*"/>
		</ItemGroup>

		<!--MockupDeploy-->
		<ItemGroup Condition="'$(Configuration)'=='MockupDeploy'">
			<!-- All files for net48 -->
			<Net48VECTO Include="$(SolutionDir)VECTO\bin\MockupRelease\net48\*.exe*" />
			<Net48VECTO Include="$(SolutionDir)VECTO\bin\MockupRelease\net48\*.dll*" />
			<Net48VECTO Include="$(SolutionDir)VECTO\bin\MockupRelease\net48\nlog.config"/>
			<Net48HashingTool Include="$(SolutionDir)HashingCmd\bin\Release\net48\*.exe*" />
			<Net48HashingTool Include="$(SolutionDir)HashingCmd\bin\Release\net48\*.dll*" />
			<Net48HashingTool Include="$(SolutionDir)HashingTool\bin\Release\net48\*.exe*"/>
			<Net48HashingTool Include="$(SolutionDir)HashingTool\bin\Release\net48\*.dll*"/>
			<Net48VectoCommandLine Include="$(SolutionDir)VectoConsole\bin\MockupRelease\net48\*.exe*" />
			<Net48VectoCommandLine Include="$(SolutionDir)VectoConsole\bin\MockupRelease\net48\*.dll*" />
			<Net48VectoMultistep Include="$(SolutionDir)VECTO3GUI2020\bin\MockupRelease\net48\*.exe*" />
			<Net48VectoMultistep Include="$(SolutionDir)VECTO3GUI2020\bin\MockupRelease\net48\*.dll*" />
			<Net48XMLConverterCmdLine Include="$(SolutionDir)XMLConverterCmdLine\bin\Release\net48\*.exe*"/>
			<Net48XMLConverterCmdLine Include="$(SolutionDir)XMLConverterCmdLine\bin\Release\net48\*.dll*"/>
		</ItemGroup>

		<Copy SourceFiles="@(Net48VectoCommandLine)" DestinationFolder="$(DeployPath)net48"/>
		<Copy SourceFiles="@(Net48HashingTool)" DestinationFolder="$(DeployPath)net48"/>
		<Copy SourceFiles="@(Net48VectoMultistep)" DestinationFolder="$(DeployPath)net48"/>
		<Copy SourceFiles="@(Net48VECTO)" DestinationFolder="$(DeployPath)net48"/>
		<Copy SourceFiles="@(Net48XMLConverterCmdLine)" DestinationFolder="$(DeployPath)net48"/>

		<ItemGroup Condition="'$(Configuration)'=='Deploy'">
			<!-- All files for net6.0 -->
			<Vecto Include="$(SolutionDir)VECTO\bin\Release\net6.0-windows\VECTO.*" Exclude="*.dev.json"/>
			<Vecto Include="$(SolutionDir)VECTO\bin\Release\net6.0-windows\*.dll"/>
			<Vecto Include="$(SolutionDir)VECTO\bin\Release\net6.0-windows\nlog.config"/>
			<VectoRuntimes Include="$(SolutionDir)VECTO\bin\Release\net6.0-windows\runtimes\**\*.*"/>
			<VectoCommandLine Include="$(SolutionDir)VectoConsole\bin\Release\net6.0\vectocmd.*" Exclude="*.dev.json"/>
			<VectoCommandLine Include="$(SolutionDir)VectoConsole\bin\Release\net6.0\*.dll"/>
			<VectoCommandLineRuntimes Include="$(SolutionDir)VectoConsole\bin\Release\net6.0\runtimes\**\*.*"/>
			<XMLConverterCmdLine Include="$(SolutionDir)XMLConverterCmdLine\bin\Release\net6.0\XMLConverterCmdLine.*" Exclude="*.dev.json"/>
			<XMLConverterCmdLine Include="$(SolutionDir)XMLConverterCmdLine\bin\Release\net6.0\*.dll"/>
			<XMLConverterCmdLineRuntimes Include="$(SolutionDir)XMLConverterCmdLine\bin\Release\net6.0\runtimes\**\*.*"/>
			<HashingTool Include="$(SolutionDir)HashingCmd\bin\Release\net6.0\hashingcmd.*" Exclude="*.dev.json"/>
			<HashingTool Include="$(SolutionDir)HashingCmd\bin\Release\net6.0\*.dll"/>
			<HashingToolRuntimes Include="$(SolutionDir)HashingCmd\bin\Release\net6.0-windows\runtimes\**\*.*"/>
			<HashingTool Include="$(SolutionDir)HashingTool\bin\Release\net6.0-windows\HashingTool.*" Exclude="*.dev.json"/>
			<HashingTool Include="$(SolutionDir)HashingTool\bin\Release\net6.0-windows\*.dll*"/>
			<HashingToolRuntimes  Include="$(SolutionDir)HashingTool\bin\Release\net6.0\runtimes\**\*.*"/>
			<VectoMultistep Include="$(SolutionDir)VECTO3GUI2020\bin\Release\net6.0-windows\VECTOMultistep.*" Exclude="*.dev.json"/>
			<VectoMultistep Include="$(SolutionDir)VECTO3GUI2020\bin\Release\net6.0-windows\*.dll"/>
			<VectoMultistepRuntimes Include="$(SolutionDir)VECTO3GUI2020\bin\Release\net6.0-windows\runtimes\**\*.*"/>
		</ItemGroup>
		<!--MockupDeploy-->

		<ItemGroup Condition="'$(Configuration)'=='MockupDeploy'">
			<!-- All files for net6.0 -->
			<Vecto Include="$(SolutionDir)VECTO\bin\MockupRelease\net6.0-windows\VECTO.*" Exclude="*.dev.json"/>
			<Vecto Include="$(SolutionDir)VECTO\bin\MockupRelease\net6.0-windows\*.dll"/>
			<Vecto Include="$(SolutionDir)VECTO\bin\MockupRelease\net6.0-windows\nlog.config"/>
			<VectoRuntimes Include="$(SolutionDir)VECTO\bin\MockupRelease\net6.0-windows\runtimes\**\*.*"/>
			<VectoCommandLine Include="$(SolutionDir)VectoConsole\bin\MockupRelease\net6.0\vectocmd.*" Exclude="*.dev.json"/>
			<VectoCommandLine Include="$(SolutionDir)VectoConsole\bin\MockupRelease\net6.0\*.dll"/>
			<VectoCommandLineRuntimes Include="$(SolutionDir)VectoConsole\bin\MockupRelease\net6.0\runtimes\**\*.*"/>
			<HashingTool Include="$(SolutionDir)HashingCmd\bin\Release\net6.0\hashingcmd.*" Exclude="*.dev.json"/>
			<HashingTool Include="$(SolutionDir)HashingCmd\bin\Release\net6.0\*.dll"/>
			<HashingToolRuntimes Include="$(SolutionDir)HashingCmd\bin\Release\net6.0\runtimes\**\*.*"/>
			<HashingTool Include="$(SolutionDir)HashingTool\bin\Release\net6.0-windows\HashingTool.*" Exclude="*.dev.json"/>
			<HashingTool Include="$(SolutionDir)HashingTool\bin\Release\net6.0-windows\*.dll*"/>
			<HashingToolRuntimes  Include="$(SolutionDir)HashingTool\bin\Release\net6.0-windows\runtimes\**\*.*"/>
			<VectoMultistep Include="$(SolutionDir)VECTO3GUI2020\bin\MockupRelease\net6.0-windows\VECTOMultistep.*" Exclude="*.dev.json"/>
			<VectoMultistep Include="$(SolutionDir)VECTO3GUI2020\bin\MockupRelease\net6.0-windows\*.dll"/>
			<VectoMultistepRuntimes Include="$(SolutionDir)VECTO3GUI2020\bin\MockupRelease\net6.0-windows\runtimes\**\*.*"/>
		</ItemGroup>

		<Copy SourceFiles="@(HashingTool)" DestinationFolder="$(DeployPath)net60"/>
		<Copy SourceFiles="@(VectoMultistep)" DestinationFolder="$(DeployPath)net60"/>
		<Copy SourceFiles="@(VectoCommandLine)" DestinationFolder="$(DeployPath)net60"/>
		<Copy SourceFiles="@(Vecto)" DestinationFolder="$(DeployPath)net60"/>
		<Copy SourceFiles="@(HashingToolRuntimes)" DestinationFiles="@(HashingToolRuntimes->'$(DeployPath)net60\runtimes\%(RecursiveDir)%(Filename)%(Extension)')"/>
		<Copy SourceFiles="@(VectoMultistepRuntimes)" DestinationFiles="@(VectoMultistepRuntimes->'$(DeployPath)net60\runtimes\%(RecursiveDir)%(Filename)%(Extension)')"/>
		<Copy SourceFiles="@(VectoCommandLineRuntimes)" DestinationFiles="@(VectoCommandLineRuntimes->'$(DeployPath)net60\runtimes\%(RecursiveDir)%(Filename)%(Extension)')"/>
		<Copy SourceFiles="@(VectoRuntimes)" DestinationFiles="@(VectoRuntimes->'$(DeployPath)net60\runtimes\%(RecursiveDir)%(Filename)%(Extension)')"/>
		<Copy SourceFiles="@(XMLConverterCmdLine)" DestinationFolder="$(DeployPath)net60"/>
		<Copy SourceFiles="@(XMLConverterCmdLineRuntimes)" DestinationFiles="@(XMLConverterCmdLineRuntimes->'$(DeployPath)net60\runtimes\%(RecursiveDir)%(Filename)%(Extension)')"/>

		<ItemGroup Condition="'$(Configuration)'=='Deploy'">
			<!-- All files for the VECTO starters -->
			<VectoStart Include="$(SolutionDir)Tools\VECTOStart\bin\Deploy\net48\VECTO.exe" />
			<VectoStart Include="$(SolutionDir)Tools\VECTOMultistepStart\bin\Release\net48\VECTOMultistep.exe" />
			<VectoStart Include="$(SolutionDir)Tools\HashingCmdStart\bin\Release\net48\hashingcmd.exe" />
			<VectoStart Include="$(SolutionDir)Tools\HashingToolStart\bin\Release\net48\HashingTool.exe" />
			<VectoStart Include="$(SolutionDir)Tools\VECTOConsoleStart\bin\Release\net48\vectocmd.exe" />
			<VectoStart Include="$(SolutionDir)Tools\XMLConverterCmdLineStart\bin\Release\net48\XMLConverterCmdLine.exe" />
		</ItemGroup>
		<ItemGroup Condition="'$(Configuration)'=='MockupDeploy'">
			<!-- All files for the VECTO starters -->
			<VectoStart Include="$(SolutionDir)Tools\VECTOStart\bin\MockupDeploy\net48\VECTO.exe" />
			<VectoStart Include="$(SolutionDir)Tools\VECTOMultistepStart\bin\Release\net48\VECTOMultistep.exe" />
			<VectoStart Include="$(SolutionDir)Tools\HashingCmdStart\bin\Release\net48\hashingcmd.exe" />
			<VectoStart Include="$(SolutionDir)Tools\HashingToolStart\bin\Release\net48\HashingTool.exe" />
			<VectoStart Include="$(SolutionDir)Tools\VECTOConsoleStart\bin\Release\net48\vectocmd.exe" />
		</ItemGroup>
		<Copy SourceFiles="@(VectoStart)" DestinationFolder="$(DeployPath)"/>

		<ItemGroup>
			<!-- General Files -->
			<VectoConfigurationSample Include="$(SolutionDir)VECTO\install.ini"/>
			<GenericVehicles Include="$(SolutionDir)Generic Vehicles\**\*.*" Exclude="$(SolutionDir)**\*.vmod;$(SolutionDir)**\*.vsum;$(SolutionDir)**\*RSLT_*.xml;$(SolutionDir)**\*.pdf"/>
			<MissionProfiles Include="$(SolutionDir)VectoCore\VectoCore\Resources\Declaration\MissionCycles\**\*.*"/>
			<DeclarationData Include="$(SolutionDir)VectoCore\VectoCore\Resources\Declaration\**\*.csv" Exclude="$(SolutionDir)**\MissionCycles\**\*.*"/>
			<DeclarationData Include="$(SolutionDir)VectoCore\VectoCore\Resources\Declaration\**\*.md" Exclude="$(SolutionDir)**\MissionCycles\**\*.*"/>
			<DeclarationData Include="$(SolutionDir)VectoCore\VectoCore\Resources\Declaration\**\*.vacc" Exclude="$(SolutionDir)**\MissionCycles\**\*.*"/>
			<DeclarationData Include="$(SolutionDir)VectoCore\VectoCore\Resources\Declaration\**\*.apac" Exclude="$(SolutionDir)**\MissionCycles\**\*.*"/>
			<DeclarationData Include="$(SolutionDir)VectoCore\VectoCore\Resources\Declaration\**\*.aenv" Exclude="$(SolutionDir)**\MissionCycles\**\*.*"/>
			<DeclarationData Include="$(SolutionDir)VectoCore\VectoCore\Resources\Declaration\**\*.aaux" Exclude="$(SolutionDir)**\MissionCycles\**\*.*"/>
			<DeclarationData Include="$(SolutionDir)VectoCore\VectoCore\Resources\Declaration\**\*.ahsm" Exclude="$(SolutionDir)**\MissionCycles\**\*.*"/>
			<DeclarationData Include="$(SolutionDir)VectoCore\VectoCore\Resources\Declaration\**\*.acmp" Exclude="$(SolutionDir)**\MissionCycles\**\*.*"/>
			<DeclarationData Include="$(SolutionDir)VectoCore\VectoCore\Resources\Declaration\**\*.vmap" Exclude="$(SolutionDir)**\MissionCycles\**\*.*"/>
			<VectoXSD Include="$(SolutionDir)VectoCore\VectoCore\Resources\XSD\**\*.*" Exclude="$(SolutionDir)**\*Engineering*;$(SolutionDir)**\Engineering\*"/>


			<!-- VectoXML Examples -->
			<VectoXMLExamples Include="$(SolutionDir)Documentation\XML\Readme.md" />


			<VectoXMLExamplesMultistep Include="$(SolutionDir)VectoCore\VectoCoreTest\TestData\XML\XMLReaderDeclaration\SchemaVersionMultistage.0.1\Airdrag_Sample_v1.xml"/>
			<VectoXMLExamplesMultistep Include="$(SolutionDir)VectoCore\VectoCoreTest\TestData\XML\XMLReaderDeclaration\SchemaVersionMultistage.0.1\Airdrag_Sample_v2.xml"/>

			<VectoXMLExamples_v25 Include="$(SolutionDir)VectoCore\VectoCoreTest\TestData\XML\XMLReaderDeclaration\SchemaVersion2.5\TyreSample.xml"/>

			<VectoXMLExamples_v23 Include="$(SolutionDir)VectoCore\VectoCoreTest\TestData\XML\XMLReaderDeclaration\SchemaVersion2.3\vecto_vehicle-fullElectricSP.xml" />
			<VectoXMLExamples_v23 Include="$(SolutionDir)VectoCore\VectoCoreTest\TestData\XML\XMLReaderDeclaration\SchemaVersion2.3\engineSample.xml" />
			<VectoXMLExamples_v23 Include="$(SolutionDir)VectoCore\VectoCoreTest\TestData\XML\XMLReaderDeclaration\SchemaVersion2.3\engineSample_WHR.xml" />
			<VectoXMLExamples_v23 Include="$(SolutionDir)VectoCore\VectoCoreTest\TestData\XML\XMLReaderDeclaration\SchemaVersion2.3\engineSampleDualModeDualFuel.xml" />
			<VectoXMLExamples_v23 Include="$(SolutionDir)VectoCore\VectoCoreTest\TestData\XML\XMLReaderDeclaration\SchemaVersion2.3\vecto_tyre-sample.xml" />

			<VectoXMLExamples_v22 Include="$(SolutionDir)VectoCore\VectoCoreTest\TestData\XML\XMLReaderDeclaration\SchemaVersion2.2\vecto_tyre-sample.xml" />
			<VectoXMLExamples_v22 Include="$(SolutionDir)VectoCore\VectoCoreTest\TestData\XML\XMLReaderDeclaration\SchemaVersion2.2\vecto_engine-sample.xml" />

			<VectoXMLExamples_v21 Include="$(SolutionDir)VectoCore\VectoCoreTest\TestData\XML\XMLReaderDeclaration\SchemaVersion2.1\vecto_tyre-sample.xml" />
			<VectoXMLExamples_v21 Include="$(SolutionDir)VectoCore\VectoCoreTest\TestData\XML\XMLReaderDeclaration\SchemaVersion2.1\vecto_engine-sample.xml" />

			<VectoXMLExamples_v20 Include="$(SolutionDir)VectoCore\VectoCoreTest\TestData\XML\XMLReaderDeclaration\SchemaVersion2.0\vecto_tyre-sample.xml" />
			<VectoXMLExamples_v20 Include="$(SolutionDir)VectoCore\VectoCoreTest\TestData\XML\XMLReaderDeclaration\SchemaVersion2.0\vecto_engine-sample.xml" />


			<VectoXMLExamples_v10 Include="$(SolutionDir)VectoCore\VectoCoreTest\TestData\XML\XMLReaderDeclaration\SchemaVersion1.0\vecto_engine-sample.xml" />
			<VectoXMLExamples_v10 Include="$(SolutionDir)VectoCore\VectoCoreTest\TestData\XML\XMLReaderDeclaration\vecto_gearbox-sample.xml" />


			<!-- <VectoXMLExamples Include="$(SolutionDir)VectoCore\VectoCoreTest\TestData\XML\XMLReaderDeclaration\*-sample.xml"/> -->
			<UserManual Include="$(SolutionDir)Documentation\User Manual\help.html"/>
			<UserManual Include="$(SolutionDir)Documentation\VectoHashingTool\HashingToolHelp.html"/>
			<UserManual Include="$(SolutionDir)Documentation\MultiStepTool\MultiStepToolHelp.html"/>
			<!-- <ParameterDocu Include="$(SolutionDir)Documentation\ParameterDocumentation\VectoParameterDocumentation.html"/> -->

			<UserManual Include="$(SolutionDir)Documentation\XML\*.png"/>
			<!-- <UserManual Include="$(SolutionDir)Documentation\XML\VectoParameters.html"/> -->
			<UserManual Include="$(SolutionDir)Documentation\User Manual Source\JIRA Quick Start Guide.pdf"/>
			<UserManual Include="$(SolutionDir)Documentation\Cdv_Generator_VECTO3.2.xlsx"/>
			<UserManual Include="$(SolutionDir)Documentation\OVC_IMC.xlsx"/>
			<UserManual Include="$(SolutionDir)Documentation\XML\Documentation_OfficialResults_2ndAmendment_20230425.xlsx"/>
			<ParameterDocu Include="$(SolutionDir)Documentation\XML\ParameterDocumentation\*.*"/>
			<ParameterDocuStyle Include="$(SolutionDir)Documentation\XML\ParameterDocumentation\HTML\css\*.*"/>
			<ReleaseNotesPdf3 Include="$(SolutionDir)Documentation\User Manual Source\Release Notes Vecto3.x.pdf"/>
			<ReleaseNotesPdf4 Include="$(SolutionDir)Documentation\User Manual Source\Release Notes Vecto4.x.pdf"/>
			<ReleaseNotesMd3 Include="$(SolutionDir)Documentation\User Manual Source\ReleaseNotesMDs\ReleaseNotesVecto3x.md"/>
			<ReleaseNotesMd4 Include="$(SolutionDir)Documentation\User Manual Source\ReleaseNotesMDs\ReleaseNotesVecto4x.md"/>
		</ItemGroup>
		<Copy SourceFiles="@(GenericVehicles)" DestinationFiles="@(GenericVehicles->'$(DeployPath)Generic Vehicles\%(RecursiveDir)%(Filename)%(Extension)')" />
		<!-- <Copy SourceFiles="@(DeclarationData)" DestinationFolder="$(DeployPath)Declaration" /> -->
		<Copy SourceFiles="@(DeclarationData)" DestinationFiles="@(DeclarationData->'$(DeployPath)Declaration\%(RecursiveDir)%(Filename)%(Extension)')"/>
		<Copy SourceFiles="@(MissionProfiles)" DestinationFolder="$(DeployPath)Mission Profiles" />

		<Copy SourceFiles="@(VectoXMLExamples)" DestinationFolder="$(DeployPath)XML\Examples" />
		<Copy SourceFiles="@(VectoXMLExamplesMultistep)" DestinationFiles="@(VectoXMLExamplesMultistep->'$(DeployPath)XML\Examples\multistep_v0.1\(Filename)%(Extension)')" />
		<Copy SourceFiles="@(VectoXMLExamples_v25)" DestinationFiles="@(VectoXMLExamples_v25->'$(DeployPath)XML\Examples\v2.5\%(Filename)%(Extension)')" />
		<Copy SourceFiles="@(VectoXMLExamples_v23)" DestinationFiles="@(VectoXMLExamples_v23->'$(DeployPath)XML\Examples\v2.3\%(Filename)%(Extension)')" />
		<Copy SourceFiles="@(VectoXMLExamples_v22)" DestinationFiles="@(VectoXMLExamples_v22->'$(DeployPath)XML\Examples\v2.2\%(Filename)%(Extension)')" />
		<Copy SourceFiles="@(VectoXMLExamples_v20)" DestinationFiles="@(VectoXMLExamples_v20->'$(DeployPath)XML\Examples\v2.0\%(Filename)%(Extension)')" />
		<Copy SourceFiles="@(VectoXMLExamples_V10)" DestinationFiles="@(VectoXMLExamples_v10->'$(DeployPath)XML\Examples\v1.0\%(Filename)%(Extension)')" />


		<Copy SourceFiles="@(VectoXSD)" DestinationFolder="$(DeployPath)XML\XSD" />
		<Copy SourceFiles="@(UserManual)" DestinationFolder="$(DeployPath)User Manual" />

		<Copy SourceFiles="@(ReleaseNotesMd3)" DestinationFiles="$(DeployPath)User Manual\Release Notes Vecto 3.md" />
		<Copy SourceFiles="@(ReleaseNotesMd4)" DestinationFiles="$(DeployPath)User Manual\Release Notes Vecto 4.md" />
		<Copy SourceFiles="@(ReleaseNotesPdf3)" DestinationFiles="$(DeployPath)User Manual\Release Notes Vecto3.x.pdf" />
		<Copy SourceFiles="@(ReleaseNotesPdf4)" DestinationFiles="$(DeployPath)User Manual\Release Notes Vecto4.x.pdf" />
		<Copy SourceFiles="@(VectoConfigurationSample)" DestinationFolder="$(DeployPath)"/>
		<Copy SourceFiles="$(SolutionDir)\Documentation\User Manual Source\README for Mission Profiles Directory.txt" DestinationFiles="$(DeployPath)Mission Profiles\!! README !!.TXT"/>
		<Copy SourceFiles="$(SolutionDir)\Documentation\User Manual Source\README for Declaration Directory.txt" DestinationFiles="$(DeployPath)Declaration\!! README !!.TXT"/>

		<Copy SourceFiles="@(ParameterDocu)" DestinationFolder="$(DeployPath)User Manual\ParameterDocumentation"/>
		<Copy SourceFiles="@(ParameterDocuStyle)" DestinationFolder="$(DeployPath)User Manual\ParameterDocumentation\HTML\css"/>



		<!-- <Copy SourceFiles="$(ParameterDocuStyle)" DestinationFolder="$(DeployPath)User Manual\Parameter Documentation\HTML\css"/> -->
		<!-- NuGet Files-->
		<ItemGroup Condition="'$(Configuration)'=='Deploy'">
			<VectoNuget Include ="$(SolutionDir)VectoCore\VectoCore\bin\Release\*$(Version)*.nupkg" />
			<VectoNuget Include ="$(SolutionDir)VectoCommon\VectoCommon\bin\Release\*$(Version)*.nupkg" />
			<VectoNuget Include ="$(SolutionDir)VectoCommon\VectoHashing\bin\Release\*$(Version)*.nupkg" />
		</ItemGroup>
		<ItemGroup Condition="'$(Configuration)'=='MockupDeploy'">
			<VectoNuget Include ="$(SolutionDir)VectoCore\VectoCore\bin\MockupRelease\*$(Version)*.nupkg" />
			<VectoNuget Include ="$(SolutionDir)VectoCommon\VectoCommon\bin\Release\*$(Version)*.nupkg" />
			<VectoNuget Include ="$(SolutionDir)VectoCommon\VectoHashing\bin\Release\*$(Version)*.nupkg" />
		</ItemGroup>

		<Copy SourceFiles="@(VectoNuget)" DestinationFolder ="$(NuGetPath)"/>

		<Copy SourceFiles="@(VectoNuget)" DestinationFolder ="$(DeployPath)NuGet"/>

		<PropertyGroup>
			<NugetDestinationZip>$(ReleasePath)$(CurrentDate)-VECTO-NuGet-$(Version).zip</NugetDestinationZip>
			<NugetDestinationZip Condition="'$(Configuration)'=='MockupDeploy'">$(ReleasePath)$(CurrentDate)-VECTO-NuGet-$(Version).zip</NugetDestinationZip>
		</PropertyGroup>
		<ZipDirectory SourceDirectory="$(NuGetPath)" DestinationFile="$(NugetDestinationZip)" Overwrite="true"/>

		<PropertyGroup>
			<DestinationZip>$(ReleasePath)$(CurrentDate)-VECTO-$(Version).zip</DestinationZip>
			<DestinationZip Condition="'$(Configuration)'=='MockupDeploy'">$(ReleasePath)$(CurrentDate)-VECTO-$(Version).zip</DestinationZip>
		</PropertyGroup>
		<ZipDirectory SourceDirectory="$(SolutionDir)Deploy\" DestinationFile="$(DestinationZip)" Overwrite="true"/>
	</Target>
</Project>