<Project>
  <PropertyGroup>
    <!-- For a Release Candidate uncomment the following line: -->
    <!--<DefineConstants>$(DefineConstants),RELEASE_CANDIDATE</DefineConstants>-->

    <!-- For a Release uncomment the following line: -->
    <!--<DefineConstants>$(DefineConstants),CERTIFICATION_RELEASE</DefineConstants>-->

    <!-- Global VECTO Version -->
    <MainProductVersion>0.7.7</MainProductVersion>
  </PropertyGroup>

  <!-- The following settings are used as default values for ALL projects -->
  <PropertyGroup>
    <TargetFramework>net45</TargetFramework>
    <VersionPrefix>$(MainProductVersion).$([System.DateTime]::UtcNow.Subtract($([System.DateTime]::new(2015,1,1))).Days)</VersionPrefix>
    <Authors>Graz University of Technology</Authors>
    <Company>European Union</Company>
    <Copyright>Copyright © 2012-$([System.DateTime]::UtcNow.Year)</Copyright>
  </PropertyGroup>

  <PropertyGroup>
    <VersionSuffix>DEV</VersionSuffix>
  </PropertyGroup>
  <PropertyGroup Condition="$(DefineConstants.Contains('RELEASE_CANDIDATE'))">
    <VersionSuffix>RC</VersionSuffix>
  </PropertyGroup>
  <PropertyGroup Condition="$(DefineConstants.Contains('CERTIFICATION_RELEASE'))">
    <VersionSuffix></VersionSuffix>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    <DefineConstants>DEBUG</DefineConstants>
    <!--<DefineConstants>DEBUG;TRACE</DefineConstants>-->
    <PlatformTarget>AnyCPU</PlatformTarget>
    <WarningLevel>5</WarningLevel>
    <DebugType>pdbonly</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <CheckForOverflowUnderflow>true</CheckForOverflowUnderflow>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DefineConstants />
    <DebugType>none</DebugType>
    <WarningLevel>5</WarningLevel>
    <DebugSymbols>false</DebugSymbols>
  </PropertyGroup>
</Project>