<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>VectoConsole</RootNamespace>
    <AssemblyName>vectocmd</AssemblyName>
    <ApplicationIcon>VECTO.ico</ApplicationIcon>
    <TargetFrameworks>net45;net48;net6.0</TargetFrameworks>
    <DefineConstants />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ninject" Version="3.3.6" />
    <PackageReference Include="NLog" Version="4.7.13" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Components\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Cycles\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="job.vecto">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VectoCore\VectoCore\VectoCore.csproj" />
  </ItemGroup>
</Project>