<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>VectoConsole</RootNamespace>
    <AssemblyName>vectocmd</AssemblyName>
    <ApplicationIcon>VECTO.ico</ApplicationIcon>
    <TargetFrameworks>net48;net6.0</TargetFrameworks>
    <DefineConstants />
    <Configurations>Debug;Release;MockupDebug;MockupRelease</Configurations>
  </PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MockupDebug|net48|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MockupDebug|net6.0|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>
	<PropertyGroup Condition="('$(Configuration)' == 'MockupRelease') Or ('$(Configuration)' == 'MockupDebug')">
		<DefineConstants>$(DefineConstants);MOCKUP</DefineConstants>
	</PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Ninject" Version="3.3.6" />
    <PackageReference Include="NLog" Version="4.7.13" />
  </ItemGroup>

  <ItemGroup>
    <None Include="Components\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="Cycles\*.*">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Include="job.vecto">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VectoCommon\VectoCommon\VectoCommon.csproj" />
    <ProjectReference Include="..\VectoCore\VectoCore\VectoCore.csproj" />
  </ItemGroup>

	<!--<Choose>
		<When Condition="$([System.Text.RegularExpressions.Regex]::IsMatch(&#xD;&#xA;         $(DefineConstants), '^(.*;)*MOCKUP(;.*)*$'))">
			<ItemGroup>
				<ProjectReference Include="..\VectoMockup\VectoMockup\VectoMockup.csproj" />

			</ItemGroup>
			--><!--<PropertyGroup>
				<DefineConstants>MOCKUP</DefineConstants>
			</PropertyGroup>--><!--
		</When>
	</Choose>-->
</Project>