[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("VectoAPI")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("VectoEngineeringAPI")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("VectoXML")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("XMLTest")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("VECTO")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("VectoCoreTest")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("VectoAPITest")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("VectoXML")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("XMLTest")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("VECTO_GIT")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("VectoAuxiliariesTests")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("VECTO3")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("VECTOMultistage")]
[assembly: System.Runtime.CompilerServices.InternalsVisibleTo("Vecto3GUI2020Test")]

