<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Version Information (only needed if it differs from Global VECTO Version)-->
    <OutputType>WinExe</OutputType>
    <RootNamespace>VECTO3GUI2020</RootNamespace>
    <AssemblyName>VECTOMultistep</AssemblyName>
    <ApplicationIcon>Resources\Icons\Icon2.ico</ApplicationIcon>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <PublishTrimmed>false</PublishTrimmed>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <TargetFrameworks>net48;net6.0-windows</TargetFrameworks>

    <Configurations>Debug;Release;MockupDebug;MockupRelease</Configurations>
</PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MockupDebug|net48|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MockupDebug|net6.0-windows|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>
	<PropertyGroup Condition="('$(Configuration)' == 'MockupRelease') Or ('$(Configuration)' == 'MockupDebug')">
		<DefineConstants>$(DefineConstants);MOCKUP</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MockupDebug|net6.0-windows|AnyCPU'">
	  <DebugType>full</DebugType>
	</PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.0" />
    <PackageReference Include="InteractiveDataDisplay.WPF" Version="1.0.0" NoWarn="NU1701" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.39" NoWarn="NU1701" />
    <PackageReference Include="Ninject" Version="3.3.6" />
    <PackageReference Include="Ninject.Extensions.ContextPreservation" Version="3.3.1" />
    <PackageReference Include="Ninject.Extensions.Factory" Version="3.3.3" />
    <PackageReference Include="PresentationFramework.Aero2" Version="1.0.1" NoWarn="NU1701" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VectoCommon\VectoCommon\VectoCommon.csproj" />
    <ProjectReference Include="..\VectoCore\VectoCore\VectoCore.csproj" />
  </ItemGroup>

	<!--<Choose>
		<When Condition="$([System.Text.RegularExpressions.Regex]::IsMatch(&#xD;&#xA;         $(DefineConstants), '^(.*;)*MOCKUP(;.*)*$'))">
			<ItemGroup>
				<ProjectReference Include="..\VectoMockup\VectoMockup\VectoMockup.csproj" />
			</ItemGroup>
		</When>
	</Choose>-->



  <ItemGroup>
    <InternalsVisibleTo Include="Vecto3GUI2020Test" />
  </ItemGroup>

  <ItemGroup>

	  <Compile Update="Properties\GUILabels.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>GUILabels.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\BusStrings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>BusStrings.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Strings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DesignTime>True</DesignTime>
      <DependentUpon>Strings.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Settings.cs" />
    <Compile Update="Properties\Settings.Designer.cs">
      <AutoGen>True</AutoGen>
      <DependentUpon>Settings.settings</DependentUpon>
      <DesignTimeSharedInput>True</DesignTimeSharedInput>
    </Compile>
    <EmbeddedResource Update="Properties\BusStrings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>BusStrings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\GUILabels.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>GUILabels.Designer.cs</LastGenOutput>
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Strings.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Strings.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <None Include="Properties\Settings.settings">
      <Generator>SettingsSingleFileGenerator</Generator>
      <LastGenOutput>Settings.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\Icons\Icon2.ico" />
    <Resource Include="Resources\Icons\folderpicker.ico" />
    <Resource Include="Resources\Icons\Trash_16x.ico" />
    <Resource Include="Resources\Images\JRC-About.png" />
    <Resource Include="Resources\Images\VECTO-About.png" />
  </ItemGroup>

  <ItemGroup>
    <Page Update="MainWindow.xaml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Page>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Util\XML\Implementation\DocumentWriter\" />
  </ItemGroup>


    <!--Workauround for build error-->
	<!--https://github.com/dotnet/wpf/pull/6680-->
    <!--https://github.com/dotnet/wpf/pull/6680#issuecomment-1183455941-->
	<Target Name="RemoveDuplicateAnalyzers" BeforeTargets="CoreCompile">

		<RemoveDuplicates Inputs="@(Analyzer)">
			<Output TaskParameter="Filtered" ItemName="FilteredAnalyzer" />
		</RemoveDuplicates>

		<ItemGroup>
			<Analyzer Remove="@(Analyzer)" />
			<Analyzer Include="@(FilteredAnalyzer)" />
		</ItemGroup>
	</Target>

    <!--END-->
</Project>