<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
	<OutputType>WinExe</OutputType>
	<StartupObject>Sub Main</StartupObject>
	<RootNamespace>TUGraz.VECTO</RootNamespace>
	<AssemblyName>VECTO</AssemblyName>
	<ApplicationIcon>Resources\Icon2.ico</ApplicationIcon>
	<OptionStrict>On</OptionStrict>
	<UseWindowsForms>true</UseWindowsForms>
	<GenerateResourceUsePreserializedResources>true</GenerateResourceUsePreserializedResources>
	<MyType>WindowsForms</MyType>
		<TargetFrameworks>net48;net6.0-windows;net8.0-windows</TargetFrameworks>
		<TargetFrameworks Condition="'$(Configuration)' == 'Release'">net48;net6.0-windows;net8.0-windows</TargetFrameworks>
		<TargetFrameworks Condition="'$(Configuration)' == 'Deploy'">net48;net6.0-windows;net8.0-windows</TargetFrameworks>
		<TargetFrameworks Condition="'$(Configuration)' == 'MockupDeploy'">net48;net6.0-windows;net8.0-windows</TargetFrameworks>
		<DefineTrace>false</DefineTrace>

		<Configurations>Debug;Release;MockupDebug;MockupRelease</Configurations>
		<AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
		<UseWindowsForms>true</UseWindowsForms>
	</PropertyGroup>
	<!--Final Define Constants https://developercommunity.visualstudio.com/t/vbprojuser-defineconstants-dont-affect/865956-->
	<PropertyGroup Condition="('$(Configuration)' == 'MockupRelease') Or ('$(Configuration)' == 'MockupDebug')">
		<FinalDefineConstants>$(FinalDefineConstants),MOCKUP</FinalDefineConstants>
		<DefineConstants>$(DefineConstants),MOCKUP</DefineConstants>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MockupDebug|net48|AnyCPU'">
	  <DebugType>full</DebugType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MockupDebug|net6.0-windows|AnyCPU'">
	  <DebugType>full</DebugType>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MockupDebug|net8.0-windows|AnyCPU'">
	  <DebugType>full</DebugType>
	</PropertyGroup>
  <ItemGroup>
    <None Remove="nlog.config" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="nlog.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

	<ItemGroup>
	<PackageReference Include="Microsoft.VisualBasic" Version="10.3.0" />
	<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
	<PackageReference Include="Ninject.Extensions.Factory" Version="3.3.3" />
	<PackageReference Include="NLog" Version="4.7.13" />
	<PackageReference Include="System.Resources.Extensions" Version="8.0.0" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' == 'net48'">
		<Reference Include="System.ComponentModel.DataAnnotations" />
		<Reference Include="System.Windows.Forms.DataVisualization" />
	</ItemGroup>
	<ItemGroup Condition="'$(TargetFramework)' != 'net48'">
		<PackageReference Include="System.Windows.Forms.DataVisualization">
			<Version>1.0.0-prerelease.20110.1</Version>
		</PackageReference>
	</ItemGroup>
	<ItemGroup>
		<ProjectReference Include="..\HashingTool\HashingTool.csproj" />
	</ItemGroup>
	<ItemGroup>
		<Import Include="System" />
		<Import Include="System.Collections" />
		<Import Include="System.Data" />
		<Import Include="System.Drawing" />
		<Import Include="System.Diagnostics" />
		<Import Include="System.Windows.Forms" />
	</ItemGroup>

	<ItemGroup>
	<Compile Update="My Project\Application.Designer.vb">
	  <DesignTime>True</DesignTime>
	  <AutoGen>True</AutoGen>
	  <DependentUpon>Application.myapp</DependentUpon>
	</Compile>
	<Compile Update="My Project\Resources.Designer.vb">
	  <DesignTime>True</DesignTime>
	  <AutoGen>True</AutoGen>
	  <DependentUpon>Resources.resx</DependentUpon>
	</Compile>
	<EmbeddedResource Update="My Project\Resources.resx">
	  <CustomToolNamespace>My.Resources</CustomToolNamespace>
	  <Generator>VbMyResourcesResXFileCodeGenerator</Generator>
	  <LastGenOutput>Resources.Designer.vb</LastGenOutput>
	</EmbeddedResource>
	<Compile Update="My Project\Settings.Designer.vb">
	  <DesignTimeSharedInput>True</DesignTimeSharedInput>
	  <AutoGen>True</AutoGen>
	  <DependentUpon>Settings.settings</DependentUpon>
	</Compile>
	<None Update="My Project\Application.myapp">
	  <Generator>MyApplicationCodeGenerator</Generator>
	  <LastGenOutput>Application.Designer.vb</LastGenOutput>
	</None>
	<None Update="My Project\Settings.settings">
	  <CustomToolNamespace>My</CustomToolNamespace>
	  <Generator>SettingsSingleFileGenerator</Generator>
	  <LastGenOutput>Settings.Designer.vb</LastGenOutput>
	</None>
	</ItemGroup>

	<ItemGroup>
	<EmbeddedResource Update="Resources\4x2r.png" />
	<EmbeddedResource Update="Resources\4x2rt.png" />
	<EmbeddedResource Update="Resources\4x2tt.png" />
	<EmbeddedResource Update="Resources\6x2r.png" />
	<EmbeddedResource Update="Resources\6x2rt.png" />
	<EmbeddedResource Update="Resources\6x2tt.png" />
	<EmbeddedResource Update="Resources\Undef.png" />
	</ItemGroup>


</Project>