<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <RootNamespace>HashingTool</RootNamespace>
    <AssemblyName>HashingTool</AssemblyName>
    <UseWPF>true</UseWPF>
    <TargetFrameworks>net48;net6.0-windows</TargetFrameworks>

    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <ApplicationIcon>HashingIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VectoCommon\VectoCommon\VectoCommon.csproj" />
    <ProjectReference Include="..\VectoCommon\VectoHashing\VectoHashing.csproj" />
    <ProjectReference Include="..\VectoCore\VectoCore\VectoCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\HashingIcon.ico" />
    <Resource Include="Resources\IVT_91x44.png" />
    <Resource Include="Resources\JRC-About.png" />
    <Resource Include="Resources\TUG_91x34.png" />
    <Resource Include="Resources\VECTO_Hashing.png" />
    <Resource Include="HashingIcon.ico" />
    <Resource Include="Resources\EuropeanCommission.jpg" />
  </ItemGroup>
</Project>