<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Version Information (only needed if it differs from Global VECTO Version)-->
    <MainProductVersion>0.2.0</MainProductVersion>
    <VersionPrefix>$(MainProductVersion).$([System.DateTime]::UtcNow.Subtract($([System.DateTime]::new(2015,1,1))).Days)</VersionPrefix>

    <OutputType>WinExe</OutputType>
    <RootNamespace>HashingTool</RootNamespace>
    <AssemblyName>HashingTool</AssemblyName>
    <UseWPF>true</UseWPF>
    <TargetFrameworks>net48;net6.0-windows</TargetFrameworks>
     
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
    <ApplicationIcon>HashingIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VectoCommon\VectoCommon\VectoCommon.csproj" />
    <ProjectReference Include="..\VectoCommon\VectoHashing\VectoHashing.csproj" />
    <ProjectReference Include="..\VectoCore\VectoCore\VectoCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\HashingIcon.ico" />
    <Resource Include="Resources\IVT_91x44.png" />
    <Resource Include="Resources\JRC-About.png" />
    <Resource Include="Resources\TUG_91x34.png" />
    <Resource Include="Resources\VECTO_Hashing.png" />
    <Resource Include="HashingIcon.ico" />
    <Resource Include="Resources\EuropeanCommission.jpg" />
  </ItemGroup>
</Project>