<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>VectoHashingTest</RootNamespace>
    <AssemblyName>VectoHashingTest</AssemblyName>
    <TargetFrameworks>net6.0</TargetFrameworks>
    <DefineConstants />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Ninject" Version="3.3.6" />
    <PackageReference Include="NUnit" Version="3.13.3" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.4.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.6.0" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="7.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\VectoCore\VectoCore\VectoCore.csproj" />
    <ProjectReference Include="..\VectoCommon\VectoCommon.csproj" />
    <ProjectReference Include="..\VectoHashing\VectoHashing.csproj" />
</ItemGroup>

  <ItemGroup>
    <None Include="Testdata\**\*.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <None Include="TestData\**\*.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>