Public Interface IDiagnostics



Property AA_NonSmartAlternatorsEfficiency As single
Property AA_SmartIdleCurrent_Amps As single
Property AA_SmartIdleAlternatorsEfficiency As single
Property AA_SmartTractionCurrent_Amps As single
Property AA_SmartTractionAlternatorEfficiency As single
Property AA_SmartOverrunCurrent_Amps As Single
Property AA_SmartOverrunAlternatorEfficiency As Single
Property AA_CompressorFlowRate_LitrePerSec As Single
Property AA_OverrunFlag As integer
Property AA_EngineIdleFlag As integer
Property AA_CompressorFlag As integer
Property AA_TotalCycleFC_BeforeSSandWHTCcorrection_Grams As single
Property AA_TotalCycleFC_BeforeSSandWHTCcorrection_Litres As single



End Interface
