//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUGraz.VectoCore.Resources{
	using System;
	
	
	/// <summary>
	///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
	/// </summary>
	// Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
	// -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
	// Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
	// mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	public class XMLNames {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal XMLNames() {
		}
		
		/// <summary>
		///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TUGraz.VectoCore.Resources.XMLNames", typeof(XMLNames).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
		///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		public static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Efficiency ähnelt.
		/// </summary>
		public static string AngleDrive_Efficiency {
			get {
				return ResourceManager.GetString("AngleDrive_Efficiency", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Entry ähnelt.
		/// </summary>
		public static string Angledrive_LossMap_Entry {
			get {
				return ResourceManager.GetString("Angledrive_LossMap_Entry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Ratio ähnelt.
		/// </summary>
		public static string AngleDrive_Ratio {
			get {
				return ResourceManager.GetString("AngleDrive_Ratio", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die TorqueLossMap ähnelt.
		/// </summary>
		public static string AngleDrive_TorqueLossMap {
			get {
				return ResourceManager.GetString("AngleDrive_TorqueLossMap", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die auxiliarySpeed ähnelt.
		/// </summary>
		public static string Aux_AuxMap_AuxiliarySpeed_Attr {
			get {
				return ResourceManager.GetString("Aux_AuxMap_AuxiliarySpeed_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die mechanicalPower ähnelt.
		/// </summary>
		public static string Aux_AuxMap_MechanicalPower_Attr {
			get {
				return ResourceManager.GetString("Aux_AuxMap_MechanicalPower_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Auxiliary ähnelt.
		/// </summary>
		public static string Auxiliaries_Auxiliary {
			get {
				return ResourceManager.GetString("Auxiliaries_Auxiliary", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die AuxMap ähnelt.
		/// </summary>
		public static string Auxiliaries_Auxiliary_AuxMap {
			get {
				return ResourceManager.GetString("Auxiliaries_Auxiliary_AuxMap", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Entry ähnelt.
		/// </summary>
		public static string Auxiliaries_Auxiliary_AuxMap_Entry {
			get {
				return ResourceManager.GetString("Auxiliaries_Auxiliary_AuxMap_Entry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die ConstantAuxLoad ähnelt.
		/// </summary>
		public static string Auxiliaries_Auxiliary_ConstantAuxLoad {
			get {
				return ResourceManager.GetString("Auxiliaries_Auxiliary_ConstantAuxLoad", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die EfficiencyAuxSupply ähnelt.
		/// </summary>
		public static string Auxiliaries_Auxiliary_EfficiencyAuxSupply {
			get {
				return ResourceManager.GetString("Auxiliaries_Auxiliary_EfficiencyAuxSupply", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die EfficiencyToEngine ähnelt.
		/// </summary>
		public static string Auxiliaries_Auxiliary_EfficiencyToEngine {
			get {
				return ResourceManager.GetString("Auxiliaries_Auxiliary_EfficiencyToEngine", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die id ähnelt.
		/// </summary>
		public static string Auxiliaries_Auxiliary_ID_Attr {
			get {
				return ResourceManager.GetString("Auxiliaries_Auxiliary_ID_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Technology ähnelt.
		/// </summary>
		public static string Auxiliaries_Auxiliary_Technology {
			get {
				return ResourceManager.GetString("Auxiliaries_Auxiliary_Technology", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die TransmissionRatioToEngine ähnelt.
		/// </summary>
		public static string Auxiliaries_Auxiliary_TransmissionRatioToEngine {
			get {
				return ResourceManager.GetString("Auxiliaries_Auxiliary_TransmissionRatioToEngine", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die supplyPower ähnelt.
		/// </summary>
		public static string Auxr_AuxMapMapping_SupplyPower_Attr {
			get {
				return ResourceManager.GetString("Auxr_AuxMapMapping_SupplyPower_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Efficiency ähnelt.
		/// </summary>
		public static string Axlegear_Efficiency {
			get {
				return ResourceManager.GetString("Axlegear_Efficiency", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Ratio ähnelt.
		/// </summary>
		public static string Axlegear_Ratio {
			get {
				return ResourceManager.GetString("Axlegear_Ratio", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die TorqueLossMap ähnelt.
		/// </summary>
		public static string Axlegear_TorqueLossMap {
			get {
				return ResourceManager.GetString("Axlegear_TorqueLossMap", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Entry ähnelt.
		/// </summary>
		public static string Axlegear_TorqueLossMap_Entry {
			get {
				return ResourceManager.GetString("Axlegear_TorqueLossMap_Entry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Axles ähnelt.
		/// </summary>
		public static string AxleWheels_Axles {
			get {
				return ResourceManager.GetString("AxleWheels_Axles", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Axle ähnelt.
		/// </summary>
		public static string AxleWheels_Axles_Axle {
			get {
				return ResourceManager.GetString("AxleWheels_Axles_Axle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die axleNumber ähnelt.
		/// </summary>
		public static string AxleWheels_Axles_Axle_AxleNumber_Attr {
			get {
				return ResourceManager.GetString("AxleWheels_Axles_Axle_AxleNumber_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die axleType ähnelt.
		/// </summary>
		public static string AxleWheels_Axles_Axle_AxleType_Attr {
			get {
				return ResourceManager.GetString("AxleWheels_Axles_Axle_AxleType_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Dimension ähnelt.
		/// </summary>
		public static string AxleWheels_Axles_Axle_Dimension {
			get {
				return ResourceManager.GetString("AxleWheels_Axles_Axle_Dimension", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die DynamicTyreRadius ähnelt.
		/// </summary>
		public static string AxleWheels_Axles_Axle_DynamicTyreRadius {
			get {
				return ResourceManager.GetString("AxleWheels_Axles_Axle_DynamicTyreRadius", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die FzISO ähnelt.
		/// </summary>
		public static string AxleWheels_Axles_Axle_FzISO {
			get {
				return ResourceManager.GetString("AxleWheels_Axles_Axle_FzISO", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Inertia ähnelt.
		/// </summary>
		public static string AxleWheels_Axles_Axle_Inertia {
			get {
				return ResourceManager.GetString("AxleWheels_Axles_Axle_Inertia", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die RRCISO ähnelt.
		/// </summary>
		public static string AxleWheels_Axles_Axle_RRCISO {
			get {
				return ResourceManager.GetString("AxleWheels_Axles_Axle_RRCISO", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die twinTyres ähnelt.
		/// </summary>
		public static string AxleWheels_Axles_Axle_TwinTyres_Attr {
			get {
				return ResourceManager.GetString("AxleWheels_Axles_Axle_TwinTyres_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die WeightShare ähnelt.
		/// </summary>
		public static string AxleWheels_Axles_Axle_WeightShare {
			get {
				return ResourceManager.GetString("AxleWheels_Axles_Axle_WeightShare", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Angledrive ähnelt.
		/// </summary>
		public static string Component_Angledrive {
			get {
				return ResourceManager.GetString("Component_Angledrive", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Auxiliaries ähnelt.
		/// </summary>
		public static string Component_Auxiliaries {
			get {
				return ResourceManager.GetString("Component_Auxiliaries", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Axlegear ähnelt.
		/// </summary>
		public static string Component_Axlegear {
			get {
				return ResourceManager.GetString("Component_Axlegear", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die AxleWheels ähnelt.
		/// </summary>
		public static string Component_AxleWheels {
			get {
				return ResourceManager.GetString("Component_AxleWheels", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Creator ähnelt.
		/// </summary>
		public static string Component_Creator {
			get {
				return ResourceManager.GetString("Component_Creator", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Date ähnelt.
		/// </summary>
		public static string Component_Date {
			get {
				return ResourceManager.GetString("Component_Date", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die DriverModel ähnelt.
		/// </summary>
		public static string Component_DriverModel {
			get {
				return ResourceManager.GetString("Component_DriverModel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Engine ähnelt.
		/// </summary>
		public static string Component_Engine {
			get {
				return ResourceManager.GetString("Component_Engine", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Gearbox ähnelt.
		/// </summary>
		public static string Component_Gearbox {
			get {
				return ResourceManager.GetString("Component_Gearbox", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die id ähnelt.
		/// </summary>
		public static string Component_ID_Attr {
			get {
				return ResourceManager.GetString("Component_ID_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die MakeAndModel ähnelt.
		/// </summary>
		public static string Component_MakeAndModel {
			get {
				return ResourceManager.GetString("Component_MakeAndModel", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Retarder ähnelt.
		/// </summary>
		public static string Component_Retarder {
			get {
				return ResourceManager.GetString("Component_Retarder", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die TorqueConverter ähnelt.
		/// </summary>
		public static string Component_TorqueConverter {
			get {
				return ResourceManager.GetString("Component_TorqueConverter", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die TypeId ähnelt.
		/// </summary>
		public static string Component_TypeId {
			get {
				return ResourceManager.GetString("Component_TypeId", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Vehicle ähnelt.
		/// </summary>
		public static string Component_Vehicle {
			get {
				return ResourceManager.GetString("Component_Vehicle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Vendor ähnelt.
		/// </summary>
		public static string Component_Vendor {
			get {
				return ResourceManager.GetString("Component_Vendor", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Data ähnelt.
		/// </summary>
		public static string ComponentDataWrapper {
			get {
				return ResourceManager.GetString("ComponentDataWrapper", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die decisionFactorVel ähnelt.
		/// </summary>
		public static string Driver_CoastingDFTargetSpeedLookupMapping_DecisionFactor_Attr {
			get {
				return ResourceManager.GetString("Driver_CoastingDFTargetSpeedLookupMapping_DecisionFactor_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die targetVelocity ähnelt.
		/// </summary>
		public static string Driver_CoastingDFTargetSpeedLookupMapping_TargetVelocity_Attr {
			get {
				return ResourceManager.GetString("Driver_CoastingDFTargetSpeedLookupMapping_TargetVelocity_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die decisionFactorDrop ähnelt.
		/// </summary>
		public static string Driver_CoastingDFVelocityDropLookupMapping_DecisionFactorDrop_Attr {
			get {
				return ResourceManager.GetString("Driver_CoastingDFVelocityDropLookupMapping_DecisionFactorDrop_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die velocityDrop ähnelt.
		/// </summary>
		public static string Driver_CoastingDFVelocityDropLookupMapping_VelocityDrop_Attr {
			get {
				return ResourceManager.GetString("Driver_CoastingDFVelocityDropLookupMapping_VelocityDrop_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die DriverAccelerationCurve ähnelt.
		/// </summary>
		public static string DriverModel_DriverAccelerationCurve {
			get {
				return ResourceManager.GetString("DriverModel_DriverAccelerationCurve", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Entry ähnelt.
		/// </summary>
		public static string DriverModel_DriverAccelerationCurve_Entry {
			get {
				return ResourceManager.GetString("DriverModel_DriverAccelerationCurve_Entry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die LookAheadCoasting ähnelt.
		/// </summary>
		public static string DriverModel_LookAheadCoasting {
			get {
				return ResourceManager.GetString("DriverModel_LookAheadCoasting", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die DecisionFactorOffset ähnelt.
		/// </summary>
		public static string DriverModel_LookAheadCoasting_DecisionFactorOffset {
			get {
				return ResourceManager.GetString("DriverModel_LookAheadCoasting_DecisionFactorOffset", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die DecisionFactorScaling ähnelt.
		/// </summary>
		public static string DriverModel_LookAheadCoasting_DecisionFactorScaling {
			get {
				return ResourceManager.GetString("DriverModel_LookAheadCoasting_DecisionFactorScaling", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Enabled ähnelt.
		/// </summary>
		public static string DriverModel_LookAheadCoasting_Enabled {
			get {
				return ResourceManager.GetString("DriverModel_LookAheadCoasting_Enabled", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die MinSpeed ähnelt.
		/// </summary>
		public static string DriverModel_LookAheadCoasting_MinSpeed {
			get {
				return ResourceManager.GetString("DriverModel_LookAheadCoasting_MinSpeed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die PreviewDistanceFactor ähnelt.
		/// </summary>
		public static string DriverModel_LookAheadCoasting_PreviewDistanceFactor {
			get {
				return ResourceManager.GetString("DriverModel_LookAheadCoasting_PreviewDistanceFactor", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die SpeedDependentDecisionFactor ähnelt.
		/// </summary>
		public static string DriverModel_LookAheadCoasting_SpeedDependentDecisionFactor {
			get {
				return ResourceManager.GetString("DriverModel_LookAheadCoasting_SpeedDependentDecisionFactor", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die VelocityDropDecisionFactor ähnelt.
		/// </summary>
		public static string DriverModel_LookAheadCoasting_VelocityDropDecisionFactor {
			get {
				return ResourceManager.GetString("DriverModel_LookAheadCoasting_VelocityDropDecisionFactor", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Overspeed ähnelt.
		/// </summary>
		public static string DriverModel_Overspeed {
			get {
				return ResourceManager.GetString("DriverModel_Overspeed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die AllowedOverspeed ähnelt.
		/// </summary>
		public static string DriverModel_Overspeed_AllowedOverspeed {
			get {
				return ResourceManager.GetString("DriverModel_Overspeed_AllowedOverspeed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die AllowedUnderspeed ähnelt.
		/// </summary>
		public static string DriverModel_Overspeed_AllowedUnderspeed {
			get {
				return ResourceManager.GetString("DriverModel_Overspeed_AllowedUnderspeed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die MinSpeed ähnelt.
		/// </summary>
		public static string DriverModel_Overspeed_MinSpeed {
			get {
				return ResourceManager.GetString("DriverModel_Overspeed_MinSpeed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Mode ähnelt.
		/// </summary>
		public static string DriverModel_Overspeed_Mode {
			get {
				return ResourceManager.GetString("DriverModel_Overspeed_Mode", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die ShiftStrategyParameters ähnelt.
		/// </summary>
		public static string DriverModel_ShiftStrategyParameters {
			get {
				return ResourceManager.GetString("DriverModel_ShiftStrategyParameters", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die DownshiftAfterUpshiftDelay ähnelt.
		/// </summary>
		public static string DriverModel_ShiftStrategyParameters_DownshiftAfterUpshiftDelay {
			get {
				return ResourceManager.GetString("DriverModel_ShiftStrategyParameters_DownshiftAfterUpshiftDelay", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die StartAcceleration ähnelt.
		/// </summary>
		public static string DriverModel_ShiftStrategyParameters_StartAcceleration {
			get {
				return ResourceManager.GetString("DriverModel_ShiftStrategyParameters_StartAcceleration", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die StartSpeed ähnelt.
		/// </summary>
		public static string DriverModel_ShiftStrategyParameters_StartSpeed {
			get {
				return ResourceManager.GetString("DriverModel_ShiftStrategyParameters_StartSpeed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die StartTorqueReserve ähnelt.
		/// </summary>
		public static string DriverModel_ShiftStrategyParameters_StartTorqueReserve {
			get {
				return ResourceManager.GetString("DriverModel_ShiftStrategyParameters_StartTorqueReserve", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die TimeBetweenGearshift ähnelt.
		/// </summary>
		public static string DriverModel_ShiftStrategyParameters_TimeBetweenGearshift {
			get {
				return ResourceManager.GetString("DriverModel_ShiftStrategyParameters_TimeBetweenGearshift", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die TorqueReserve ähnelt.
		/// </summary>
		public static string DriverModel_ShiftStrategyParameters_TorqueReserve {
			get {
				return ResourceManager.GetString("DriverModel_ShiftStrategyParameters_TorqueReserve", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die UpshiftAfterDownshiftDelay ähnelt.
		/// </summary>
		public static string DriverModel_ShiftStrategyParameters_UpshiftAfterDownshiftDelay {
			get {
				return ResourceManager.GetString("DriverModel_ShiftStrategyParameters_UpshiftAfterDownshiftDelay", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die UpshiftMinAcceleration ähnelt.
		/// </summary>
		public static string DriverModel_ShiftStrategyParameters_UpshiftMinAcceleration {
			get {
				return ResourceManager.GetString("DriverModel_ShiftStrategyParameters_UpshiftMinAcceleration", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die ColdHotBalancingFactor ähnelt.
		/// </summary>
		public static string Engine_ColdHotBalancingFactor {
			get {
				return ResourceManager.GetString("Engine_ColdHotBalancingFactor", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Displacement ähnelt.
		/// </summary>
		public static string Engine_Displacement {
			get {
				return ResourceManager.GetString("Engine_Displacement", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die engineSpeed ähnelt.
		/// </summary>
		public static string Engine_EngineFullLoadCurve_EngineSpeed_Attr {
			get {
				return ResourceManager.GetString("Engine_EngineFullLoadCurve_EngineSpeed_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die FuelConsumptionMap ähnelt.
		/// </summary>
		public static string Engine_FuelConsumptionMap {
			get {
				return ResourceManager.GetString("Engine_FuelConsumptionMap", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die engineSpeed ähnelt.
		/// </summary>
		public static string Engine_FuelConsumptionMap_EngineSpeed_Attr {
			get {
				return ResourceManager.GetString("Engine_FuelConsumptionMap_EngineSpeed_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Entry ähnelt.
		/// </summary>
		public static string Engine_FuelConsumptionMap_Entry {
			get {
				return ResourceManager.GetString("Engine_FuelConsumptionMap_Entry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die fuelConsumption ähnelt.
		/// </summary>
		public static string Engine_FuelConsumptionMap_FuelConsumption_Attr {
			get {
				return ResourceManager.GetString("Engine_FuelConsumptionMap_FuelConsumption_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die torque ähnelt.
		/// </summary>
		public static string Engine_FuelConsumptionMap_Torque_Attr {
			get {
				return ResourceManager.GetString("Engine_FuelConsumptionMap_Torque_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die FullLoadAndDragCurve ähnelt.
		/// </summary>
		public static string Engine_FullLoadAndDragCurve {
			get {
				return ResourceManager.GetString("Engine_FullLoadAndDragCurve", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die dragTorque ähnelt.
		/// </summary>
		public static string Engine_FullLoadCurve_DragTorque_Attr {
			get {
				return ResourceManager.GetString("Engine_FullLoadCurve_DragTorque_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Entry ähnelt.
		/// </summary>
		public static string Engine_FullLoadCurve_Entry {
			get {
				return ResourceManager.GetString("Engine_FullLoadCurve_Entry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die maxTorque ähnelt.
		/// </summary>
		public static string Engine_FullLoadCurve_MaxTorque_Attr {
			get {
				return ResourceManager.GetString("Engine_FullLoadCurve_MaxTorque_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die IdlingSpeed ähnelt.
		/// </summary>
		public static string Engine_IdlingSpeed {
			get {
				return ResourceManager.GetString("Engine_IdlingSpeed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Inertia ähnelt.
		/// </summary>
		public static string Engine_Inertia {
			get {
				return ResourceManager.GetString("Engine_Inertia", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die WHTCEngineering ähnelt.
		/// </summary>
		public static string Engine_WHTCEngineering {
			get {
				return ResourceManager.GetString("Engine_WHTCEngineering", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die WHTCMotorway ähnelt.
		/// </summary>
		public static string Engine_WHTCMotorway {
			get {
				return ResourceManager.GetString("Engine_WHTCMotorway", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die WHTCRural ähnelt.
		/// </summary>
		public static string Engine_WHTCRural {
			get {
				return ResourceManager.GetString("Engine_WHTCRural", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die WHTCUrban ähnelt.
		/// </summary>
		public static string Engine_WHTCUrban {
			get {
				return ResourceManager.GetString("Engine_WHTCUrban", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Resource ähnelt.
		/// </summary>
		public static string ExternalResource {
			get {
				return ResourceManager.GetString("ExternalResource", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die component ähnelt.
		/// </summary>
		public static string ExtResource_Component_Attr {
			get {
				return ResourceManager.GetString("ExtResource_Component_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die file ähnelt.
		/// </summary>
		public static string ExtResource_File_Attr {
			get {
				return ResourceManager.GetString("ExtResource_File_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die type ähnelt.
		/// </summary>
		public static string ExtResource_Type_Attr {
			get {
				return ResourceManager.GetString("ExtResource_Type_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die csv ähnelt.
		/// </summary>
		public static string ExtResource_Type_Value_CSV {
			get {
				return ResourceManager.GetString("ExtResource_Type_Value_CSV", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die xml ähnelt.
		/// </summary>
		public static string ExtResource_Type_Value_XML {
			get {
				return ResourceManager.GetString("ExtResource_Type_Value_XML", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die engineTorque ähnelt.
		/// </summary>
		public static string Gear_ShiftPolygon_EngineTorque_Attr {
			get {
				return ResourceManager.GetString("Gear_ShiftPolygon_EngineTorque_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die downshiftSpeed ähnelt.
		/// </summary>
		public static string Gear_ShiftPolygonMapping_DownshiftSpeed_Attr {
			get {
				return ResourceManager.GetString("Gear_ShiftPolygonMapping_DownshiftSpeed_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die upshiftSpeed ähnelt.
		/// </summary>
		public static string Gear_ShiftPolygonMapping_UpshiftSpeed_Attr {
			get {
				return ResourceManager.GetString("Gear_ShiftPolygonMapping_UpshiftSpeed_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Efficiency ähnelt.
		/// </summary>
		public static string Gearbox_Gear_Efficiency {
			get {
				return ResourceManager.GetString("Gearbox_Gear_Efficiency", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die number ähnelt.
		/// </summary>
		public static string Gearbox_Gear_GearNumber_Attr {
			get {
				return ResourceManager.GetString("Gearbox_Gear_GearNumber_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Ratio ähnelt.
		/// </summary>
		public static string Gearbox_Gear_Ratio {
			get {
				return ResourceManager.GetString("Gearbox_Gear_Ratio", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die TorqueLossMap ähnelt.
		/// </summary>
		public static string Gearbox_Gear_TorqueLossMap {
			get {
				return ResourceManager.GetString("Gearbox_Gear_TorqueLossMap", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Entry ähnelt.
		/// </summary>
		public static string Gearbox_Gear_TorqueLossMap_Entry {
			get {
				return ResourceManager.GetString("Gearbox_Gear_TorqueLossMap_Entry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Gears ähnelt.
		/// </summary>
		public static string Gearbox_Gears {
			get {
				return ResourceManager.GetString("Gearbox_Gears", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Gear ähnelt.
		/// </summary>
		public static string Gearbox_Gears_Gear {
			get {
				return ResourceManager.GetString("Gearbox_Gears_Gear", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die ShiftPolygon ähnelt.
		/// </summary>
		public static string Gearbox_Gears_Gear_ShiftPolygon {
			get {
				return ResourceManager.GetString("Gearbox_Gears_Gear_ShiftPolygon", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Entry ähnelt.
		/// </summary>
		public static string Gearbox_Gears_Gear_ShiftPolygon_Entry {
			get {
				return ResourceManager.GetString("Gearbox_Gears_Gear_ShiftPolygon_Entry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die MaxTorque ähnelt.
		/// </summary>
		public static string Gearbox_Gears_MaxTorque {
			get {
				return ResourceManager.GetString("Gearbox_Gears_MaxTorque", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Inertia ähnelt.
		/// </summary>
		public static string Gearbox_Inertia {
			get {
				return ResourceManager.GetString("Gearbox_Inertia", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die TractionInterruption ähnelt.
		/// </summary>
		public static string Gearbox_TractionInterruption {
			get {
				return ResourceManager.GetString("Gearbox_TractionInterruption", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die TransmissionType ähnelt.
		/// </summary>
		public static string Gearbox_TransmissionType {
			get {
				return ResourceManager.GetString("Gearbox_TransmissionType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Entry ähnelt.
		/// </summary>
		public static string LookAheadCoasting_SpeedDependentDecisionFactor_Entry {
			get {
				return ResourceManager.GetString("LookAheadCoasting_SpeedDependentDecisionFactor_Entry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Entry ähnelt.
		/// </summary>
		public static string LookAheadCoasting_VelocityDropDecisionFactor_Entry {
			get {
				return ResourceManager.GetString("LookAheadCoasting_VelocityDropDecisionFactor_Entry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Cycle ähnelt.
		/// </summary>
		public static string Missions_Cycle {
			get {
				return ResourceManager.GetString("Missions_Cycle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die RetarderLossMap ähnelt.
		/// </summary>
		public static string Retarder_RetarderLossMap {
			get {
				return ResourceManager.GetString("Retarder_RetarderLossMap", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Entry ähnelt.
		/// </summary>
		public static string Retarder_RetarderLossMap_Entry {
			get {
				return ResourceManager.GetString("Retarder_RetarderLossMap_Entry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die retarderSpeed ähnelt.
		/// </summary>
		public static string Retarder_RetarderLossmap_RetarderSpeed_Attr {
			get {
				return ResourceManager.GetString("Retarder_RetarderLossmap_RetarderSpeed_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die torqueLoss ähnelt.
		/// </summary>
		public static string Retarder_RetarderLossmap_TorqueLoss_Attr {
			get {
				return ResourceManager.GetString("Retarder_RetarderLossmap_TorqueLoss_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Characteristics ähnelt.
		/// </summary>
		public static string TorqueConverter_Characteristics {
			get {
				return ResourceManager.GetString("TorqueConverter_Characteristics", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Entry ähnelt.
		/// </summary>
		public static string TorqueConverter_Characteristics_Entry {
			get {
				return ResourceManager.GetString("TorqueConverter_Characteristics_Entry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Inertia ähnelt.
		/// </summary>
		public static string TorqueConverter_Inertia {
			get {
				return ResourceManager.GetString("TorqueConverter_Inertia", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die ReferenceRPM ähnelt.
		/// </summary>
		public static string TorqueConverter_ReferenceRPM {
			get {
				return ResourceManager.GetString("TorqueConverter_ReferenceRPM", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die ShiftPolygon ähnelt.
		/// </summary>
		public static string TorqueConverter_ShiftPolygon {
			get {
				return ResourceManager.GetString("TorqueConverter_ShiftPolygon", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Entry ähnelt.
		/// </summary>
		public static string TorqueConverter_ShiftPolygon_Entry {
			get {
				return ResourceManager.GetString("TorqueConverter_ShiftPolygon_Entry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die speedRatio ähnelt.
		/// </summary>
		public static string TorqueConverterData_SpeedRatio_Attr {
			get {
				return ResourceManager.GetString("TorqueConverterData_SpeedRatio_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die torqueRatio ähnelt.
		/// </summary>
		public static string TorqueConverterData_TorqueRatio_Attr {
			get {
				return ResourceManager.GetString("TorqueConverterData_TorqueRatio_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die inputTorqueRef ähnelt.
		/// </summary>
		public static string TorqueConverterDataMapping_InputTorqueRef_Attr {
			get {
				return ResourceManager.GetString("TorqueConverterDataMapping_InputTorqueRef_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die inputSpeed ähnelt.
		/// </summary>
		public static string TransmissionLossmap_InputSpeed_Attr {
			get {
				return ResourceManager.GetString("TransmissionLossmap_InputSpeed_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die inputTorque ähnelt.
		/// </summary>
		public static string TransmissionLossmap_InputTorque_Attr {
			get {
				return ResourceManager.GetString("TransmissionLossmap_InputTorque_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die torqueLoss ähnelt.
		/// </summary>
		public static string TransmissionLossmap_TorqueLoss_Attr {
			get {
				return ResourceManager.GetString("TransmissionLossmap_TorqueLoss_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die VectoComponentEngineering ähnelt.
		/// </summary>
		public static string VectoComponentEngineering {
			get {
				return ResourceManager.GetString("VectoComponentEngineering", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die VectoInputDeclaration ähnelt.
		/// </summary>
		public static string VectoInputDeclaration {
			get {
				return ResourceManager.GetString("VectoInputDeclaration", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die VectoInputEngineering ähnelt.
		/// </summary>
		public static string VectoInputEngineering {
			get {
				return ResourceManager.GetString("VectoInputEngineering", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die EngineOnlyMode ähnelt.
		/// </summary>
		public static string VectoJob_EngineOnlyMode {
			get {
				return ResourceManager.GetString("VectoJob_EngineOnlyMode", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die MissionCycles ähnelt.
		/// </summary>
		public static string VectoJob_MissionCycles {
			get {
				return ResourceManager.GetString("VectoJob_MissionCycles", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die maxAcceleration ähnelt.
		/// </summary>
		public static string Vehicle_AccelerationCurve_MaxAcceleration_Attr {
			get {
				return ResourceManager.GetString("Vehicle_AccelerationCurve_MaxAcceleration_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die maxDeceleration ähnelt.
		/// </summary>
		public static string Vehicle_AccelerationCurve_MaxDeceleration_Attr {
			get {
				return ResourceManager.GetString("Vehicle_AccelerationCurve_MaxDeceleration_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die vehicleSpeed ähnelt.
		/// </summary>
		public static string Vehicle_AccelerationCurve_VehicleSpeed_Attr {
			get {
				return ResourceManager.GetString("Vehicle_AccelerationCurve_VehicleSpeed_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die AdvancedDriverAssist ähnelt.
		/// </summary>
		public static string Vehicle_AdvancedDriverAssist {
			get {
				return ResourceManager.GetString("Vehicle_AdvancedDriverAssist", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die EngineStartStop ähnelt.
		/// </summary>
		public static string Vehicle_AdvancedDriverAssist_EngineStartStop {
			get {
				return ResourceManager.GetString("Vehicle_AdvancedDriverAssist_EngineStartStop", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die ActivationDelay ähnelt.
		/// </summary>
		public static string Vehicle_AdvancedDriverAssist_EngineStartStop_ActivationDelay {
			get {
				return ResourceManager.GetString("Vehicle_AdvancedDriverAssist_EngineStartStop_ActivationDelay", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Enabled ähnelt.
		/// </summary>
		public static string Vehicle_AdvancedDriverAssist_EngineStartStop_Enabled {
			get {
				return ResourceManager.GetString("Vehicle_AdvancedDriverAssist_EngineStartStop_Enabled", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die MaxSpeed ähnelt.
		/// </summary>
		public static string Vehicle_AdvancedDriverAssist_EngineStartStop_MaxSpeed {
			get {
				return ResourceManager.GetString("Vehicle_AdvancedDriverAssist_EngineStartStop_MaxSpeed", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die MinOnTime ähnelt.
		/// </summary>
		public static string Vehicle_AdvancedDriverAssist_EngineStartStop_MinOnTime {
			get {
				return ResourceManager.GetString("Vehicle_AdvancedDriverAssist_EngineStartStop_MinOnTime", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die CdxA ähnelt.
		/// </summary>
		public static string Vehicle_AirDragArea {
			get {
				return ResourceManager.GetString("Vehicle_AirDragArea", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die AngledriveType ähnelt.
		/// </summary>
		public static string Vehicle_AngledriveType {
			get {
				return ResourceManager.GetString("Vehicle_AngledriveType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die AxleConfiguration ähnelt.
		/// </summary>
		public static string Vehicle_AxleConfiguration {
			get {
				return ResourceManager.GetString("Vehicle_AxleConfiguration", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Components ähnelt.
		/// </summary>
		public static string Vehicle_Components {
			get {
				return ResourceManager.GetString("Vehicle_Components", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die CrossWindCorrectionData ähnelt.
		/// </summary>
		public static string Vehicle_CrosswindCorrectionData {
			get {
				return ResourceManager.GetString("Vehicle_CrosswindCorrectionData", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Entry ähnelt.
		/// </summary>
		public static string Vehicle_CrosswindCorrectionData_Entry {
			get {
				return ResourceManager.GetString("Vehicle_CrosswindCorrectionData_Entry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die beta ähnelt.
		/// </summary>
		public static string Vehicle_CrosswindCorrectionMap_Beta {
			get {
				return ResourceManager.GetString("Vehicle_CrosswindCorrectionMap_Beta", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die CdScalingFactor ähnelt.
		/// </summary>
		public static string Vehicle_CrosswindCorrectionMap_CdScalingFactor {
			get {
				return ResourceManager.GetString("Vehicle_CrosswindCorrectionMap_CdScalingFactor", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die deltaCdxA ähnelt.
		/// </summary>
		public static string Vehicle_CrosswindCorrectionMap_DeltaCdxA {
			get {
				return ResourceManager.GetString("Vehicle_CrosswindCorrectionMap_DeltaCdxA", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die vehicleSpeed ähnelt.
		/// </summary>
		public static string Vehicle_CrosswindCorrectionMap_VehicleSpeed_Attr {
			get {
				return ResourceManager.GetString("Vehicle_CrosswindCorrectionMap_VehicleSpeed_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die CrossWindCorrectionMode ähnelt.
		/// </summary>
		public static string Vehicle_CrossWindCorrectionMode {
			get {
				return ResourceManager.GetString("Vehicle_CrossWindCorrectionMode", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die CurbWeightChassis ähnelt.
		/// </summary>
		public static string Vehicle_CurbWeightChassis {
			get {
				return ResourceManager.GetString("Vehicle_CurbWeightChassis", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die CurbWeightExtra ähnelt.
		/// </summary>
		public static string Vehicle_CurbWeightExtra {
			get {
				return ResourceManager.GetString("Vehicle_CurbWeightExtra", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die GrossVehicleMass ähnelt.
		/// </summary>
		public static string Vehicle_GrossVehicleMass {
			get {
				return ResourceManager.GetString("Vehicle_GrossVehicleMass", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Loading ähnelt.
		/// </summary>
		public static string Vehicle_Loading {
			get {
				return ResourceManager.GetString("Vehicle_Loading", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die PTOCycle ähnelt.
		/// </summary>
		public static string Vehicle_PTOCycle {
			get {
				return ResourceManager.GetString("Vehicle_PTOCycle", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die engineSpeed ähnelt.
		/// </summary>
		public static string Vehicle_PTOCycle_EngineSpeed_Attr {
			get {
				return ResourceManager.GetString("Vehicle_PTOCycle_EngineSpeed_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Entry ähnelt.
		/// </summary>
		public static string Vehicle_PTOCycle_Entry {
			get {
				return ResourceManager.GetString("Vehicle_PTOCycle_Entry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die time ähnelt.
		/// </summary>
		public static string Vehicle_PTOCycle_Time_Attr {
			get {
				return ResourceManager.GetString("Vehicle_PTOCycle_Time_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die torque ähnelt.
		/// </summary>
		public static string Vehicle_PTOCycle_Torque_Attr {
			get {
				return ResourceManager.GetString("Vehicle_PTOCycle_Torque_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die PTOIdleLossMap ähnelt.
		/// </summary>
		public static string Vehicle_PTOIdleLossMap {
			get {
				return ResourceManager.GetString("Vehicle_PTOIdleLossMap", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die engineSpeed ähnelt.
		/// </summary>
		public static string Vehicle_PTOIdleLossMap_EngineSpeed_Attr {
			get {
				return ResourceManager.GetString("Vehicle_PTOIdleLossMap_EngineSpeed_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die Entry ähnelt.
		/// </summary>
		public static string Vehicle_PTOIdleLossMap_Entry {
			get {
				return ResourceManager.GetString("Vehicle_PTOIdleLossMap_Entry", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die ptoTorqueLoss ähnelt.
		/// </summary>
		public static string Vehicle_PTOIdleLossMap_TorqueLoss_Attr {
			get {
				return ResourceManager.GetString("Vehicle_PTOIdleLossMap_TorqueLoss_Attr", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die PTOType ähnelt.
		/// </summary>
		public static string Vehicle_PTOType {
			get {
				return ResourceManager.GetString("Vehicle_PTOType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die RetarderRatio ähnelt.
		/// </summary>
		public static string Vehicle_RetarderRatio {
			get {
				return ResourceManager.GetString("Vehicle_RetarderRatio", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die RetarderType ähnelt.
		/// </summary>
		public static string Vehicle_RetarderType {
			get {
				return ResourceManager.GetString("Vehicle_RetarderType", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die SteeredAxles ähnelt.
		/// </summary>
		public static string Vehicle_SteeredAxles {
			get {
				return ResourceManager.GetString("Vehicle_SteeredAxles", resourceCulture);
			}
		}
		
		/// <summary>
		///   Sucht eine lokalisierte Zeichenfolge, die VehicleCategory ähnelt.
		/// </summary>
		public static string Vehicle_VehicleCategory {
			get {
				return ResourceManager.GetString("Vehicle_VehicleCategory", resourceCulture);
			}
		}
	}
}
