<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Version Information (only needed if it differs from Global VECTO Version)-->
    <MainProductVersion>1.2.9</MainProductVersion>
    <VersionPrefix>$(MainProductVersion).$([System.DateTime]::UtcNow.Subtract($([System.DateTime]::new(2015,1,1))).Days)</VersionPrefix>

    <RootNamespace>TUGraz.VectoHashing</RootNamespace>
    <AssemblyName>VectoHashing</AssemblyName>
    <TargetFrameworks>net45;net48;net6.0</TargetFrameworks>
    <DefineConstants />
    <Configurations>Debug;Release;MockupRelease</Configurations>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net45'">
    <Reference Include="System.Security" />
  </ItemGroup>


  <ItemGroup Condition="'$(TargetFramework)' == 'net48'">
    <PackageReference Include="System.Security.Cryptography.Xml">
      <Version>6.0.0</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
    <PackageReference Include="System.Security.Cryptography.Xml">
      <Version>6.0.0</Version>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VectoCommon\VectoCommon.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\XSLT\SortInputData.xslt" />
  </ItemGroup>
</Project>
