//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TUGraz.VectoCore.OutputData.XML.GroupWriter.Declaration {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class GroupNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GroupNames() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TUGraz.VectoCore.OutputData.XML.GroupWriter.Declaration.GroupNames", typeof(GroupNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ADAS_Conventional_Type ähnelt.
        /// </summary>
        public static string ADAS_Conventional_Type {
            get {
                return ResourceManager.GetString("ADAS_Conventional_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ADAS_HEV_Type ähnelt.
        /// </summary>
        public static string ADAS_HEV_Type {
            get {
                return ResourceManager.GetString("ADAS_HEV_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ADAS_IEPC_Type ähnelt.
        /// </summary>
        public static string ADAS_IEPC_Type {
            get {
                return ResourceManager.GetString("ADAS_IEPC_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die ADAS_PEV_Type ähnelt.
        /// </summary>
        public static string ADAS_PEV_Type {
            get {
                return ResourceManager.GetString("ADAS_PEV_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BusAuxElectricSystemLightsGroup ähnelt.
        /// </summary>
        public static string BusAuxElectricSystemLightsGroup {
            get {
                return ResourceManager.GetString("BusAuxElectricSystemLightsGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BusAuxElectricSystemSupplySequenceGroup ähnelt.
        /// </summary>
        public static string BusAuxElectricSystemSupplySequenceGroup {
            get {
                return ResourceManager.GetString("BusAuxElectricSystemSupplySequenceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BusAuxHVACConventionalSequenceGroup ähnelt.
        /// </summary>
        public static string BusAuxHVACConventionalSequenceGroup {
            get {
                return ResourceManager.GetString("BusAuxHVACConventionalSequenceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BusAuxHVACHeatPumpSequenceGroup ähnelt.
        /// </summary>
        public static string BusAuxHVACHeatPumpSequenceGroup {
            get {
                return ResourceManager.GetString("BusAuxHVACHeatPumpSequenceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die BusAuxHVACxEVSequenceGroup ähnelt.
        /// </summary>
        public static string BusAuxHVACxEVSequenceGroup {
            get {
                return ResourceManager.GetString("BusAuxHVACxEVSequenceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle_CompletedBus_DimensionsSequenceGroup ähnelt.
        /// </summary>
        public static string Vehicle_CompletedBus_DimensionsSequenceGroup {
            get {
                return ResourceManager.GetString("Vehicle_CompletedBus_DimensionsSequenceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle_CompletedBus_GeneralParametersSequenceGroup ähnelt.
        /// </summary>
        public static string Vehicle_CompletedBus_GeneralParametersSequenceGroup {
            get {
                return ResourceManager.GetString("Vehicle_CompletedBus_GeneralParametersSequenceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle_CompletedBus_PassengerCountSequenceGroup ähnelt.
        /// </summary>
        public static string Vehicle_CompletedBus_PassengerCountSequenceGroup {
            get {
                return ResourceManager.GetString("Vehicle_CompletedBus_PassengerCountSequenceGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vehicle_CompletedBusParametersSequenceGroup ähnelt.
        /// </summary>
        public static string Vehicle_CompletedBusParametersSequenceGroup {
            get {
                return ResourceManager.GetString("Vehicle_CompletedBusParametersSequenceGroup", resourceCulture);
            }
        }
    }
}
