/*
* This file is part of VECTO.
*
* Copyright © 2012-2017 European Union
*
* Developed by Graz University of Technology,
*              Institute of Internal Combustion Engines and Thermodynamics,
*              Institute of Technical Informatics
*
* VECTO is licensed under the EUPL, Version 1.1 or - as soon they will be approved
* by the European Commission - subsequent versions of the EUPL (the "Licence");
* You may not use VECTO except in compliance with the Licence.
* You may obtain a copy of the Licence at:
*
* https://joinup.ec.europa.eu/community/eupl/og_page/eupl
*
* Unless required by applicable law or agreed to in writing, VECTO
* distributed under the Licence is distributed on an "AS IS" basis,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the Licence for the specific language governing permissions and
* limitations under the Licence.
*
* Authors:
*   Stefan Hausberger, hausberger@ivt.tugraz.at, IVT, Graz University of Technology
*   Christian Kreiner, christian.kreiner@tugraz.at, ITI, Graz University of Technology
*   Michael Krisper, michael.krisper@tugraz.at, ITI, Graz University of Technology
*   Raphael Luz, luz@ivt.tugraz.at, IVT, Graz University of Technology
*   Markus Quaritsch, markus.quaritsch@tugraz.at, IVT, Graz University of Technology
*   Martin Rexeis, rexeis@ivt.tugraz.at, IVT, Graz University of Technology
*/

namespace TUGraz.VectoCommon.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class XMLNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XMLNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TUGraz.VectoCommon.Resources.XMLNames", typeof(XMLNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeclaredCdxA.
        /// </summary>
        public static string AirDrag_DeclaredCdxA {
            get {
                return ResourceManager.GetString("AirDrag_DeclaredCdxA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        public static string AngleDrive_Efficiency {
            get {
                return ResourceManager.GetString("AngleDrive_Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Angledrive_LossMap_Entry {
            get {
                return ResourceManager.GetString("Angledrive_LossMap_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        public static string AngleDrive_Ratio {
            get {
                return ResourceManager.GetString("AngleDrive_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TorqueLossMap.
        /// </summary>
        public static string AngleDrive_TorqueLossMap {
            get {
                return ResourceManager.GetString("AngleDrive_TorqueLossMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to auxiliarySpeed.
        /// </summary>
        public static string Aux_AuxMap_AuxiliarySpeed_Attr {
            get {
                return ResourceManager.GetString("Aux_AuxMap_AuxiliarySpeed_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mechanicalPower.
        /// </summary>
        public static string Aux_AuxMap_MechanicalPower_Attr {
            get {
                return ResourceManager.GetString("Aux_AuxMap_MechanicalPower_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliary.
        /// </summary>
        public static string Auxiliaries_Auxiliary {
            get {
                return ResourceManager.GetString("Auxiliaries_Auxiliary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuxMap.
        /// </summary>
        public static string Auxiliaries_Auxiliary_AuxMap {
            get {
                return ResourceManager.GetString("Auxiliaries_Auxiliary_AuxMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Auxiliaries_Auxiliary_AuxMap_Entry {
            get {
                return ResourceManager.GetString("Auxiliaries_Auxiliary_AuxMap_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConstantAuxLoad.
        /// </summary>
        public static string Auxiliaries_Auxiliary_ConstantAuxLoad {
            get {
                return ResourceManager.GetString("Auxiliaries_Auxiliary_ConstantAuxLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EfficiencyAuxSupply.
        /// </summary>
        public static string Auxiliaries_Auxiliary_EfficiencyAuxSupply {
            get {
                return ResourceManager.GetString("Auxiliaries_Auxiliary_EfficiencyAuxSupply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EfficiencyToEngine.
        /// </summary>
        public static string Auxiliaries_Auxiliary_EfficiencyToEngine {
            get {
                return ResourceManager.GetString("Auxiliaries_Auxiliary_EfficiencyToEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string Auxiliaries_Auxiliary_ID_Attr {
            get {
                return ResourceManager.GetString("Auxiliaries_Auxiliary_ID_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technology.
        /// </summary>
        public static string Auxiliaries_Auxiliary_Technology {
            get {
                return ResourceManager.GetString("Auxiliaries_Auxiliary_Technology", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransmissionRatioToEngine.
        /// </summary>
        public static string Auxiliaries_Auxiliary_TransmissionRatioToEngine {
            get {
                return ResourceManager.GetString("Auxiliaries_Auxiliary_TransmissionRatioToEngine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to supplyPower.
        /// </summary>
        public static string Auxr_AuxMapMapping_SupplyPower_Attr {
            get {
                return ResourceManager.GetString("Auxr_AuxMapMapping_SupplyPower_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        public static string Axlegear_Efficiency {
            get {
                return ResourceManager.GetString("Axlegear_Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineType.
        /// </summary>
        public static string Axlegear_LineType {
            get {
                return ResourceManager.GetString("Axlegear_LineType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        public static string Axlegear_Ratio {
            get {
                return ResourceManager.GetString("Axlegear_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TorqueLossMap.
        /// </summary>
        public static string Axlegear_TorqueLossMap {
            get {
                return ResourceManager.GetString("Axlegear_TorqueLossMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Axlegear_TorqueLossMap_Entry {
            get {
                return ResourceManager.GetString("Axlegear_TorqueLossMap_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axles.
        /// </summary>
        public static string AxleWheels_Axles {
            get {
                return ResourceManager.GetString("AxleWheels_Axles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axle.
        /// </summary>
        public static string AxleWheels_Axles_Axle {
            get {
                return ResourceManager.GetString("AxleWheels_Axles_Axle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to axleNumber.
        /// </summary>
        public static string AxleWheels_Axles_Axle_AxleNumber_Attr {
            get {
                return ResourceManager.GetString("AxleWheels_Axles_Axle_AxleNumber_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxleType.
        /// </summary>
        public static string AxleWheels_Axles_Axle_AxleType {
            get {
                return ResourceManager.GetString("AxleWheels_Axles_Axle_AxleType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxleType.
        /// </summary>
        public static string AxleWheels_Axles_Axle_AxleType_Attr {
            get {
                return ResourceManager.GetString("AxleWheels_Axles_Axle_AxleType_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension.
        /// </summary>
        public static string AxleWheels_Axles_Axle_Dimension {
            get {
                return ResourceManager.GetString("AxleWheels_Axles_Axle_Dimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DynamicTyreRadius.
        /// </summary>
        public static string AxleWheels_Axles_Axle_DynamicTyreRadius {
            get {
                return ResourceManager.GetString("AxleWheels_Axles_Axle_DynamicTyreRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FzISO.
        /// </summary>
        public static string AxleWheels_Axles_Axle_FzISO {
            get {
                return ResourceManager.GetString("AxleWheels_Axles_Axle_FzISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inertia.
        /// </summary>
        public static string AxleWheels_Axles_Axle_Inertia {
            get {
                return ResourceManager.GetString("AxleWheels_Axles_Axle_Inertia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RRCDeclared.
        /// </summary>
        public static string AxleWheels_Axles_Axle_RRCDeclared {
            get {
                return ResourceManager.GetString("AxleWheels_Axles_Axle_RRCDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RRCISO.
        /// </summary>
        public static string AxleWheels_Axles_Axle_RRCISO {
            get {
                return ResourceManager.GetString("AxleWheels_Axles_Axle_RRCISO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steered.
        /// </summary>
        public static string AxleWheels_Axles_Axle_Steered {
            get {
                return ResourceManager.GetString("AxleWheels_Axles_Axle_Steered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwinTyres.
        /// </summary>
        public static string AxleWheels_Axles_Axle_TwinTyres {
            get {
                return ResourceManager.GetString("AxleWheels_Axles_Axle_TwinTyres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TwinTyres.
        /// </summary>
        public static string AxleWheels_Axles_Axle_TwinTyres_Attr {
            get {
                return ResourceManager.GetString("AxleWheels_Axles_Axle_TwinTyres_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tyre.
        /// </summary>
        public static string AxleWheels_Axles_Axle_Tyre {
            get {
                return ResourceManager.GetString("AxleWheels_Axles_Axle_Tyre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WeightShare.
        /// </summary>
        public static string AxleWheels_Axles_Axle_WeightShare {
            get {
                return ResourceManager.GetString("AxleWheels_Axles_Axle_WeightShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AirDrag.
        /// </summary>
        public static string Component_AirDrag {
            get {
                return ResourceManager.GetString("Component_AirDrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Angledrive.
        /// </summary>
        public static string Component_Angledrive {
            get {
                return ResourceManager.GetString("Component_Angledrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AppVersion.
        /// </summary>
        public static string Component_AppVersion {
            get {
                return ResourceManager.GetString("Component_AppVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auxiliaries.
        /// </summary>
        public static string Component_Auxiliaries {
            get {
                return ResourceManager.GetString("Component_Auxiliaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Axlegear.
        /// </summary>
        public static string Component_Axlegear {
            get {
                return ResourceManager.GetString("Component_Axlegear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxleWheels.
        /// </summary>
        public static string Component_AxleWheels {
            get {
                return ResourceManager.GetString("Component_AxleWheels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CertificationMethod.
        /// </summary>
        public static string Component_CertificationMethod {
            get {
                return ResourceManager.GetString("Component_CertificationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CertificationNumber.
        /// </summary>
        public static string Component_CertificationNumber {
            get {
                return ResourceManager.GetString("Component_CertificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creator.
        /// </summary>
        public static string Component_Creator {
            get {
                return ResourceManager.GetString("Component_Creator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Component_Date {
            get {
                return ResourceManager.GetString("Component_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverModel.
        /// </summary>
        public static string Component_DriverModel {
            get {
                return ResourceManager.GetString("Component_DriverModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine.
        /// </summary>
        public static string Component_Engine {
            get {
                return ResourceManager.GetString("Component_Engine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gearbox.
        /// </summary>
        public static string Component_Gearbox {
            get {
                return ResourceManager.GetString("Component_Gearbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MainCertificationMethod.
        /// </summary>
        public static string Component_Gearbox_CertificationMethod {
            get {
                return ResourceManager.GetString("Component_Gearbox_CertificationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to id.
        /// </summary>
        public static string Component_ID_Attr {
            get {
                return ResourceManager.GetString("Component_ID_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manufacturer.
        /// </summary>
        public static string Component_Manufacturer {
            get {
                return ResourceManager.GetString("Component_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ManufacturerAddress.
        /// </summary>
        public static string Component_ManufacturerAddress {
            get {
                return ResourceManager.GetString("Component_ManufacturerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Component_Model {
            get {
                return ResourceManager.GetString("Component_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retarder.
        /// </summary>
        public static string Component_Retarder {
            get {
                return ResourceManager.GetString("Component_Retarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TechnicalReportId.
        /// </summary>
        public static string Component_TechnicalReportId {
            get {
                return ResourceManager.GetString("Component_TechnicalReportId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TorqueConverter.
        /// </summary>
        public static string Component_TorqueConverter {
            get {
                return ResourceManager.GetString("Component_TorqueConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vehicle.
        /// </summary>
        public static string Component_Vehicle {
            get {
                return ResourceManager.GetString("Component_Vehicle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string ComponentDataWrapper {
            get {
                return ResourceManager.GetString("ComponentDataWrapper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signature.
        /// </summary>
        public static string DI_Signature {
            get {
                return ResourceManager.GetString("DI_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algorithm.
        /// </summary>
        public static string DI_Signature_Algorithm_Attr {
            get {
                return ResourceManager.GetString("DI_Signature_Algorithm_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        public static string DI_Signature_Reference {
            get {
                return ResourceManager.GetString("DI_Signature_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigestMethod.
        /// </summary>
        public static string DI_Signature_Reference_DigestMethod {
            get {
                return ResourceManager.GetString("DI_Signature_Reference_DigestMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DigestValue.
        /// </summary>
        public static string DI_Signature_Reference_DigestValue {
            get {
                return ResourceManager.GetString("DI_Signature_Reference_DigestValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transforms.
        /// </summary>
        public static string DI_Signature_Reference_Transforms {
            get {
                return ResourceManager.GetString("DI_Signature_Reference_Transforms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transform.
        /// </summary>
        public static string DI_Signature_Reference_Transforms_Transform {
            get {
                return ResourceManager.GetString("DI_Signature_Reference_Transforms_Transform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URI.
        /// </summary>
        public static string DI_Signature_Reference_URI_Attr {
            get {
                return ResourceManager.GetString("DI_Signature_Reference_URI_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decisionFactorVel.
        /// </summary>
        public static string Driver_CoastingDFTargetSpeedLookupMapping_DecisionFactor_Attr {
            get {
                return ResourceManager.GetString("Driver_CoastingDFTargetSpeedLookupMapping_DecisionFactor_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to targetVelocity.
        /// </summary>
        public static string Driver_CoastingDFTargetSpeedLookupMapping_TargetVelocity_Attr {
            get {
                return ResourceManager.GetString("Driver_CoastingDFTargetSpeedLookupMapping_TargetVelocity_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to decisionFactorDrop.
        /// </summary>
        public static string Driver_CoastingDFVelocityDropLookupMapping_DecisionFactorDrop_Attr {
            get {
                return ResourceManager.GetString("Driver_CoastingDFVelocityDropLookupMapping_DecisionFactorDrop_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to velocityDrop.
        /// </summary>
        public static string Driver_CoastingDFVelocityDropLookupMapping_VelocityDrop_Attr {
            get {
                return ResourceManager.GetString("Driver_CoastingDFVelocityDropLookupMapping_VelocityDrop_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DriverAccelerationCurve.
        /// </summary>
        public static string DriverModel_DriverAccelerationCurve {
            get {
                return ResourceManager.GetString("DriverModel_DriverAccelerationCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string DriverModel_DriverAccelerationCurve_Entry {
            get {
                return ResourceManager.GetString("DriverModel_DriverAccelerationCurve_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LookAheadCoasting.
        /// </summary>
        public static string DriverModel_LookAheadCoasting {
            get {
                return ResourceManager.GetString("DriverModel_LookAheadCoasting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecisionFactorOffset.
        /// </summary>
        public static string DriverModel_LookAheadCoasting_DecisionFactorOffset {
            get {
                return ResourceManager.GetString("DriverModel_LookAheadCoasting_DecisionFactorOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DecisionFactorScaling.
        /// </summary>
        public static string DriverModel_LookAheadCoasting_DecisionFactorScaling {
            get {
                return ResourceManager.GetString("DriverModel_LookAheadCoasting_DecisionFactorScaling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string DriverModel_LookAheadCoasting_Enabled {
            get {
                return ResourceManager.GetString("DriverModel_LookAheadCoasting_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinSpeed.
        /// </summary>
        public static string DriverModel_LookAheadCoasting_MinSpeed {
            get {
                return ResourceManager.GetString("DriverModel_LookAheadCoasting_MinSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PreviewDistanceFactor.
        /// </summary>
        public static string DriverModel_LookAheadCoasting_PreviewDistanceFactor {
            get {
                return ResourceManager.GetString("DriverModel_LookAheadCoasting_PreviewDistanceFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SpeedDependentDecisionFactor.
        /// </summary>
        public static string DriverModel_LookAheadCoasting_SpeedDependentDecisionFactor {
            get {
                return ResourceManager.GetString("DriverModel_LookAheadCoasting_SpeedDependentDecisionFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VelocityDropDecisionFactor.
        /// </summary>
        public static string DriverModel_LookAheadCoasting_VelocityDropDecisionFactor {
            get {
                return ResourceManager.GetString("DriverModel_LookAheadCoasting_VelocityDropDecisionFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overspeed.
        /// </summary>
        public static string DriverModel_Overspeed {
            get {
                return ResourceManager.GetString("DriverModel_Overspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowedOverspeed.
        /// </summary>
        public static string DriverModel_Overspeed_AllowedOverspeed {
            get {
                return ResourceManager.GetString("DriverModel_Overspeed_AllowedOverspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllowedUnderspeed.
        /// </summary>
        public static string DriverModel_Overspeed_AllowedUnderspeed {
            get {
                return ResourceManager.GetString("DriverModel_Overspeed_AllowedUnderspeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinSpeed.
        /// </summary>
        public static string DriverModel_Overspeed_MinSpeed {
            get {
                return ResourceManager.GetString("DriverModel_Overspeed_MinSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string DriverModel_Overspeed_Mode {
            get {
                return ResourceManager.GetString("DriverModel_Overspeed_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShiftStrategyParameters.
        /// </summary>
        public static string DriverModel_ShiftStrategyParameters {
            get {
                return ResourceManager.GetString("DriverModel_ShiftStrategyParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DownshiftAfterUpshiftDelay.
        /// </summary>
        public static string DriverModel_ShiftStrategyParameters_DownshiftAfterUpshiftDelay {
            get {
                return ResourceManager.GetString("DriverModel_ShiftStrategyParameters_DownshiftAfterUpshiftDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartAcceleration.
        /// </summary>
        public static string DriverModel_ShiftStrategyParameters_StartAcceleration {
            get {
                return ResourceManager.GetString("DriverModel_ShiftStrategyParameters_StartAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartSpeed.
        /// </summary>
        public static string DriverModel_ShiftStrategyParameters_StartSpeed {
            get {
                return ResourceManager.GetString("DriverModel_ShiftStrategyParameters_StartSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartTorqueReserve.
        /// </summary>
        public static string DriverModel_ShiftStrategyParameters_StartTorqueReserve {
            get {
                return ResourceManager.GetString("DriverModel_ShiftStrategyParameters_StartTorqueReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TimeBetweenGearshift.
        /// </summary>
        public static string DriverModel_ShiftStrategyParameters_TimeBetweenGearshift {
            get {
                return ResourceManager.GetString("DriverModel_ShiftStrategyParameters_TimeBetweenGearshift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TorqueReserve.
        /// </summary>
        public static string DriverModel_ShiftStrategyParameters_TorqueReserve {
            get {
                return ResourceManager.GetString("DriverModel_ShiftStrategyParameters_TorqueReserve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpshiftAfterDownshiftDelay.
        /// </summary>
        public static string DriverModel_ShiftStrategyParameters_UpshiftAfterDownshiftDelay {
            get {
                return ResourceManager.GetString("DriverModel_ShiftStrategyParameters_UpshiftAfterDownshiftDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpshiftMinAcceleration.
        /// </summary>
        public static string DriverModel_ShiftStrategyParameters_UpshiftMinAcceleration {
            get {
                return ResourceManager.GetString("DriverModel_ShiftStrategyParameters_UpshiftMinAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BFColdHot.
        /// </summary>
        public static string Engine_ColdHotBalancingFactor {
            get {
                return ResourceManager.GetString("Engine_ColdHotBalancingFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFNCV.
        /// </summary>
        public static string Engine_CorrecionFactor_NCV {
            get {
                return ResourceManager.GetString("Engine_CorrecionFactor_NCV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CFRegPer.
        /// </summary>
        public static string Engine_CorrectionFactor_RegPer {
            get {
                return ResourceManager.GetString("Engine_CorrectionFactor_RegPer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displacement.
        /// </summary>
        public static string Engine_Displacement {
            get {
                return ResourceManager.GetString("Engine_Displacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to engineSpeed.
        /// </summary>
        public static string Engine_EngineFullLoadCurve_EngineSpeed_Attr {
            get {
                return ResourceManager.GetString("Engine_EngineFullLoadCurve_EngineSpeed_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FuelConsumptionMap.
        /// </summary>
        public static string Engine_FuelConsumptionMap {
            get {
                return ResourceManager.GetString("Engine_FuelConsumptionMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to engineSpeed.
        /// </summary>
        public static string Engine_FuelConsumptionMap_EngineSpeed_Attr {
            get {
                return ResourceManager.GetString("Engine_FuelConsumptionMap_EngineSpeed_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Engine_FuelConsumptionMap_Entry {
            get {
                return ResourceManager.GetString("Engine_FuelConsumptionMap_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fuelConsumption.
        /// </summary>
        public static string Engine_FuelConsumptionMap_FuelConsumption_Attr {
            get {
                return ResourceManager.GetString("Engine_FuelConsumptionMap_FuelConsumption_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to torque.
        /// </summary>
        public static string Engine_FuelConsumptionMap_Torque_Attr {
            get {
                return ResourceManager.GetString("Engine_FuelConsumptionMap_Torque_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FuelType.
        /// </summary>
        public static string Engine_FuelType {
            get {
                return ResourceManager.GetString("Engine_FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullLoadAndDragCurve.
        /// </summary>
        public static string Engine_FullLoadAndDragCurve {
            get {
                return ResourceManager.GetString("Engine_FullLoadAndDragCurve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dragTorque.
        /// </summary>
        public static string Engine_FullLoadCurve_DragTorque_Attr {
            get {
                return ResourceManager.GetString("Engine_FullLoadCurve_DragTorque_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Engine_FullLoadCurve_Entry {
            get {
                return ResourceManager.GetString("Engine_FullLoadCurve_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxTorque.
        /// </summary>
        public static string Engine_FullLoadCurve_MaxTorque_Attr {
            get {
                return ResourceManager.GetString("Engine_FullLoadCurve_MaxTorque_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdlingSpeed.
        /// </summary>
        public static string Engine_IdlingSpeed {
            get {
                return ResourceManager.GetString("Engine_IdlingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inertia.
        /// </summary>
        public static string Engine_Inertia {
            get {
                return ResourceManager.GetString("Engine_Inertia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxEngineTorque.
        /// </summary>
        public static string Engine_MaxTorque {
            get {
                return ResourceManager.GetString("Engine_MaxTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RatedPower.
        /// </summary>
        public static string Engine_RatedPower {
            get {
                return ResourceManager.GetString("Engine_RatedPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RatedSpeed.
        /// </summary>
        public static string Engine_RatedSpeed {
            get {
                return ResourceManager.GetString("Engine_RatedSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHTCEngineering.
        /// </summary>
        public static string Engine_WHTCEngineering {
            get {
                return ResourceManager.GetString("Engine_WHTCEngineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHTCMotorway.
        /// </summary>
        public static string Engine_WHTCMotorway {
            get {
                return ResourceManager.GetString("Engine_WHTCMotorway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHTCRural.
        /// </summary>
        public static string Engine_WHTCRural {
            get {
                return ResourceManager.GetString("Engine_WHTCRural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WHTCUrban.
        /// </summary>
        public static string Engine_WHTCUrban {
            get {
                return ResourceManager.GetString("Engine_WHTCUrban", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resource.
        /// </summary>
        public static string ExternalResource {
            get {
                return ResourceManager.GetString("ExternalResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to component.
        /// </summary>
        public static string ExtResource_Component_Attr {
            get {
                return ResourceManager.GetString("ExtResource_Component_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        public static string ExtResource_File_Attr {
            get {
                return ResourceManager.GetString("ExtResource_File_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to type.
        /// </summary>
        public static string ExtResource_Type_Attr {
            get {
                return ResourceManager.GetString("ExtResource_Type_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csv.
        /// </summary>
        public static string ExtResource_Type_Value_CSV {
            get {
                return ResourceManager.GetString("ExtResource_Type_Value_CSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml.
        /// </summary>
        public static string ExtResource_Type_Value_XML {
            get {
                return ResourceManager.GetString("ExtResource_Type_Value_XML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to engineTorque.
        /// </summary>
        public static string Gear_ShiftPolygon_EngineTorque_Attr {
            get {
                return ResourceManager.GetString("Gear_ShiftPolygon_EngineTorque_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to downshiftSpeed.
        /// </summary>
        public static string Gear_ShiftPolygonMapping_DownshiftSpeed_Attr {
            get {
                return ResourceManager.GetString("Gear_ShiftPolygonMapping_DownshiftSpeed_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to upshiftSpeed.
        /// </summary>
        public static string Gear_ShiftPolygonMapping_UpshiftSpeed_Attr {
            get {
                return ResourceManager.GetString("Gear_ShiftPolygonMapping_UpshiftSpeed_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efficiency.
        /// </summary>
        public static string Gearbox_Gear_Efficiency {
            get {
                return ResourceManager.GetString("Gearbox_Gear_Efficiency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to number.
        /// </summary>
        public static string Gearbox_Gear_GearNumber_Attr {
            get {
                return ResourceManager.GetString("Gearbox_Gear_GearNumber_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxSpeed.
        /// </summary>
        public static string Gearbox_Gear_MaxSpeed {
            get {
                return ResourceManager.GetString("Gearbox_Gear_MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ratio.
        /// </summary>
        public static string Gearbox_Gear_Ratio {
            get {
                return ResourceManager.GetString("Gearbox_Gear_Ratio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TorqueLossMap.
        /// </summary>
        public static string Gearbox_Gear_TorqueLossMap {
            get {
                return ResourceManager.GetString("Gearbox_Gear_TorqueLossMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Gearbox_Gear_TorqueLossMap_Entry {
            get {
                return ResourceManager.GetString("Gearbox_Gear_TorqueLossMap_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gears.
        /// </summary>
        public static string Gearbox_Gears {
            get {
                return ResourceManager.GetString("Gearbox_Gears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gear.
        /// </summary>
        public static string Gearbox_Gears_Gear {
            get {
                return ResourceManager.GetString("Gearbox_Gears_Gear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShiftPolygon.
        /// </summary>
        public static string Gearbox_Gears_Gear_ShiftPolygon {
            get {
                return ResourceManager.GetString("Gearbox_Gears_Gear_ShiftPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Gearbox_Gears_Gear_ShiftPolygon_Entry {
            get {
                return ResourceManager.GetString("Gearbox_Gears_Gear_ShiftPolygon_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxTorque.
        /// </summary>
        public static string Gearbox_Gears_MaxTorque {
            get {
                return ResourceManager.GetString("Gearbox_Gears_MaxTorque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inertia.
        /// </summary>
        public static string Gearbox_Inertia {
            get {
                return ResourceManager.GetString("Gearbox_Inertia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TractionInterruption.
        /// </summary>
        public static string Gearbox_TractionInterruption {
            get {
                return ResourceManager.GetString("Gearbox_TractionInterruption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransmissionType.
        /// </summary>
        public static string Gearbox_TransmissionType {
            get {
                return ResourceManager.GetString("Gearbox_TransmissionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string LookAheadCoasting_SpeedDependentDecisionFactor_Entry {
            get {
                return ResourceManager.GetString("LookAheadCoasting_SpeedDependentDecisionFactor_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string LookAheadCoasting_VelocityDropDecisionFactor_Entry {
            get {
                return ResourceManager.GetString("LookAheadCoasting_VelocityDropDecisionFactor_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cycle.
        /// </summary>
        public static string Missions_Cycle {
            get {
                return ResourceManager.GetString("Missions_Cycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CdxA.
        /// </summary>
        public static string Report_AirDrag_CdxA {
            get {
                return ResourceManager.GetString("Report_AirDrag_CdxA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationInformation.
        /// </summary>
        public static string Report_ApplicationInfo_ApplicationInformation {
            get {
                return ResourceManager.GetString("Report_ApplicationInfo_ApplicationInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        public static string Report_ApplicationInfo_Date {
            get {
                return ResourceManager.GetString("Report_ApplicationInfo_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimulationToolVersion.
        /// </summary>
        public static string Report_ApplicationInfo_SimulationToolVersion {
            get {
                return ResourceManager.GetString("Report_ApplicationInfo_SimulationToolVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CertificationMethod.
        /// </summary>
        public static string Report_Component_CertificationMethod {
            get {
                return ResourceManager.GetString("Report_Component_CertificationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CertificationNumber.
        /// </summary>
        public static string Report_Component_CertificationNumber {
            get {
                return ResourceManager.GetString("Report_Component_CertificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransmissionRatioFinalGear.
        /// </summary>
        public static string Report_Gearbox_TransmissionRatioFinalGear {
            get {
                return ResourceManager.GetString("Report_Gearbox_TransmissionRatioFinalGear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GearsCount.
        /// </summary>
        public static string Report_GetGearbox_GearsCount {
            get {
                return ResourceManager.GetString("Report_GetGearbox_GearsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InputDataSignature.
        /// </summary>
        public static string Report_Input_Signature {
            get {
                return ResourceManager.GetString("Report_Input_Signature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mission.
        /// </summary>
        public static string Report_Result_Mission {
            get {
                return ResourceManager.GetString("Report_Result_Mission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result.
        /// </summary>
        public static string Report_Result_Result {
            get {
                return ResourceManager.GetString("Report_Result_Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Report_Result_Status {
            get {
                return ResourceManager.GetString("Report_Result_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status.
        /// </summary>
        public static string Report_Result_Status_Attr {
            get {
                return ResourceManager.GetString("Report_Result_Status_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AverageSpeed.
        /// </summary>
        public static string Report_ResultEntry_AverageSpeed {
            get {
                return ResourceManager.GetString("Report_ResultEntry_AverageSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Report_ResultEntry_Distance {
            get {
                return ResourceManager.GetString("Report_ResultEntry_Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FuelType.
        /// </summary>
        public static string Report_ResultEntry_FuelType {
            get {
                return ResourceManager.GetString("Report_ResultEntry_FuelType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FullLoadDrivingtimePercentage.
        /// </summary>
        public static string Report_ResultEntry_FullLoadDrivingtimePercentage {
            get {
                return ResourceManager.GetString("Report_ResultEntry_FullLoadDrivingtimePercentage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GearshiftCount.
        /// </summary>
        public static string Report_ResultEntry_GearshiftCount {
            get {
                return ResourceManager.GetString("Report_ResultEntry_GearshiftCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxAcceleration.
        /// </summary>
        public static string Report_ResultEntry_MaxAcceleration {
            get {
                return ResourceManager.GetString("Report_ResultEntry_MaxAcceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxDeceleration.
        /// </summary>
        public static string Report_ResultEntry_MaxDeceleration {
            get {
                return ResourceManager.GetString("Report_ResultEntry_MaxDeceleration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxSpeed.
        /// </summary>
        public static string Report_ResultEntry_MaxSpeed {
            get {
                return ResourceManager.GetString("Report_ResultEntry_MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinSpeed.
        /// </summary>
        public static string Report_ResultEntry_MinSpeed {
            get {
                return ResourceManager.GetString("Report_ResultEntry_MinSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payload.
        /// </summary>
        public static string Report_ResultEntry_Payload {
            get {
                return ResourceManager.GetString("Report_ResultEntry_Payload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimulationParameters.
        /// </summary>
        public static string Report_ResultEntry_SimulationParameters {
            get {
                return ResourceManager.GetString("Report_ResultEntry_SimulationParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TotalVehicleMass.
        /// </summary>
        public static string Report_ResultEntry_TotalVehicleMass {
            get {
                return ResourceManager.GetString("Report_ResultEntry_TotalVehicleMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VehiclePerformance.
        /// </summary>
        public static string Report_ResultEntry_VehiclePerformance {
            get {
                return ResourceManager.GetString("Report_ResultEntry_VehiclePerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO2.
        /// </summary>
        public static string Report_Results_CO2 {
            get {
                return ResourceManager.GetString("Report_Results_CO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Report_Results_Error {
            get {
                return ResourceManager.GetString("Report_Results_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorDetails.
        /// </summary>
        public static string Report_Results_ErrorDetails {
            get {
                return ResourceManager.GetString("Report_Results_ErrorDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FuelConsumption.
        /// </summary>
        public static string Report_Results_FuelConsumption {
            get {
                return ResourceManager.GetString("Report_Results_FuelConsumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unit.
        /// </summary>
        public static string Report_Results_Unit_Attr {
            get {
                return ResourceManager.GetString("Report_Results_Unit_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TyreCertificationNumber.
        /// </summary>
        public static string Report_Tyre_TyreCertificationNumber {
            get {
                return ResourceManager.GetString("Report_Tyre_TyreCertificationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TyreDimension.
        /// </summary>
        public static string Report_Tyre_TyreDimension {
            get {
                return ResourceManager.GetString("Report_Tyre_TyreDimension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TyreRRCDeclared.
        /// </summary>
        public static string Report_Tyre_TyreRRCDeclared {
            get {
                return ResourceManager.GetString("Report_Tyre_TyreRRCDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AverageRRC.
        /// </summary>
        public static string Report_Vehicle_AverageRRC {
            get {
                return ResourceManager.GetString("Report_Vehicle_AverageRRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxleRatio.
        /// </summary>
        public static string Report_Vehicle_AxleRatio {
            get {
                return ResourceManager.GetString("Report_Vehicle_AxleRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EngineDisplacement.
        /// </summary>
        public static string Report_Vehicle_EngineDisplacement {
            get {
                return ResourceManager.GetString("Report_Vehicle_EngineDisplacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EngineRatedPower.
        /// </summary>
        public static string Report_Vehicle_EngineRatedPower {
            get {
                return ResourceManager.GetString("Report_Vehicle_EngineRatedPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retarder.
        /// </summary>
        public static string Report_Vehicle_Retarder {
            get {
                return ResourceManager.GetString("Report_Vehicle_Retarder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TransmissionMainCertificationMethod.
        /// </summary>
        public static string Report_Vehicle_TransmissionCertificationMethod {
            get {
                return ResourceManager.GetString("Report_Vehicle_TransmissionCertificationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VehicleGroup.
        /// </summary>
        public static string Report_Vehicle_VehicleGroup {
            get {
                return ResourceManager.GetString("Report_Vehicle_VehicleGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetarderLossMap.
        /// </summary>
        public static string Retarder_RetarderLossMap {
            get {
                return ResourceManager.GetString("Retarder_RetarderLossMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Retarder_RetarderLossMap_Entry {
            get {
                return ResourceManager.GetString("Retarder_RetarderLossMap_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to retarderSpeed.
        /// </summary>
        public static string Retarder_RetarderLossmap_RetarderSpeed_Attr {
            get {
                return ResourceManager.GetString("Retarder_RetarderLossmap_RetarderSpeed_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to torqueLoss.
        /// </summary>
        public static string Retarder_RetarderLossmap_TorqueLoss_Attr {
            get {
                return ResourceManager.GetString("Retarder_RetarderLossmap_TorqueLoss_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characteristics.
        /// </summary>
        public static string TorqueConverter_Characteristics {
            get {
                return ResourceManager.GetString("TorqueConverter_Characteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string TorqueConverter_Characteristics_Entry {
            get {
                return ResourceManager.GetString("TorqueConverter_Characteristics_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inertia.
        /// </summary>
        public static string TorqueConverter_Inertia {
            get {
                return ResourceManager.GetString("TorqueConverter_Inertia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReferenceRPM.
        /// </summary>
        public static string TorqueConverter_ReferenceRPM {
            get {
                return ResourceManager.GetString("TorqueConverter_ReferenceRPM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShiftPolygon.
        /// </summary>
        public static string TorqueConverter_ShiftPolygon {
            get {
                return ResourceManager.GetString("TorqueConverter_ShiftPolygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string TorqueConverter_ShiftPolygon_Entry {
            get {
                return ResourceManager.GetString("TorqueConverter_ShiftPolygon_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to speedRatio.
        /// </summary>
        public static string TorqueConverterData_SpeedRatio_Attr {
            get {
                return ResourceManager.GetString("TorqueConverterData_SpeedRatio_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to torqueRatio.
        /// </summary>
        public static string TorqueConverterData_TorqueRatio_Attr {
            get {
                return ResourceManager.GetString("TorqueConverterData_TorqueRatio_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inputTorqueRef.
        /// </summary>
        public static string TorqueConverterDataMapping_InputTorqueRef_Attr {
            get {
                return ResourceManager.GetString("TorqueConverterDataMapping_InputTorqueRef_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inputSpeed.
        /// </summary>
        public static string TransmissionLossmap_InputSpeed_Attr {
            get {
                return ResourceManager.GetString("TransmissionLossmap_InputSpeed_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to inputTorque.
        /// </summary>
        public static string TransmissionLossmap_InputTorque_Attr {
            get {
                return ResourceManager.GetString("TransmissionLossmap_InputTorque_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to torqueLoss.
        /// </summary>
        public static string TransmissionLossmap_TorqueLoss_Attr {
            get {
                return ResourceManager.GetString("TransmissionLossmap_TorqueLoss_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VectoComponentEngineering.
        /// </summary>
        public static string VectoComponentEngineering {
            get {
                return ResourceManager.GetString("VectoComponentEngineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VectoCustomerInformation.
        /// </summary>
        public static string VectoCustomerReport {
            get {
                return ResourceManager.GetString("VectoCustomerReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VectoInputDeclaration.
        /// </summary>
        public static string VectoInputDeclaration {
            get {
                return ResourceManager.GetString("VectoInputDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VectoInputEngineering.
        /// </summary>
        public static string VectoInputEngineering {
            get {
                return ResourceManager.GetString("VectoInputEngineering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EngineOnlyMode.
        /// </summary>
        public static string VectoJob_EngineOnlyMode {
            get {
                return ResourceManager.GetString("VectoJob_EngineOnlyMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MissionCycles.
        /// </summary>
        public static string VectoJob_MissionCycles {
            get {
                return ResourceManager.GetString("VectoJob_MissionCycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VectoOutput.
        /// </summary>
        public static string VectoManufacturerReport {
            get {
                return ResourceManager.GetString("VectoManufacturerReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxAcceleration.
        /// </summary>
        public static string Vehicle_AccelerationCurve_MaxAcceleration_Attr {
            get {
                return ResourceManager.GetString("Vehicle_AccelerationCurve_MaxAcceleration_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxDeceleration.
        /// </summary>
        public static string Vehicle_AccelerationCurve_MaxDeceleration_Attr {
            get {
                return ResourceManager.GetString("Vehicle_AccelerationCurve_MaxDeceleration_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicleSpeed.
        /// </summary>
        public static string Vehicle_AccelerationCurve_VehicleSpeed_Attr {
            get {
                return ResourceManager.GetString("Vehicle_AccelerationCurve_VehicleSpeed_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AdvancedDriverAssist.
        /// </summary>
        public static string Vehicle_AdvancedDriverAssist {
            get {
                return ResourceManager.GetString("Vehicle_AdvancedDriverAssist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EngineStartStop.
        /// </summary>
        public static string Vehicle_AdvancedDriverAssist_EngineStartStop {
            get {
                return ResourceManager.GetString("Vehicle_AdvancedDriverAssist_EngineStartStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivationDelay.
        /// </summary>
        public static string Vehicle_AdvancedDriverAssist_EngineStartStop_ActivationDelay {
            get {
                return ResourceManager.GetString("Vehicle_AdvancedDriverAssist_EngineStartStop_ActivationDelay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enabled.
        /// </summary>
        public static string Vehicle_AdvancedDriverAssist_EngineStartStop_Enabled {
            get {
                return ResourceManager.GetString("Vehicle_AdvancedDriverAssist_EngineStartStop_Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MaxSpeed.
        /// </summary>
        public static string Vehicle_AdvancedDriverAssist_EngineStartStop_MaxSpeed {
            get {
                return ResourceManager.GetString("Vehicle_AdvancedDriverAssist_EngineStartStop_MaxSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinOnTime.
        /// </summary>
        public static string Vehicle_AdvancedDriverAssist_EngineStartStop_MinOnTime {
            get {
                return ResourceManager.GetString("Vehicle_AdvancedDriverAssist_EngineStartStop_MinOnTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CdxA.
        /// </summary>
        public static string Vehicle_AirDragArea {
            get {
                return ResourceManager.GetString("Vehicle_AirDragArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AngledriveType.
        /// </summary>
        public static string Vehicle_AngledriveType {
            get {
                return ResourceManager.GetString("Vehicle_AngledriveType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AxleConfiguration.
        /// </summary>
        public static string Vehicle_AxleConfiguration {
            get {
                return ResourceManager.GetString("Vehicle_AxleConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Components.
        /// </summary>
        public static string Vehicle_Components {
            get {
                return ResourceManager.GetString("Vehicle_Components", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrossWindCorrectionData.
        /// </summary>
        public static string Vehicle_CrosswindCorrectionData {
            get {
                return ResourceManager.GetString("Vehicle_CrosswindCorrectionData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Vehicle_CrosswindCorrectionData_Entry {
            get {
                return ResourceManager.GetString("Vehicle_CrosswindCorrectionData_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to beta.
        /// </summary>
        public static string Vehicle_CrosswindCorrectionMap_Beta {
            get {
                return ResourceManager.GetString("Vehicle_CrosswindCorrectionMap_Beta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CdScalingFactor.
        /// </summary>
        public static string Vehicle_CrosswindCorrectionMap_CdScalingFactor {
            get {
                return ResourceManager.GetString("Vehicle_CrosswindCorrectionMap_CdScalingFactor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deltaCdxA.
        /// </summary>
        public static string Vehicle_CrosswindCorrectionMap_DeltaCdxA {
            get {
                return ResourceManager.GetString("Vehicle_CrosswindCorrectionMap_DeltaCdxA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to vehicleSpeed.
        /// </summary>
        public static string Vehicle_CrosswindCorrectionMap_VehicleSpeed_Attr {
            get {
                return ResourceManager.GetString("Vehicle_CrosswindCorrectionMap_VehicleSpeed_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrossWindCorrectionMode.
        /// </summary>
        public static string Vehicle_CrossWindCorrectionMode {
            get {
                return ResourceManager.GetString("Vehicle_CrossWindCorrectionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurbMassChassis.
        /// </summary>
        public static string Vehicle_CurbMassChassis {
            get {
                return ResourceManager.GetString("Vehicle_CurbMassChassis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurbMassExtra.
        /// </summary>
        public static string Vehicle_CurbMassExtra {
            get {
                return ResourceManager.GetString("Vehicle_CurbMassExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurbWeightChassis.
        /// </summary>
        public static string Vehicle_CurbWeightChassis {
            get {
                return ResourceManager.GetString("Vehicle_CurbWeightChassis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurbWeightExtra.
        /// </summary>
        public static string Vehicle_CurbWeightExtra {
            get {
                return ResourceManager.GetString("Vehicle_CurbWeightExtra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GrossVehicleMass.
        /// </summary>
        public static string Vehicle_GrossVehicleMass {
            get {
                return ResourceManager.GetString("Vehicle_GrossVehicleMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IdlingSpeed.
        /// </summary>
        public static string Vehicle_IdlingSpeed {
            get {
                return ResourceManager.GetString("Vehicle_IdlingSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LegislativeClass.
        /// </summary>
        public static string Vehicle_LegislativeClass {
            get {
                return ResourceManager.GetString("Vehicle_LegislativeClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string Vehicle_Loading {
            get {
                return ResourceManager.GetString("Vehicle_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTO.
        /// </summary>
        public static string Vehicle_PTO {
            get {
                return ResourceManager.GetString("Vehicle_PTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTOOtherElements.
        /// </summary>
        public static string Vehicle_PTO_OtherElements {
            get {
                return ResourceManager.GetString("Vehicle_PTO_OtherElements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTOShaftsGearWheels.
        /// </summary>
        public static string Vehicle_PTO_ShaftsGearWheels {
            get {
                return ResourceManager.GetString("Vehicle_PTO_ShaftsGearWheels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTOCycle.
        /// </summary>
        public static string Vehicle_PTOCycle {
            get {
                return ResourceManager.GetString("Vehicle_PTOCycle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to engineSpeed.
        /// </summary>
        public static string Vehicle_PTOCycle_EngineSpeed_Attr {
            get {
                return ResourceManager.GetString("Vehicle_PTOCycle_EngineSpeed_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Vehicle_PTOCycle_Entry {
            get {
                return ResourceManager.GetString("Vehicle_PTOCycle_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to time.
        /// </summary>
        public static string Vehicle_PTOCycle_Time_Attr {
            get {
                return ResourceManager.GetString("Vehicle_PTOCycle_Time_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to torque.
        /// </summary>
        public static string Vehicle_PTOCycle_Torque_Attr {
            get {
                return ResourceManager.GetString("Vehicle_PTOCycle_Torque_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTOIdleLossMap.
        /// </summary>
        public static string Vehicle_PTOIdleLossMap {
            get {
                return ResourceManager.GetString("Vehicle_PTOIdleLossMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to engineSpeed.
        /// </summary>
        public static string Vehicle_PTOIdleLossMap_EngineSpeed_Attr {
            get {
                return ResourceManager.GetString("Vehicle_PTOIdleLossMap_EngineSpeed_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Vehicle_PTOIdleLossMap_Entry {
            get {
                return ResourceManager.GetString("Vehicle_PTOIdleLossMap_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ptoTorqueLoss.
        /// </summary>
        public static string Vehicle_PTOIdleLossMap_TorqueLoss_Attr {
            get {
                return ResourceManager.GetString("Vehicle_PTOIdleLossMap_TorqueLoss_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PTOType.
        /// </summary>
        public static string Vehicle_PTOType {
            get {
                return ResourceManager.GetString("Vehicle_PTOType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetarderRatio.
        /// </summary>
        public static string Vehicle_RetarderRatio {
            get {
                return ResourceManager.GetString("Vehicle_RetarderRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RetarderType.
        /// </summary>
        public static string Vehicle_RetarderType {
            get {
                return ResourceManager.GetString("Vehicle_RetarderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SteeredAxles.
        /// </summary>
        public static string Vehicle_SteeredAxles {
            get {
                return ResourceManager.GetString("Vehicle_SteeredAxles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TorqueLimits.
        /// </summary>
        public static string Vehicle_TorqueLimits {
            get {
                return ResourceManager.GetString("Vehicle_TorqueLimits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entry.
        /// </summary>
        public static string Vehicle_TorqueLimits_Entry {
            get {
                return ResourceManager.GetString("Vehicle_TorqueLimits_Entry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gear.
        /// </summary>
        public static string Vehicle_TorqueLimits_Entry_Gear_Attr {
            get {
                return ResourceManager.GetString("Vehicle_TorqueLimits_Entry_Gear_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to maxTorque.
        /// </summary>
        public static string Vehicle_TorqueLimits_Entry_MaxTorque_Attr {
            get {
                return ResourceManager.GetString("Vehicle_TorqueLimits_Entry_MaxTorque_Attr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VehicleCategory.
        /// </summary>
        public static string Vehicle_VehicleCategory {
            get {
                return ResourceManager.GetString("Vehicle_VehicleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VIN.
        /// </summary>
        public static string Vehicle_VIN {
            get {
                return ResourceManager.GetString("Vehicle_VIN", resourceCulture);
            }
        }
    }
}
