<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>LicenceHeader</RootNamespace>
    <AssemblyName>LicenceHeader</AssemblyName>
    <DefineConstants />
    <TargetFrameworks>net5.0</TargetFrameworks>
  </PropertyGroup>
  <ItemGroup>
    <None Update="header.txt">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>