<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TUGraz.VectoCore.Tests</RootNamespace>
    <AssemblyName>VectoCoreTest</AssemblyName>
    <TargetFrameworks>net6.0</TargetFrameworks>
    <DefineConstants />
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Ninject" Version="3.3.3" />
    <PackageReference Include="NLog" Version="4.7.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\VectoCommon\VectoCommon\VectoCommon.csproj" />
    <ProjectReference Include="..\VectoCore\VectoCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="TestData\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms">
      <HintPath>C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5\System.Windows.Forms.dll</HintPath>
    </Reference>
    <Reference Include="System.Windows.Forms.DataVisualization" />
  </ItemGroup>

</Project>