<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TUGraz.VectoCore.Tests</RootNamespace>
    <AssemblyName>VectoCoreTest</AssemblyName>
    <TargetFrameworks>net6.0</TargetFrameworks>
    <DefineConstants />
    <Configurations>Debug;Release;MockupDebug</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MockupDebug|net6.0|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit" Version="3.13.2" />
    <PackageReference Include="NUnit3TestAdapter" Version="4.2.1" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.1.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Ninject" Version="3.3.5" />
    <PackageReference Include="NLog" Version="4.7.13" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\VectoCommon\VectoCommon\VectoCommon.csproj" />
    <ProjectReference Include="..\VectoCore\VectoCore.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="TestData\**" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <None Update="TestData\XML\XMLReaderDeclaration\SchemaVersion2.4\Distributed\HeavyLorry\HEV-S_heavyLorry_S3_ovc.xml">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>
	<Choose>
		<When Condition="'$(Configuration)|$(Platform)'=='MockupDebug|AnyCPU'">
			<ItemGroup>
				<ProjectReference Include="..\..\VectoMockup\VectoMockup\VectoMockup.csproj" />

			</ItemGroup>
			<PropertyGroup>
				<DefineConstants>MOCKUP</DefineConstants>
			</PropertyGroup>
		</When>
	</Choose>

</Project>