<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TUGraz.VectoCore.ModelbasedTests</RootNamespace>
    <AssemblyName>ModelbasedTests</AssemblyName>
    <TargetFrameworks>net8.0</TargetFrameworks>

  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NUnit3TestAdapter" Version="4.4.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\VectoCommon\VectoCommon\VectoCommon.csproj" />
    <ProjectReference Include="..\VectoCoreTest\VectoCoreTest.csproj" />
    <ProjectReference Include="..\VectoCore\VectoCore.csproj" />
  </ItemGroup>
</Project>