Imports VectoAuxiliaries.Electrics
Namespace Electrics

Public Class ElectricsUserInputsConfig
Implements IElectricsUserInputsConfig


Public Property PowerNetVoltage As Single Implements IElectricsUserInputsConfig.PowerNetVoltage
Public Property AlternatorMap As String Implements IElectricsUserInputsConfig.AlternatorMap
Public Property AlternatorGearEfficiency As Single Implements IElectricsUserInputsConfig.AlternatorGearEfficiency
Public Property ElectricalConsumers As IElectricalConsumerList Implements IElectricsUserInputsConfig.ElectricalConsumers
Public Property DoorActuationTimeSecond As Integer Implements IElectricsUserInputsConfig.DoorActuationTimeSecond


Public Property ResultCardIdle As List(Of SmartResult) Implements IElectricsUserInputsConfig.ResultCardIdle
Public Property ResultCardTraction As List(Of SmartResult) Implements IElectricsUserInputsConfig.ResultCardTraction
Public Property ResultCardOverrun As List(Of SmartResult) Implements IElectricsUserInputsConfig.ResultCardOverrun

Public Property SmartElectrical As Boolean Implements IElectricsUserInputsConfig.SmartElectrical


End Class

End Namespace



