<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <!-- Version Information (only needed if it differs from Global VECTO Version)-->
    <MainProductVersion>0.1.0</MainProductVersion>
    <VersionPrefix>$(MainProductVersion).$([System.DateTime]::UtcNow.Subtract($([System.DateTime]::new(2015,1,1))).Days)</VersionPrefix>

    <RootNamespace>HashingCmd</RootNamespace>
    <AssemblyName>hashingcmd</AssemblyName>
    <TargetFrameworks>net48;net6.0</TargetFrameworks>
    <DefineConstants />
    <OutputType>Exe</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\VectoCommon\VectoCommon\VectoCommon.csproj" />
    <ProjectReference Include="..\VectoCommon\VectoHashing\VectoHashing.csproj" />
    <ProjectReference Include="..\VectoCore\VectoCore\VectoCore.csproj" />
  </ItemGroup>
</Project>