<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TUGraz.VectoCore</RootNamespace>
    <AssemblyName>VectoCore</AssemblyName>
    <TargetFrameworks>net45;net48;net5.0</TargetFrameworks>
    <DefineConstants />
  </PropertyGroup>
  <ItemGroup>
    <None Remove="Resources\XSD\VectoDeclarationDefinitions.2.2.1.xsd" />
    <None Remove="Resources\XSD\VectoOutputPrimaryBus.xsd" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.1" />
    <PackageReference Include="Ninject.Extensions.Factory" Version="3.3.3" />
    <PackageReference Include="NLog" Version="4.7.13" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net45'">
    <Reference Include="Microsoft.VisualBasic" />
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Windows.Forms.DataVisualization" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='net48'">
    <Reference Include="Microsoft.VisualBasic" />
    <Reference Include="System.Windows.Forms" />
    <Reference Include="System.Windows.Forms.DataVisualization" />
  </ItemGroup>
  
  <ItemGroup>
    <InternalsVisibleTo Include="VectoAPI" />
    <InternalsVisibleTo Include="VectoEngineeringAPI" />
    <InternalsVisibleTo Include="VectoXML" />
    <InternalsVisibleTo Include="XMLTest" />
    <InternalsVisibleTo Include="VECTO" />
    <InternalsVisibleTo Include="VectoCoreTest" />
    <InternalsVisibleTo Include="VectoAPITest" />
    <InternalsVisibleTo Include="VectoXML" />
    <InternalsVisibleTo Include="XMLTest" />
    <InternalsVisibleTo Include="VECTO_GIT" />
    <InternalsVisibleTo Include="VectoAuxiliariesTests" />
    <InternalsVisibleTo Include="VECTO3" />
    <InternalsVisibleTo Include="VECTOMultistage" />
    <InternalsVisibleTo Include="Vecto3GUI2020Test" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\VectoCommon\VectoCommon\VectoCommon.csproj" />
    <ProjectReference Include="..\..\VectoCommon\VectoHashing\VectoHashing.csproj" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Resources\XSD\ParameterDocumentation.xsd">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoDeclarationDefinitions.2.2.1.xsd" />
    <EmbeddedResource Include="Resources\XSD\VectoEngineeringDefinitions.0.6.xsd">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoEngineeringDefinitions.0.7.xsd">
      <SubType>Designer</SubType>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoOutputManufacturer.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoOutputPrimaryBus.xsd" />
    <EmbeddedResource Include="Resources\XSD\xmldsig-core-schema.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>

    <EmbeddedResource Include="Resources\Declaration\Wheels.csv" />
    <EmbeddedResource Include="Resources\Declaration\SegmentTable.csv" />
    <EmbeddedResource Include="Resources\Declaration\MissionCycles\HeavyUrban.vdri" />
    <EmbeddedResource Include="Resources\Declaration\MissionCycles\Suburban.vdri" />
    <EmbeddedResource Include="Resources\Declaration\MissionCycles\Urban.vdri" />
    <EmbeddedResource Include="Resources\Declaration\MissionCycles\Coach.vdri" />
    <EmbeddedResource Include="Resources\Declaration\MissionCycles\Construction.vdri" />
    <EmbeddedResource Include="Resources\Declaration\MissionCycles\Interurban.vdri" />
    <EmbeddedResource Include="Resources\Declaration\MissionCycles\LongHaul.vdri" />
    <EmbeddedResource Include="Resources\Declaration\MissionCycles\MunicipalUtility.vdri" />
    <EmbeddedResource Include="Resources\Declaration\MissionCycles\RegionalDelivery.vdri" />
    <EmbeddedResource Include="Resources\Declaration\MissionCycles\UrbanDelivery.vdri" />
    <EmbeddedResource Include="Resources\Declaration\PT1.csv" />
    <EmbeddedResource Include="Resources\Declaration\VACC\Truck.vacc" />
    <EmbeddedResource Include="Resources\Declaration\VAUX\ES-Tech.csv" />
    <EmbeddedResource Include="Resources\Declaration\VAUX\Fan-Tech.csv" />
    <EmbeddedResource Include="Resources\Declaration\VAUX\HVAC-Table.csv" />
    <EmbeddedResource Include="Resources\Declaration\VAUX\PS-Table.csv" />
    <EmbeddedResource Include="Resources\Declaration\VAUX\SP-Table.csv" />
    <EmbeddedResource Include="Resources\Declaration\VAUX\SP-Tech.csv" />
    <EmbeddedResource Include="Resources\Declaration\VCDV\VCDV_parameters.csv" />
    <EmbeddedResource Include="Resources\Declaration\WHTC-Weighting-Factors.csv" />
    <EmbeddedResource Include="Resources\Declaration\VAUX\ALT-Tech.csv" />
    <EmbeddedResource Include="Resources\Declaration\Report\cyclePageTemplate.pdf" />
    <EmbeddedResource Include="Resources\Declaration\Report\title2CyclesTemplate.pdf" />
    <EmbeddedResource Include="Resources\Declaration\Report\title3CyclesTemplate.pdf" />
    <EmbeddedResource Include="Resources\Declaration\LAC-DF-Vdrop.csv" />
    <EmbeddedResource Include="Resources\Declaration\LAC-DF-Vtarget.csv" />
    <EmbeddedResource Include="Resources\Declaration\Body_Trailers_Weights.csv" />
    <EmbeddedResource Include="Resources\Declaration\Payloads.csv" />
    <EmbeddedResource Include="Resources\Declaration\VAUX\SP-Axles.csv" />
    <EmbeddedResource Include="Resources\Declaration\VAUX\PTO-tech.csv" />
    <EmbeddedResource Include="Resources\Declaration\MissionCycles\MunicipalUtility_PTO_generic.vptoc" />
    <EmbeddedResource Include="Resources\Declaration\MissionCycles\MunicipalUtility_PTO_generic.vptol" />
    <EmbeddedResource Include="Resources\Declaration\FuelTypes.csv" />
    <EmbeddedResource Include="Resources\Declaration\GearshiftParameters\PredictionTimeLookup.csv" />
    <EmbeddedResource Include="Resources\Declaration\GearshiftParameters\AccelerationReserveLookup.csv" />
    <EmbeddedResource Include="Resources\Declaration\GearshiftParameters\ShareEngineSpeedHigh.csv" />
    <EmbeddedResource Include="Resources\Declaration\GearshiftParameters\ShareIdleLow.csv" />
    <EmbeddedResource Include="Resources\Declaration\GearshiftParameters\ShareTq99L.csv" />
    <EmbeddedResource Include="Resources\Declaration\CO2Standards\MissionProfileWeights.csv" />
    <EmbeddedResource Include="Resources\Declaration\CO2Standards\WeightingGroups.csv" />
    <EmbeddedResource Include="Resources\Declaration\TyreLabeling.csv" />
    <EmbeddedResource Include="Resources\XSD\VectoDeclarationDefinitions.1.0.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoOutputCustomer.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoInput.1.0.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoOutputCustomer.0.4.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoOutputManufacturer.0.4.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoEngineeringInput.0.7.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoComponent.1.0.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoOutputManufacturer.0.5.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoOutputCustomer.0.5.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoOutputManufacturer.0.6.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoOutputManufacturer.0.7.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoOutputCustomer.0.7.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoMonitoring.0.7.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoDeclarationDefinitions.2.0.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoDeclarationDefinitions.2.1.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoDeclarationDefinitions.2.2.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoDeclarationDefinitions.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoDeclarationJob.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoComponent.2.0.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoDeclarationComponent.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoEngineeringDefinitions.1.0.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoEngineeringInput.1.0.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoInput.2.0.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoEngineeringDefinitions.1.0.TEST.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoEngineeringComponent.1.0.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoEngineeringComponent.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VTPReport.0.1.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoEngineeringDefinitions.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoEngineeringJob.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoMonitoring.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoOutputCustomer.0.8.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoOutputManufacturer.0.8.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoMonitoring.0.8.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoEngineeringDefinitions.1.1.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Declaration\ADAS\ADAS_Combinations.csv" />
    <EmbeddedResource Include="Resources\Declaration\VAUX\Fan-Tech-Medium.csv" />
    <EmbeddedResource Include="Resources\Declaration\Buses\ElectricConsumers.csv" />
    <EmbeddedResource Include="Resources\Declaration\Buses\SSMTechList.csv" />
    <EmbeddedResource Include="Resources\Declaration\Buses\SSMDefaults.ahsm" />
    <EmbeddedResource Include="Resources\Declaration\Buses\DefaultClimatic.aenv">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Declaration\Buses\AlternatorTechnologies.csv" />
    <None Include="Resources\Declaration\Buses\DefaultBusAuxCfg.aaux">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <EmbeddedResource Include="Resources\Declaration\Buses\DefaultActuationsMap.apac" />
    <EmbeddedResource Include="Resources\Declaration\PrimaryBusSegmentationTable.csv" />
    <EmbeddedResource Include="Resources\Declaration\VACC\Bus.vacc" />
    <EmbeddedResource Include="Resources\Declaration\VAUXBus\DEFAULT_1-Cylinder_1-Stage_393ccm.acmp" />
    <EmbeddedResource Include="Resources\Declaration\VAUXBus\DEFAULT_2-Cylinder_1-Stage_650ccm.acmp" />
    <EmbeddedResource Include="Resources\Declaration\VAUXBus\DEFAULT_2-Cylinder_2-Stage_398ccm.acmp" />
    <EmbeddedResource Include="Resources\Declaration\VAUXBus\DEFAULT_3-Cylinder_2-Stage_598ccm.acmp" />
    <EmbeddedResource Include="Resources\XSD\VectoVTPReport.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoOutputDefinitions.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Declaration\Buses\HVACCoolingPowerDriver.csv" />
    <EmbeddedResource Include="Resources\Declaration\Buses\HVACCoolingPowerPassenger.csv" />
    <EmbeddedResource Include="Resources\XSD\VTPReport.0.2.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VTPReport.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\Declaration\CompletedBusSegmentationTable.csv" />
    <EmbeddedResource Include="Resources\Declaration\VAUXBus\SP-AxleFactor.csv" />
    <EmbeddedResource Include="Resources\Declaration\VAUXBus\SP-Axles_Bus.csv" />
    <EmbeddedResource Include="Resources\Declaration\VAUXBus\SP-Factors_Bus.csv" />
    <EmbeddedResource Include="Resources\Declaration\GenericBusData\EngineConsumptionMap_CI_normalized.vmap" />
    <EmbeddedResource Include="Resources\Declaration\GenericBusData\EngineConsumptionMap_PI_normalized.vmap" />
    <EmbeddedResource Include="Resources\XSD\VectoOutputMultistep.0.1.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoComponent.2.1.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoDeclarationDefinitions.2.3.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoDeclarationDefinitions.2.4.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoMonitoring.0.7.1.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoOutputCustomer.0.7.1.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
    <EmbeddedResource Include="Resources\XSD\VectoOutputManufacturer.0.7.1.xsd">
      <SubType>Designer</SubType>
    </EmbeddedResource>
  </ItemGroup>


  <ItemGroup>
    <EmbeddedResource Include="Resources\Declaration\Report\4x2r.png" />
    <EmbeddedResource Include="Resources\Declaration\Report\4x2rt.png" />
    <EmbeddedResource Include="Resources\Declaration\Report\4x2tt.png" />
    <EmbeddedResource Include="Resources\Declaration\Report\6x2r.png" />
    <EmbeddedResource Include="Resources\Declaration\Report\6x2rt.png" />
    <EmbeddedResource Include="Resources\Declaration\Report\6x2tt.png" />
    <EmbeddedResource Include="Resources\Declaration\Report\Undef.png" />
  </ItemGroup>





  <ItemGroup>
    <Compile Update="JSONKeys.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>JSONKeys.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="JSONKeys.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>JSONKeys.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

</Project>