<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>exe</OutputType>
    
    <AssemblyName>vectocmd</AssemblyName>
    <ApplicationIcon>Icon2.ico</ApplicationIcon>
    <RootNamespace>TUGraz.VECTO</RootNamespace>
    <TargetFrameworks>net45</TargetFrameworks>
	<DefineConstants />
    <StartupObject></StartupObject>
  </PropertyGroup>

</Project>
