<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TUGraz.VectoMockup</RootNamespace>
    <AssemblyName>VectoMockup</AssemblyName>
    <TargetFrameworks>net45;net48;net6.0</TargetFrameworks>
    <DefineConstants Condition="'$(Configuration)' == 'MockupDebug'">Debug</DefineConstants>
    <Configurations>Debug;Release;MockupDebug</Configurations>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MockupDebug|net45|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MockupDebug|net48|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='MockupDebug|net6.0|AnyCPU'">
    <DebugType>full</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <None Remove="MockupResults\CIF_MockupResults_Conv_Bus.xml" />
    <None Remove="MockupResults\CIF_MockupResults_Conv_Lorry.xml" />
    <None Remove="MockupResults\CIF_MockupResults_non-OVC-HEV_Bus.xml" />
    <None Remove="MockupResults\CIF_MockupResults_non-OVC-HEV_Lorry.xml" />
    <None Remove="MockupResults\CIF_MockupResults_OVC-HEV_Bus.xml" />
    <None Remove="MockupResults\CIF_MockupResults_OVC-HEV_Lorry.xml" />
    <None Remove="MockupResults\CIF_MockupResults_PEV_Bus.xml" />
    <None Remove="MockupResults\CIF_MockupResults_PEV_Lorry.xml" />
    <None Remove="MockupResults\MRF_MockupResults_Conv_Bus.xml" />
    <None Remove="MockupResults\MRF_MockupResults_Conv_Lorry.xml" />
    <None Remove="MockupResults\MRF_MockupResults_Error.xml" />
    <None Remove="MockupResults\MRF_MockupResults_non-OVC-HEV_Bus.xml" />
    <None Remove="MockupResults\MRF_MockupResults_non-OVC-HEV_Lorry.xml" />
    <None Remove="MockupResults\MRF_MockupResults_OVC-HEV_Bus.xml" />
    <None Remove="MockupResults\MRF_MockupResults_OVC-HEV_Lorry.xml" />
    <None Remove="MockupResults\MRF_MockupResults_PEV_Bus.xml" />
    <None Remove="MockupResults\MRF_MockupResults_PEV_Lorry.xml" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Include="MockupResults\CIF_MockupResults_Conv_Bus.xml" />
    <EmbeddedResource Include="MockupResults\CIF_MockupResults_Conv_Lorry.xml" />
    <EmbeddedResource Include="MockupResults\CIF_MockupResults_non-OVC-HEV_Bus.xml" />
    <EmbeddedResource Include="MockupResults\CIF_MockupResults_non-OVC-HEV_Lorry.xml" />
    <EmbeddedResource Include="MockupResults\CIF_MockupResults_OVC-HEV_Bus.xml" />
    <EmbeddedResource Include="MockupResults\CIF_MockupResults_OVC-HEV_Lorry.xml" />
    <EmbeddedResource Include="MockupResults\CIF_MockupResults_PEV_Bus.xml" />
    <EmbeddedResource Include="MockupResults\CIF_MockupResults_PEV_Lorry.xml" />
    <EmbeddedResource Include="MockupResults\MRF_MockupResults_Conv_Bus.xml" />
    <EmbeddedResource Include="MockupResults\MRF_MockupResults_Conv_Lorry.xml" />
    <EmbeddedResource Include="MockupResults\MRF_MockupResults_Error.xml" />
    <EmbeddedResource Include="MockupResults\MRF_MockupResults_non-OVC-HEV_Bus.xml" />
    <EmbeddedResource Include="MockupResults\MRF_MockupResults_non-OVC-HEV_Lorry.xml" />
    <EmbeddedResource Include="MockupResults\MRF_MockupResults_OVC-HEV_Bus.xml" />
    <EmbeddedResource Include="MockupResults\MRF_MockupResults_OVC-HEV_Lorry.xml" />
    <EmbeddedResource Include="MockupResults\MRF_MockupResults_PEV_Bus.xml" />
    <EmbeddedResource Include="MockupResults\MRF_MockupResults_PEV_Lorry.xml" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\VectoCore\VectoCore\VectoCore.csproj" />
  </ItemGroup>

</Project>
