<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks />
    <TargetFramework>net45</TargetFramework>
    <AssemblyName>HashingTool</AssemblyName>
    <ApplicationIcon>Icon2.ico</ApplicationIcon>
    <PackageIconUrl />
    <RootNamespace>TUGraz.VECTO</RootNamespace>
    <StartupObject />
  </PropertyGroup>

</Project>
