<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFrameworks>net45</TargetFrameworks>
    <AssemblyName>HashingTool</AssemblyName>
    <ApplicationIcon>HashingIcon.ico</ApplicationIcon>
    <RootNamespace>TUGraz.VECTO</RootNamespace>
  </PropertyGroup>

</Project>
