<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <AssemblyName>HashingTool</AssemblyName>
    <ApplicationIcon>HashingIcon.ico</ApplicationIcon>
    <RootNamespace>TUGraz.VECTO</RootNamespace>
    <TargetFrameworks>net48</TargetFrameworks>
     
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\VECTOStart\StarterHelper.cs" Link="StarterHelper.cs" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="System.Windows.Forms" />
  </ItemGroup>
</Project>
