<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>TUGraz.VectoCommon</RootNamespace>
    <AssemblyName>VectoCommon</AssemblyName>
    <TargetFrameworks>net48;net6.0</TargetFrameworks>
     
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Ninject" Version="3.3.6" />
    <PackageReference Include="Ninject.Extensions.ContextPreservation" Version="3.3.1" />
    <PackageReference Include="Ninject.Extensions.Factory" Version="3.3.3" />
    <PackageReference Include="NLog" Version="4.7.13" />
  </ItemGroup>


  <ItemGroup Condition="'$(TargetFramework)'=='net48'">
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Resources\XMLNames.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>XMLNames.resx</DependentUpon>
    </Compile>
    <EmbeddedResource Update="Resources\XMLNames.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>XMLNames.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
</Project>
