<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com) by Helmut Eichlseder (TU Graz/Inst. f. VKM und THD) -->
<xs:schema xmlns:tns="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.6" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:vectoParam="urn:tugraz:ivt:VectoAPI:ParameterDocumentation" xmlns:di="http://www.w3.org/2000/09/xmldsig#" xmlns:v1.0="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v1.0" xmlns:v2.0="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.0" xmlns:v2.1="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.1" xmlns:v2.4="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.4" targetNamespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.6" elementFormDefault="qualified" attributeFormDefault="unqualified" xsi:schemaLocation="urn:tugraz:ivt:VectoAPI:ParameterDocumentation ParameterDocumentation.xsd">
	<xs:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v1.0" schemaLocation="VectoDeclarationDefinitions.1.0.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.0" schemaLocation="VectoDeclarationDefinitions.2.0.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.1" schemaLocation="VectoDeclarationDefinitions.2.1.xsd"/>
	<xs:complexType name="HeavyBusPrimaryVehicleDeclarationType">
		<xs:complexContent>
			<xs:extension base="v2.0:AbstractVehicleDeclarationType">
				<xs:sequence>
					<xs:element name="ManufacturerPrimaryVehicle" type="v1.0:ManufacturerType"/>
					<xs:element name="ManufacturerAddressPrimaryVehicle" type="v1.0:ManufacturerAddressType"/>
					<xs:element name="Model" type="v1.0:ModelType">
						<xs:annotation>
							<xs:documentation>P236</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="VIN" type="v1.0:VINType">
						<xs:annotation>
							<xs:documentation>P238</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="Date" type="v1.0:DateTimeWithTimezone">
						<xs:annotation>
							<xs:documentation>P239</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="LegislativeClass" type="v1.0:LegislativeClassDeclarationType">
						<xs:annotation>
							<xs:documentation>P251 - enum</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="VehicleCategory" type="tns:VehicleCategoryDeclarationType">
						<xs:annotation>
							<xs:documentation>P036 - enum</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="AxleConfiguration" type="v1.0:VehicleAxleConfigurationDeclarationType">
						<xs:annotation>
							<xs:documentation>P037 - enum</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="TechnicalPermissibleMaximumLadenMass" type="v1.0:VehicleGrossVehicleMassType">
						<xs:annotation>
							<xs:documentation>P041 - [kg]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="IdlingSpeed" type="v1.0:EngineDeclaredSpeedType">
						<xs:annotation>
							<xs:documentation>P198 - [1/min]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="RetarderType" type="v1.0:RetarderTypeType">
						<xs:annotation>
							<xs:documentation>P052 - enum</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="RetarderRatio" type="v1.0:RetarderRatioType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P053 - [-]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="AngledriveType" type="v1.0:AngledriveTypeType">
						<xs:annotation>
							<xs:documentation>P180 - enum</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="ZeroEmissionVehicle" type="xs:boolean"/>
					<xs:element name="ADAS" type="v2.1:AbstractAdvancedDriverAssistantSystemsType"/>
					<xs:element name="TorqueLimits" type="v2.0:AbstractTorqueLimitsType" minOccurs="0"/>
					<xs:element name="Components" type="tns:AbstractHeavyBusPrimaryComponentsDeclarationType"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="LegislativeClassDeclarationType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="N2"/>
			<xs:enumeration value="N3"/>
			<xs:enumeration value="M3"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="VehicleCategoryDeclarationType">
		<xs:annotation>
			<xs:appinfo>
				<vectoParam:description>
					<vectoParam:parameterId component="Vehicle">036</vectoParam:parameterId>
					<vectoParam:unit>-</vectoParam:unit>
				</vectoParam:description>
			</xs:appinfo>
			<xs:documentation>P036 - enum (Declaration)</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Bus"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="AbstractHeavyBusPrimaryComponentsDeclarationType" abstract="true"/>
	<xs:complexType name="VehicleComponentsType">
		<xs:complexContent>
			<xs:extension base="tns:AbstractHeavyBusPrimaryComponentsDeclarationType">
				<xs:sequence>
					<xs:element name="Engine" type="v2.0:EngineComponentDeclarationType"/>
					<xs:element name="Gearbox" type="v2.0:GearboxComponentDeclarationType"/>
					<xs:element name="TorqueConverter" type="v2.0:TorqueConverterComponentDeclarationType" minOccurs="0"/>
					<xs:element name="Angledrive" type="v2.0:AngledriveComponentDeclarationType" minOccurs="0"/>
					<xs:element name="Retarder" type="v2.0:RetarderComponentDeclarationType" minOccurs="0"/>
					<xs:element name="Axlegear" type="v2.0:AxlegearComponentDeclarationType"/>
					<xs:element name="AxleWheels" type="v2.0:AxleWheelsComponentDeclarationType"/>
					<xs:element name="Auxiliaries" type="tns:AuxiliariesComponentHeavyBusDeclarationType"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="AuxiliariesComponentHeavyBusDeclarationType">
		<xs:sequence>
			<xs:element name="Data" type="tns:AbstractAuxiliaryDataHeavyBusDeclarationType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AbstractAuxiliaryDataHeavyBusDeclarationType" abstract="true"/>
	<xs:complexType name="AuxiliaryDataHeavyBusDeclarationType">
		<xs:complexContent>
			<xs:extension base="tns:AbstractAuxiliaryDataHeavyBusDeclarationType">
				<xs:sequence>
					<xs:element name="Fan">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Technology" type="v1.0:AuxFanTechnologyType">
									<xs:annotation>
										<xs:documentation>P181</xs:documentation>
									</xs:annotation>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="SteeringPump">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Technology" maxOccurs="4">
									<xs:annotation>
										<xs:documentation>P182</xs:documentation>
									</xs:annotation>
									<xs:complexType>
										<xs:simpleContent>
											<xs:extension base="tns:AuxSPTechnologyType">
												<xs:attribute name="axleNumber" use="required">
													<xs:simpleType>
														<xs:restriction base="xs:int">
															<xs:minInclusive value="1"/>
															<xs:maxInclusive value="4"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:extension>
										</xs:simpleContent>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="ElectricSystem">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="AlternatorTechnology" maxOccurs="unbounded">
									<xs:annotation>
										<xs:documentation>PXXX</xs:documentation>
									</xs:annotation>
									<xs:complexType>
										<xs:simpleContent>
											<xs:extension base="xs:string">
												<xs:attribute name="ratio" type="v1.0:Double3" use="required"/>
											</xs:extension>
										</xs:simpleContent>
									</xs:complexType>
								</xs:element>
								<xs:element name="SmartElectrics" type="xs:boolean"/>
								<xs:element name="ResultCards"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="PneumaticSystem">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="AirsuspensionControl">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="mechanically"/>
											<xs:enumeration value="electronically"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="AdBlueDosing" type="xs:boolean"/>
								<xs:element name="DoorDriveTechnology">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="pneumatic"/>
											<xs:enumeration value="electric"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="HVAC">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="AdjustableCoolantThermostat" type="xs:boolean"/>
								<xs:element name="EngineWasteGasHeatExchanger" type="xs:boolean"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="AuxSPTechnologyType">
		<xs:annotation>
			<xs:documentation>P182</xs:documentation>
			<xs:appinfo>
				<vectoParam:description>
					<vectoParam:parameterId component="Vehicle/Auxiliaries">182</vectoParam:parameterId>
					<vectoParam:comment>Multiple entires allowed, one per steered axle</vectoParam:comment>
					<vectoParam:unit>-</vectoParam:unit>
				</vectoParam:description>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Fixed displacement"/>
			<xs:enumeration value="Fixed displacement with elec. control"/>
			<xs:enumeration value="Dual displacement with mech. control"/>
			<xs:enumeration value="Dual displacement with elec. control"/>
			<xs:enumeration value="Variable displacement mech. controlled"/>
			<xs:enumeration value="Variable displacement elec. controlled"/>
			<xs:enumeration value="Electric driven pump"/>
			<xs:enumeration value="Full electric steering gear"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AuxFanTechnologyType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="Crankshaft mounted - Electronically controlled visco clutch"/>
			<xs:enumeration value="Crankshaft mounted - Bimetallic controlled visco clutch"/>
			<xs:enumeration value="Crankshaft mounted - Discrete step clutch 2 stages"/>
			<xs:enumeration value="Crankshaft mounted - Discrete step clutch 3 stages"/>
			<xs:enumeration value="Crankshaft mounted - On/off clutch"/>
			<xs:enumeration value="Belt driven or driven via transm. - Electronically controlled visco clutch"/>
			<xs:enumeration value="Belt driven or driven via transm. - Bimetallic controlled visco clutch"/>
			<xs:enumeration value="Belt driven or driven via transm. - Discrete step clutch 2 stages"/>
			<xs:enumeration value="Belt driven or driven via transm. - Discrete step clutch 3 stages"/>
			<xs:enumeration value="Belt driven or driven via transm. - On/off clutch"/>
			<xs:enumeration value="Hydraulic driven - Variable displacement pump"/>
			<xs:enumeration value="Hydraulic driven - Constant displacement pump"/>
			<xs:enumeration value="Electrically driven - Electronically controlled"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
