<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com) by Helmut Eichlseder (TU Graz/Inst. f. VKM und THD) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:mrf="urn:tugraz:ivt:VectoAPI:DeclarationOutput:v0.9" xmlns:out="urn:tugraz:ivt:VectoAPI:DeclarationOutputDefinitions" xmlns:dd="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions" xmlns:v2.0="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.0" xmlns:v1.0="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v1.0" xmlns:v2.1="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.1" xmlns:v2.10.1="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.10.1" xmlns:v2.10.2="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.10.2" xmlns:v2.3="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.3" targetNamespace="urn:tugraz:ivt:VectoAPI:DeclarationOutput:v0.9" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<!-- Imports_______________________________________________ -->
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v1.0" schemaLocation="VectoDeclarationDefinitions.1.0.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.0" schemaLocation="VectoDeclarationDefinitions.2.0.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.1" schemaLocation="VectoDeclarationDefinitions.2.1.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.3" schemaLocation="VectoDeclarationDefinitions.2.3_DEV.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.10.1" schemaLocation="VectoDeclarationDefinitions.2.10.1_xEV_Components.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.10.2" schemaLocation="VectoDeclarationDefinitions.2.10.2_JobInputData.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions" schemaLocation="VectoDeclarationDefinitions.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationOutputDefinitions" schemaLocation="VectoOutputDefinitions.xsd"/>
	<!-- End imports___________________________________________ -->
	<xs:element name="VectoOutput" type="mrf:AbstractVectoManufacturerOutputType">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="AbstractVectoManufacturerOutputType" abstract="true"/>
	<xs:complexType name="ConventionalLorryManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType">
				<xs:sequence>
					<xs:element name="Vehicle" type="mrf:Conventional-LorryVehicleOutputType"/>
					<xs:element name="Components">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Engine" type="mrf:EngineOutputType"/>
								<xs:element name="Transmission" type="mrf:TransmissionType"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="Results"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="HEV-Px_IHPCLorryManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType">
				<xs:sequence>
					<xs:element name="Vehicle" type="mrf:HEV-LorryVehicleOutputType"/>
					<xs:element name="Components">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Engine" type="mrf:EngineOutputType"/>
								<xs:element name="Transmission" type="mrf:TransmissionType"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="Results"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="HEV-S2_LorryManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType">
				<xs:sequence>
					<xs:element name="Vehicle" type="mrf:HEV-LorryVehicleOutputType"/>
					<xs:element name="Components">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Engine" type="mrf:EngineOutputType"/>
								<xs:element name="Transmission" type="mrf:TransmissionType"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="Results"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="HEV-S3_LorryManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType">
				<xs:sequence>
					<xs:element name="Vehicle" type="mrf:HEV-LorryVehicleOutputType"/>
					<xs:element name="Components">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Engine" type="mrf:EngineOutputType"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="Results"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="HEV-S4_LorryManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType">
				<xs:sequence>
					<xs:element name="Vehicle" type="mrf:HEV-LorryVehicleOutputType"/>
					<xs:element name="Components">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Engine" type="mrf:EngineOutputType"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="Results"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="HEV-IEPC-S_LorryManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType">
				<xs:sequence>
					<xs:element name="Vehicle" type="mrf:HEV-LorryVehicleOutputType"/>
					<xs:element name="Components">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Engine" type="mrf:EngineOutputType"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="Results"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PEV-E2_LorryManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PEV-E3_LorryManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PEV-E4_LorryManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PEV-IEPC_LorryManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ConventionalPrimaryBusManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType">
				<xs:sequence>
					<xs:element name="Vehicle" type="mrf:Conventional-PrimaryBus-VehicleOutputType"/>
					<xs:element name="Components">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Engine" type="mrf:EngineOutputType"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="Result"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="HEV-Px_IHPCPrimaryBusManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType">
				<xs:sequence>
					<xs:element name="Vehicle" type="mrf:HEV-PrimaryBus-VehicleOutputType"/>
					<xs:element name="Components">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Engine" type="mrf:EngineOutputType"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="Result"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="HEV-S2_PrimaryBusManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType">
				<xs:sequence>
					<xs:element name="Vehicle" type="mrf:HEV-PrimaryBus-VehicleOutputType"/>
					<xs:element name="Components">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Engine" type="mrf:EngineOutputType"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="Result"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="HEV-S3_PrimaryBusManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType">
				<xs:sequence>
					<xs:element name="Vehicle" type="mrf:HEV-PrimaryBus-VehicleOutputType"/>
					<xs:element name="Components">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Engine" type="mrf:EngineOutputType"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="Result"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="HEV-S4_PrimaryBusManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType">
				<xs:sequence>
					<xs:element name="Vehicle" type="mrf:HEV-PrimaryBus-VehicleOutputType"/>
					<xs:element name="Components">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Engine" type="mrf:EngineOutputType"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="Result"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="HEV-IEPC-S_PrimaryBusManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType">
				<xs:sequence>
					<xs:element name="Vehicle" type="mrf:HEV-PrimaryBus-VehicleOutputType"/>
					<xs:element name="Components">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="Engine" type="mrf:EngineOutputType"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="Result"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PEV-E2_PrimaryBusManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType">
				<xs:sequence>
					<xs:element name="Vehicle" type="mrf:PEV-PrimaryBus-VehicleOutputType"/>
					<xs:element name="Components"/>
					<xs:element name="Result"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PEV-E3_PrimaryBusManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType">
				<xs:sequence>
					<xs:element name="Vehicle" type="mrf:PEV-PrimaryBus-VehicleOutputType"/>
					<xs:element name="Components"/>
					<xs:element name="Result"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PEV-E4_PrimaryBusManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType">
				<xs:sequence>
					<xs:element name="Vehicle" type="mrf:PEV-PrimaryBus-VehicleOutputType"/>
					<xs:element name="Components"/>
					<xs:element name="Result"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PEV-IEPC_PrimaryBusManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType">
				<xs:sequence>
					<xs:element name="Vehicle" type="mrf:PEV-PrimaryBus-VehicleOutputType"/>
					<xs:element name="Components"/>
					<xs:element name="Result"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ConventionalCompletedBusManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="HEVCompletedBusManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="PEVCompletedBusManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ExemptedLorryManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ExemptedPrimaryBusManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ExemptedCompletedBusManufacturerOutputDataType">
		<xs:complexContent>
			<xs:extension base="mrf:AbstractVectoManufacturerOutputType"/>
		</xs:complexContent>
	</xs:complexType>
	<!--Vehicle-->
	<xs:group name="GeneralVehicleOutputGroup">
		<xs:sequence>
			<xs:element name="Model" type="v1.0:ModelType">
				<xs:annotation>
					<xs:documentation>1.1.2. Vehicle model/Commercial Name</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="VIN" type="v1.0:VINType">
				<xs:annotation>
					<xs:documentation>1.1.3. Vehicle identification number (VIN)</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="AxleConfiguration">
				<xs:annotation>
					<xs:documentation>1.1.5 Axle configuration</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="TechnicalPermissibleMaximumLadenMass" type="v1.0:VehicleGrossVehicleMassType">
				<xs:annotation>
					<xs:documentation>1.1.6. Technical Permissible Maximum Laden Mass [t]</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="VehicleGroup" type="v1.0:LegislativeClassDeclarationType">
				<xs:annotation>
					<xs:documentation>1.1.7.Vehicle group (Annex 1)</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="OffVehicleChargingGroup">
		<xs:annotation>
			<xs:documentation>			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="OffVehicleChargingCapability" type="v1.0:ManufacturerType"/>
			<xs:element name="OffVehicleChargingMaxPower" type="v1.0:ManufacturerAddressType" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="ManufacturerGroup">
		<xs:annotation>
			<xs:documentation>1.1.1. Name and address of manufacturer (s)
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Manufacturer" type="v1.0:ManufacturerType"/>
			<xs:element name="ManufacturerAddress" type="v1.0:ManufacturerAddressType"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="CompletedBusGeneralVehicleOutputGroup">
		<xs:sequence>
			<xs:element name="Manufacturers">
				<xs:complexType>
					<xs:sequence maxOccurs="unbounded">
						<xs:element name="Step">
							<xs:complexType>
								<xs:group ref="mrf:ManufacturerGroup"/>
								<xs:attribute name="Count" type="xs:int"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:group ref="mrf:GeneralVehicleOutputGroup"/>
			<xs:group ref="mrf:CompletedBusSequenceGroup"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="LorryGeneralVehicleOutputGroup">
		<xs:sequence>
			<xs:group ref="mrf:ManufacturerGroup"/>
			<xs:group ref="mrf:GeneralVehicleOutputGroup"/>
			<xs:element name="CO2StandardGroup" minOccurs="0">
				<xs:annotation>
					<xs:documentation>1.1.7a (Sub)group for CO2 standards</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="CorrectedActualMass" type="v1.0:VehicleCurbMassChassisType">
				<xs:annotation>
					<xs:documentation>1.1.8 Corrected actual mass [kg]</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="VocationalVehicle" type="v1.0:VocationalVehicleType">
				<xs:annotation>
					<xs:documentation>1.1.9. Vocational Vehicle</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ZeroEmissionHDV" type="v1.0:ZeroEmissionVehicleType">
				<xs:annotation>
					<xs:documentation>1.1.10. Zero emission heavy-duty vehicle</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="HybridElectricHDV" type="v1.0:HybridElectricHDVType">
				<xs:annotation>
					<xs:documentation>1.1.11 Hyprid electric heavy-duty vehicle</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="HEV-LorryVehicleOutputTypeSequenceGroup">
		<xs:sequence>
			<xs:element name="DualFuelVehicle" type="v1.0:DualFuelType">
				<xs:annotation>
					<xs:documentation>1.1.12. Dual-fuel vehicle</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:group ref="mrf:HEVVehicleSequenceGroup"/>
			<xs:element name="SleeperCab" type="v1.0:SleeperCabType">
				<xs:annotation>
					<xs:documentation>1.1.13 Sleeper cab</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="NgTankSystem" type="v1.0:NgTankSystemType"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="PEV-LorryVehicleOutputTypeSequenceGroup">
		<xs:sequence>
			<xs:element name="SleeperCab" type="v1.0:SleeperCabType">
				<xs:annotation>
					<xs:documentation>1.1.13 Sleeper cab</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="PEVArchitecture"/>
			<xs:group ref="mrf:OffVehicleChargingGroup"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="HEVVehicleSequenceGroup">
		<xs:sequence>
			<xs:element name="HEVArchitecture"/>
			<xs:group ref="mrf:OffVehicleChargingGroup"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="PEVVehicleSequenceGroup">
		<xs:sequence>
			<xs:element name="PEVArchitecture"/>
			<xs:group ref="mrf:OffVehicleChargingGroup"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="CompletedBusSequenceGroup">
		<xs:sequence>
			<xs:element name="CorrectedActualMass" type="v1.0:VehicleCurbMassChassisType"/>
			<xs:element name="ZeroEmissionHDV" type="xs:boolean"/>
			<xs:element name="HybridElectricHDV" type="xs:boolean"/>
			<xs:element name="ClassBus" type="v2.10.2:RegisteredClassType"/>
			<xs:element name="NrOfPassengersUpperDeck" type="xs:int"/>
			<xs:element name="NrOfPassengerLowerDeck" type="xs:int"/>
			<xs:element name="BodyWorkCode" type="v2.10.2:VehicleCodeType"/>
			<xs:element name="LowEntry" type="xs:boolean"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="CompletedBusVehicleDimensionSequenceGroup">
		<xs:sequence>
			<xs:element name="HeightIntegratedBody"/>
			<xs:element name="VehicleLength"/>
			<xs:element name="VehicleHeight"/>
		</xs:sequence>
	</xs:group>
	<xs:complexType name="Conventional-LorryVehicleOutputType">
		<xs:sequence>
			<xs:group ref="mrf:LorryGeneralVehicleOutputGroup"/>
			<xs:element name="DualFuelVehicle" type="v1.0:DualFuelType">
				<xs:annotation>
					<xs:documentation>1.1.12. Dual-fuel vehicle</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="SleeperCab" type="v1.0:SleeperCabType">
				<xs:annotation>
					<xs:documentation>1.1.13 Sleeper cab</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="NgTankSystem" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV-LorryVehicleOutputType">
		<xs:sequence>
			<xs:group ref="mrf:LorryGeneralVehicleOutputGroup"/>
			<xs:group ref="mrf:HEV-LorryVehicleOutputTypeSequenceGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV-LorryVehicleOutputType">
		<xs:sequence>
			<xs:group ref="mrf:LorryGeneralVehicleOutputGroup"/>
			<xs:element name="SleeperCab" type="v1.0:SleeperCabType">
				<xs:annotation>
					<xs:documentation>1.1.13 Sleeper cab</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:group ref="mrf:PEVVehicleSequenceGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Conventional-PrimaryBus-VehicleOutputType">
		<xs:sequence>
			<xs:group ref="mrf:PrimaryBusGeneralVehicleOutputGroup"/>
			<xs:sequence>
				<xs:element name="ZeroEmissionHDV" type="xs:boolean"/>
				<xs:element name="HybridElectricHDV"/>
			</xs:sequence>
			<xs:element name="DualFuelVehicle" type="xs:boolean"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV-PrimaryBus-VehicleOutputType">
		<xs:sequence>
			<xs:group ref="mrf:PrimaryBusGeneralVehicleOutputGroup"/>
			<xs:group ref="mrf:HEVVehicleSequenceGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV-PrimaryBus-VehicleOutputType">
		<xs:sequence>
			<xs:group ref="mrf:PrimaryBusGeneralVehicleOutputGroup"/>
			<xs:sequence>
				<xs:element name="ZeroEmissionHDV" type="xs:boolean"/>
				<xs:element name="HybridElectricHDV"/>
			</xs:sequence>
			<xs:group ref="mrf:PEVVehicleSequenceGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Conventional-CompletedBusVehicleOutputType">
		<xs:sequence>
			<xs:group ref="mrf:CompletedBusGeneralVehicleOutputGroup"/>
			<xs:group ref="mrf:CompletedBusVehicleDimensionSequenceGroup"/>
			<xs:element name="DoorDriveTechnology" type="v2.10.2:DoorDriveTechnologyType"/>
			<xs:element name="NgTankSystem" type="v1.0:NgTankSystemType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV-CompletedBusVehicleOutputType">
		<xs:sequence>
			<xs:group ref="mrf:CompletedBusGeneralVehicleOutputGroup"/>
			<xs:group ref="mrf:CompletedBusVehicleDimensionSequenceGroup"/>
			<xs:element name="DoorDriveTechnology" type="v2.10.2:DoorDriveTechnologyType"/>
			<xs:element name="NgTankSystem" type="v1.0:NgTankSystemType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV-CompletedBusVehicleOutputType">
		<xs:sequence>
			<xs:group ref="mrf:CompletedBusGeneralVehicleOutputGroup"/>
			<xs:group ref="mrf:CompletedBusVehicleDimensionSequenceGroup"/>
			<xs:element name="DoorDriveTechnology" type="v2.10.2:DoorDriveTechnologyType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Exempted-LorryVehicleOutputType">
		<xs:sequence>
			<xs:group ref="mrf:LorryGeneralVehicleOutputGroup"/>
			<xs:element name="VehicleTechnologyExempted" type="xs:string"/>
			<xs:element name="SumNetPower"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Exempted-PrimaryBusVehicleOutputType">
		<xs:sequence>
			<xs:group ref="mrf:PrimaryBusGeneralVehicleOutputGroup"/>
			<xs:element name="VehicleTechnologyExempted" type="xs:string"/>
			<xs:element name="SumNetPower"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Exempted-CompletedBusVehicleOutputType">
		<xs:sequence>
			<xs:group ref="mrf:CompletedBusGeneralVehicleOutputGroup"/>
		</xs:sequence>
	</xs:complexType>
	<!--Auxiliaries-->
	<xs:complexType name="ConventionalLorryAuxOutputType">
		<xs:sequence>
			<xs:element name="CoolingFanTechnology"/>
			<xs:element name="SteeringPumpTechnology" type="v1.0:AuxSPTechnologyType"/>
			<xs:element name="ElectricSystem">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="LEDHeadLights" type="xs:boolean"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="PneumaticSystem">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Technology" type="v1.0:AuxSPTechnologyType"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEVLorryAuxOutputType"/>
	<xs:complexType name="PEVLorryAuxOutputType"/>
	<xs:complexType name="ConventionPrimaryBusAuxOutputType"/>
	<xs:complexType name="HEVPrimaryBusAuxOutputType"/>
	<xs:complexType name="PEVPrimaryBusAuxOutputType"/>
	<xs:complexType name="ConventionalCompletedBusAuxOutputType"/>
	<xs:complexType name="HEVCompletedBusAuxOutputType"/>
	<xs:complexType name="PEVCompletedBusAuxOutputType"/>
	<xs:group name="PrimaryBusElectricSystemGroup">
		<xs:sequence>
			<xs:element name="AlternatorTechnology" type="v2.10.2:AlternatorTechnologyType"/>
			<xs:element name="MaxAlternatorPower" type="mrf:PowerType" minOccurs="0"/>
			<xs:element name="ElectricStorageCapacity" type="mrf:StorageCapacityType" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="CompletedBusElectricSystemGroup">
		<xs:sequence>
			<xs:element name="DayRunningLightsLED" type="xs:boolean"/>
			<xs:element name="HeadLightsLED" type="xs:boolean"/>
			<xs:element name="PositionLightsLED" type="xs:boolean"/>
			<xs:element name="BrakeLightsLED" type="xs:boolean"/>
			<xs:element name="InteriorLightsLED" type="xs:boolean"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="LorryPneumaticSystemGroup">
		<xs:sequence>
			<xs:element name="Technology" type="v1.0:AuxPSTechnologyType"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="PrimaryBusPneumaticSystemGroup">
		<xs:sequence>
			<xs:element name="Technology" type="v1.0:AuxPSTechnologyType"/>
			<xs:element name="CompressorRatio" type="v1.0:Double3"/>
			<xs:element name="SmartCompressionSystem" type="xs:boolean"/>
			<xs:element name="SmartRegenerationSystem" type="xs:boolean"/>
			<xs:element name="AirSuspensionControl" type="v2.10.2:AirsuspensionControlType"/>
			<xs:element name="ReagentDosing" type="xs:boolean"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="xEVHVACGroup">
		<xs:sequence>
			<xs:group ref="mrf:HVACSystemGroup"/>
			<xs:element name="WaterElectricHeater" type="xs:boolean"/>
			<xs:element name="AirElectricHeater" type="xs:boolean"/>
			<xs:element name="OtherHeatingTechnology" type="xs:boolean"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="HVACSystemGroup">
		<xs:sequence>
			<xs:group ref="v2.10.2:BusAuxHVACHeatPumpSequenceGroup"/>
			<xs:element name="DoubleGlasing" type="xs:boolean"/>
			<xs:element name="AdjustableAuxiliaryHeater" type="xs:boolean"/>
		</xs:sequence>
	</xs:group>
	<!--ADAS-->
	<xs:group name="ConventionalADASGroup">
		<xs:sequence>
			<xs:element name="EngineStopStart" type="xs:boolean"/>
			<xs:element name="EcoRollWithoutEngineStopStart" type="xs:boolean"/>
			<xs:element name="EcoRollWithEngineStopStart" type="xs:boolean"/>
			<xs:element name="PredictiveCruiseControl" type="xs:boolean"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="HEVADASGroup">
		<xs:sequence>
			<xs:element name="EngineStopStart" type="xs:boolean"/>
			<xs:element name="PredictiveCruiseControl" type="xs:boolean"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="PEVADASGroup">
		<xs:sequence>
			<xs:element name="PredictiveCruiseControl" type="xs:boolean"/>
		</xs:sequence>
	</xs:group>
	<!--ElectricMachine_IEPC-->
	<xs:group name="ElectricMachineGroup">
		<xs:sequence>
			<xs:group ref="mrf:ComponentCommonOutputGroup"/>
			<xs:element name="ElectricMachineType"/>
			<xs:element name="Position"/>
			<xs:element name="CoupledAxleNumber"/>
			<xs:element name="CountAtPosition"/>
			<xs:element name="CertificationMethod" type="v2.10.1:CertificationMethodType"/>
			<xs:element name="ADC">
				<xs:complexType>
					<xs:sequence>
						<xs:group ref="mrf:ComponentCommonOutputGroup"/>
						<xs:element name="CertificationMethod" type="v2.10.1:CertificationMethodType"/>
						<xs:element name="Ratio"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="ElectricMachinePowerGroup">
		<xs:sequence>
			<xs:element name="RatedPower"/>
			<xs:element name="MaxContinuousPower"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="IEPCGroup">
		<xs:sequence>
			<xs:group ref="mrf:ComponentCommonOutputGroup"/>
			<xs:group ref="mrf:ElectricMachinePowerGroup"/>
			<xs:element name="NrOfGears" type="xs:int"/>
			<xs:element name="LowestTotalTransmissionRatio"/>
			<xs:element name="DifferentialIncluded" type="xs:boolean"/>
			<xs:element name="CertificationMethod" type="v2.10.1:CertificationMethodType"/>
		</xs:sequence>
	</xs:group>
	<!--REESS-->
	<xs:group name="EngineTorqueLimitationsGroup">
		<xs:sequence>
			<xs:element name="EngineTorqueLimit" maxOccurs="unbounded">
				<xs:complexType>
					<xs:attribute name="Gear" type="xs:int"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="REESSGroup">
		<xs:sequence>
			<xs:group ref="mrf:ComponentCommonOutputGroup"/>
			<xs:element name="NominalVoltage"/>
			<xs:element name="TotalStorageCapacitiy"/>
			<xs:element name="TotalUsableCapacityInSimulation"/>
			<xs:element name="CertificationMethod"/>
			<xs:element name="StringID" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<!--Axles-->
	<xs:complexType name="TyresOutputType">
		<xs:sequence>
			<xs:sequence minOccurs="2" maxOccurs="unbounded">
				<xs:element name="Tyre">
					<xs:complexType>
						<xs:group ref="mrf:TyreGroup"/>
						<xs:attribute name="axleCount" type="xs:int"/>
					</xs:complexType>
				</xs:element>
				<xs:element name="TwinAxle" type="xs:boolean" minOccurs="0"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:group name="TyreGroup">
		<xs:sequence>
			<xs:element name="TyreDimension" type="v2.3:TyreDimensionType"/>
			<xs:element name="CertificationNumber" type="v1.0:CertificationNumberType"/>
			<xs:element name="SpecificRRC" type="v1.0:TyreRRCISOType"/>
			<xs:element name="DigestValue" type="xs:token"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="AxleGroup">
		<xs:sequence>
			<xs:group ref="mrf:ComponentCommonOutputGroup"/>
			<xs:element name="CertificationMethod" type="v1.0:AxlegearCertificationOptionType"/>
			<xs:element name="AxleType" type="v1.0:AxleTypeType"/>
			<xs:element name="AxleRatio" type="v1.0:AxlegearRatioType"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="AngledriveGroup">
		<xs:sequence>
			<xs:group ref="mrf:ComponentCommonOutputGroup"/>
			<xs:element name="CertificationMethod" type="v1.0:AngledriveCertificationOptionType"/>
			<xs:element name="AngledriveRatio" type="v1.0:AngledriveRatioType"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="AerodynamicsGroup">
		<xs:sequence>
			<xs:element name="Model" type="v1.0:ModelType"/>
			<xs:element name="CertificationMethod" type="v2.10.1:CertificationMethodType"/>
			<xs:element name="CertificationNumber" type="v1.0:CertificationNumberType" minOccurs="0"/>
			<xs:element name="CdxA" type="v1.0:AirdragCdxAType"/>
			<xs:element name="DigestValue" type="xs:token"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="PrimaryBusGeneralVehicleOutputGroup">
		<xs:sequence>
			<xs:group ref="mrf:ManufacturerGroup"/>
			<xs:group ref="mrf:GeneralVehicleOutputGroup"/>
			<xs:sequence>
				<xs:element name="ZeroEmissionHDV" type="xs:boolean"/>
				<xs:element name="HybridElectricHDV"/>
			</xs:sequence>
			<xs:element name="DualFuelVehicle" type="xs:boolean"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="TorqueConverterGroup">
		<xs:sequence>
			<xs:group ref="mrf:ComponentCommonOutputGroup"/>
			<xs:element name="CertificationMethod" type="v2.10.1:CertificationMethodType"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="RetarderGroup">
		<xs:sequence>
			<xs:group ref="mrf:ComponentCommonOutputGroup"/>
			<xs:element name="CertificationMethod" type="v2.10.1:CertificationMethodType"/>
		</xs:sequence>
	</xs:group>
	<xs:complexType name="TransmissionType">
		<xs:sequence>
			<xs:group ref="mrf:ComponentCommonOutputGroup"/>
			<xs:element name="Type" type="v1.0:GearboxTransmissionTypeType"/>
			<xs:element name="NrOfGears" type="xs:int"/>
			<xs:element name="FinalGearRatio" type="v1.0:GearboxGearRatioType"/>
			<xs:element name="RetarderType" type="v1.0:RetarderTypeType"/>
			<xs:element name="PowerTakeOff" type="xs:boolean" minOccurs="0"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EngineOutputType">
		<xs:sequence>
			<xs:group ref="mrf:ComponentCommonOutputGroup"/>
			<xs:element name="RatedPower" type="v1.0:EngineRatedPower"/>
			<xs:element name="IdlingSpeed" type="v1.0:EngineDeclaredSpeedType"/>
			<xs:element name="RatedSpeed" type="v1.0:EngineDeclaredSpeedType"/>
			<xs:element name="FuelTypes">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="FuelType" type="v1.0:FuelTypeType" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="WasteHeatRecoverySystem" type="xs:boolean"/>
			<xs:element name="WastHeatRecoverySystemType" type="xs:string" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:group name="ComponentCommonOutputGroup">
		<xs:sequence>
			<xs:element name="Model" type="v1.0:ModelType"/>
			<xs:element name="CertificationNumber" type="v1.0:CertificationNumberType"/>
			<xs:element name="DigestValue" type="xs:token" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:complexType name="EngineCapacityType">
		<xs:simpleContent>
			<xs:extension base="xs:double"/>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="AlternatorTechnologyType"/>
	<xs:simpleType name="PowerType">
		<xs:restriction base="xs:double"/>
	</xs:simpleType>
	<xs:simpleType name="StorageCapacityType">
		<xs:restriction base="xs:double"/>
	</xs:simpleType>
</xs:schema>
