<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2021 (x64) (http://www.altova.com) by Franz Kober (Technische Universität Graz) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:vectoParam="urn:tugraz:ivt:VectoAPI:ParameterDocumentation" xmlns:di="http://www.w3.org/2000/09/xmldsig#" xmlns:v2.0="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.0" xmlns:v2.1="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.1" xmlns:v2.3="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.3" xmlns:v2.4="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.4" xmlns:v2.8="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.8" xmlns:v1.0="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v1.0" xmlns:v2.6="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.6" targetNamespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.8" elementFormDefault="qualified" attributeFormDefault="unqualified" xsi:schemaLocation="urn:tugraz:ivt:VectoAPI:ParameterDocumentation ParameterDocumentation.xsd">
	<xs:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v1.0" schemaLocation="VectoDeclarationDefinitions.1.0.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.0" schemaLocation="VectoDeclarationDefinitions.2.0.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.1" schemaLocation="VectoDeclarationDefinitions.2.1.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.3" schemaLocation="VectoDeclarationDefinitions.2.3_DEV.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.6" schemaLocation="VectoDeclarationDefinitions.2.6_Buses.xsd"/>
	<xs:complexType name="AbstractCompletedVehicleAuxiliaryDataDeclarationType" abstract="true"/>
	<xs:complexType name="AbstractCompletedVehicleComponentsDeclarationType" abstract="true"/>
	<xs:complexType name="CompletedVehicleComponentsDeclarationType">
		<xs:complexContent>
			<xs:extension base="v2.8:AbstractCompletedVehicleComponentsDeclarationType">
				<xs:sequence>
					<xs:element name="AirDrag" type="v2.0:AirDragComponentDeclarationType" minOccurs="0"/>
					<xs:element name="Auxiliaries" type="v2.8:CompletedVehicleAuxiliariesComponentDeclarationType"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="CompletedVehicleAuxiliariesComponentDeclarationType">
		<xs:sequence>
			<xs:element name="Data" type="v2.8:AbstractCompletedVehicleAuxiliaryDataDeclarationType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="CompletedVehicleAuxiliaryDataDeclarationType">
		<xs:complexContent>
			<xs:extension base="v2.8:AbstractCompletedVehicleAuxiliaryDataDeclarationType">
				<xs:sequence minOccurs="0">
					<xs:element name="ElectricSystem" minOccurs="0">
						<xs:complexType>
							<xs:sequence minOccurs="0">
								<xs:element name="LEDLights" minOccurs="0">
									<xs:complexType>
										<xs:sequence minOccurs="0">
											<xs:element name="Interiorlights" type="xs:boolean" minOccurs="0">
												<xs:annotation>
													<xs:documentation>P304 - bool</xs:documentation>
												</xs:annotation>
											</xs:element>
											<xs:element name="Dayrunninglights" type="xs:boolean" minOccurs="0">
												<xs:annotation>
													<xs:documentation>P305 - bool</xs:documentation>
												</xs:annotation>
											</xs:element>
											<xs:element name="Positionlights" type="xs:boolean" minOccurs="0">
												<xs:annotation>
													<xs:documentation>P306 - bool</xs:documentation>
												</xs:annotation>
											</xs:element>
											<xs:element name="Brakelights" type="xs:boolean" minOccurs="0">
												<xs:annotation>
													<xs:documentation>P307 - bool</xs:documentation>
												</xs:annotation>
											</xs:element>
											<xs:element name="Headlights" type="xs:boolean" minOccurs="0">
												<xs:annotation>
													<xs:documentation>P308 - bool</xs:documentation>
												</xs:annotation>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<xs:element name="HVAC" minOccurs="0">
						<xs:complexType>
							<xs:sequence minOccurs="0">
								<xs:sequence minOccurs="0">
									<xs:element name="SystemConfiguration">
										<xs:annotation>
											<xs:documentation>P317 - int</xs:documentation>
										</xs:annotation>
										<xs:simpleType>
											<xs:restriction base="xs:int">
												<xs:minInclusive value="0"/>
												<xs:maxInclusive value="10"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:element>
									<xs:element name="HeatPumpTypeDriverCompartment" type="v2.8:HVACHeatPumpType">
										<xs:annotation>
											<xs:documentation>P318 - enum</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="HeatPumpModeDriverCompartment" type="v2.8:HVACHeatPumpModeType">
										<xs:annotation>
											<xs:documentation>P319 - enum</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="HeatPumpTypePassengerCompartment" type="v2.8:HVACHeatPumpType">
										<xs:annotation>
											<xs:documentation>P320 - enum</xs:documentation>
										</xs:annotation>
									</xs:element>
									<xs:element name="HeatPumpModePassengerCompartment" type="v2.8:HVACHeatPumpModeType">
										<xs:annotation>
											<xs:documentation>P321 - enum</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
								<xs:element name="AuxiliaryHeaterPower" minOccurs="0">
									<xs:annotation>
										<xs:documentation>P322 - [W]</xs:documentation>
									</xs:annotation>
									<xs:simpleType>
										<xs:restriction base="xs:int">
											<xs:minInclusive value="0"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:element>
								<xs:element name="DoubleGlasing" type="xs:boolean" minOccurs="0">
									<xs:annotation>
										<xs:documentation>P323 - bool</xs:documentation>
									</xs:annotation>
								</xs:element>
								<xs:element name="AdjustableAuxiliaryHeater" type="xs:boolean" minOccurs="0">
									<xs:annotation>
										<xs:documentation>P325 - bool</xs:documentation>
									</xs:annotation>
								</xs:element>
								<xs:element name="SeparateAirDistributionDucts" type="xs:boolean" minOccurs="0">
									<xs:annotation>
										<xs:documentation>P327 - bool</xs:documentation>
									</xs:annotation>
								</xs:element>
								<xs:element name="WaterElectricHeater" type="xs:boolean" minOccurs="0">
									<xs:annotation>
										<xs:documentation>P328 - bool</xs:documentation>
									</xs:annotation>
								</xs:element>
								<xs:element name="AirElectricHeater" type="xs:boolean" minOccurs="0">
									<xs:annotation>
										<xs:documentation>P329 - bool</xs:documentation>
									</xs:annotation>
								</xs:element>
								<xs:element name="OtherHeatingTechnology" type="xs:boolean" minOccurs="0">
									<xs:annotation>
										<xs:documentation>P330 - bool</xs:documentation>
									</xs:annotation>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ExemptedVectoStageInputType">
		<xs:annotation>
			<xs:documentation>Exempted vehicle stage input parts</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="v2.8:AbstractCompletedBusVehicleType">
				<xs:sequence>
					<xs:element name="Manufacturer" type="v1.0:ManufacturerType">
						<xs:annotation>
							<xs:documentation>P235</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="ManufacturerAddress" type="v1.0:ManufacturerAddressType">
						<xs:annotation>
							<xs:documentation>P252</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="VIN" type="v1.0:VINType">
						<xs:annotation>
							<xs:documentation>P238</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="Date" type="v1.0:DateTimeWithTimezone">
						<xs:annotation>
							<xs:documentation>P239</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="Model" type="v1.0:ModelType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P236</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="LegislativeCategory" type="v2.8:LegislativeClassDeclarationType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P251 - enum</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="CorrectedActualMass" type="v1.0:VehicleCurbMassChassisType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P038 - [kg]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="TechniclaPermissibleMaximumLadenMass" type="v1.0:VehicleGrossVehicleMassType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P041 - [kg]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="ClassBus" type="v2.6:RegisteredClassType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P282 - enum</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:sequence minOccurs="0">
						<xs:element name="NumberPassengersLowerDeck" type="v2.8:NumberOfPassengersType">
							<xs:annotation>
								<xs:documentation>P283 - [-]</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="NumberPassengersUpperDeck" type="v2.8:NumberOfPassengersType">
							<xs:annotation>
								<xs:documentation>P284 - [-]</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
					<xs:element name="VehicleCode" type="v2.6:VehicleCodeType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P285 - enum</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="LowEntry" type="xs:boolean" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P286 - bool</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="HeightIntegratedBody" type="v2.8:VehicleDimensionType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P287 - [mm]</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="VectoStageInputType">
		<xs:annotation>
			<xs:documentation>Vehicle stage input parts</xs:documentation>
		</xs:annotation>
		<xs:complexContent>
			<xs:extension base="v2.8:AbstractCompletedBusVehicleType">
				<xs:sequence>
					<xs:element name="Manufacturer" type="v1.0:ManufacturerType">
						<xs:annotation>
							<xs:documentation>P235</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="ManufacturerAddress" type="v1.0:ManufacturerAddressType">
						<xs:annotation>
							<xs:documentation>P252</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="VIN" type="v1.0:VINType">
						<xs:annotation>
							<xs:documentation>P238</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="Date" type="v1.0:DateTimeWithTimezone">
						<xs:annotation>
							<xs:documentation>P239</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="Model" type="v1.0:ModelType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P236</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="LegislativeCategory" type="v2.8:LegislativeClassDeclarationType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P251 - enum</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="CorrectedActualMass" type="v1.0:VehicleCurbMassChassisType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P038 - [kg]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="TechniclaPermissibleMaximumLadenMass" type="v1.0:VehicleGrossVehicleMassType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P041 - [kg]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="AirdragModifiedMultistage" type="v2.8:AirdragModifiedMultistageType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P334 - bool</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="NgTankSystem" type="v1.0:NgTankSystemType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P275 - enum</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="ClassBus" type="v2.6:RegisteredClassType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P282 - enum</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:sequence minOccurs="0">
						<xs:element name="NumberPassengersLowerDeck" type="v2.8:NumberOfPassengersType">
							<xs:annotation>
								<xs:documentation>P283 - [-]</xs:documentation>
							</xs:annotation>
						</xs:element>
						<xs:element name="NumberPassengersUpperDeck" type="v2.8:NumberOfPassengersType">
							<xs:annotation>
								<xs:documentation>P284 - [-]</xs:documentation>
							</xs:annotation>
						</xs:element>
					</xs:sequence>
					<xs:element name="VehicleCode" type="v2.6:VehicleCodeType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P285 - enum</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="LowEntry" type="xs:boolean" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P286 - bool</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="HeightIntegratedBody" type="v2.8:VehicleDimensionType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P287 - [mm]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="VehicleLength" type="v2.8:VehicleDimensionType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P288 - [mm]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="VehicleWidth" type="v2.8:VehicleDimensionType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P289 - [mm]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="EntranceHeight" type="v2.8:VehicleDimensionType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P290 - [mm]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="DoorDriveTechnology" type="v2.6:DoorDriveTechnologyType" minOccurs="0">
						<xs:annotation>
							<xs:documentation>P291 - enum</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="StateOfCompletion" type="v2.8:StateOfCompletionType">
						<xs:annotation>
							<xs:documentation>P293 - enum</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="ADAS" type="v2.3:AdvancedDriverAssistantSystemsType" minOccurs="0"/>
					<xs:element name="Components" type="v2.8:AbstractCompletedVehicleComponentsDeclarationType" minOccurs="0"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:simpleType name="LegislativeClassDeclarationType">
		<xs:annotation>
			<xs:appinfo>
				<vectoParam:description>
					<vectoParam:parameterId component="Vehicle">251</vectoParam:parameterId>
					<vectoParam:unit>-</vectoParam:unit>
				</vectoParam:description>
			</xs:appinfo>
			<xs:documentation>P251 - enum</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="M3"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="AirdragModifiedMultistageType">
		<xs:annotation>
			<xs:appinfo>
				<vectoParam:description>
					<vectoParam:parameterId component="Vehicle">334</vectoParam:parameterId>
					<vectoParam:unit>-</vectoParam:unit>
				</vectoParam:description>
			</xs:appinfo>
			<xs:documentation>P334 - [-]</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:boolean"/>
	</xs:simpleType>
	<xs:simpleType name="NumberOfPassengersType">
		<xs:annotation>
			<xs:appinfo>
				<vectoParam:description>
					<vectoParam:parameterId component="Vehicle">283</vectoParam:parameterId>
					<vectoParam:parameterId component="Vehicle">284</vectoParam:parameterId>
					<vectoParam:unit>-</vectoParam:unit>
				</vectoParam:description>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:int">
			<xs:minInclusive value="0"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="VehicleDimensionType">
		<xs:annotation>
			<xs:appinfo>
				<vectoParam:description>
					<vectoParam:parameterId component="Vehicle">287</vectoParam:parameterId>
					<vectoParam:parameterId component="Vehicle">288</vectoParam:parameterId>
					<vectoParam:parameterId component="Vehicle">289</vectoParam:parameterId>
					<vectoParam:parameterId component="Vehicle">290</vectoParam:parameterId>
					<vectoParam:unit>mm</vectoParam:unit>
				</vectoParam:description>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:int"/>
	</xs:simpleType>
	<xs:simpleType name="StateOfCompletionType">
		<xs:annotation>
			<xs:appinfo>
				<vectoParam:description>
					<vectoParam:parameterId component="Vehicle">293</vectoParam:parameterId>
					<vectoParam:unit>-</vectoParam:unit>
				</vectoParam:description>
			</xs:appinfo>
			<xs:documentation>P293 - enum</xs:documentation>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="incomplete"/>
			<xs:enumeration value="complete"/>
			<xs:enumeration value="completed"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="HVACHeatPumpModeType">
		<xs:annotation>
			<xs:appinfo>
				<vectoParam:description>
					<vectoParam:parameterId component="Vehicle/Auxiliaries">319</vectoParam:parameterId>
					<vectoParam:parameterId component="Vehicle/Auxiliaries">321</vectoParam:parameterId>
					<vectoParam:unit>-</vectoParam:unit>
				</vectoParam:description>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="heating"/>
			<xs:enumeration value="heating and cooling"/>
			<xs:enumeration value="cooling"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="HVACHeatPumpType">
		<xs:annotation>
			<xs:appinfo>
				<vectoParam:description>
					<vectoParam:parameterId component="Vehicle/Auxiliaries">318</vectoParam:parameterId>
					<vectoParam:parameterId component="Vehicle/Auxiliaries">320</vectoParam:parameterId>
					<vectoParam:unit>-</vectoParam:unit>
				</vectoParam:description>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="none"/>
			<xs:enumeration value="R-744"/>
			<xs:enumeration value="non R-744 2-stage"/>
			<xs:enumeration value="non R-744 3-stage"/>
			<xs:enumeration value="non R-744 4-stage"/>
			<xs:enumeration value="non R-744 continuous"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="AirDragModifiedUseStandardValueType">
		<xs:complexContent>
			<xs:extension base="v1.0:AbstractAirdragDataDeclarationType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="AbstractCompletedBusVehicleType" abstract="true">
		<xs:complexContent>
			<xs:extension base="v2.0:AbstractVehicleDeclarationType"/>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>
