<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com) by Helmut Eichlseder (TU Graz/Inst. f. VKM und THD) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:tugraz:ivt:VectoAPI:CustomerOutput:v0.9" xmlns:out="urn:tugraz:ivt:VectoAPI:DeclarationOutputDefinitions" xmlns:mrf="urn:tugraz:ivt:VectoAPI:DeclarationOutput:v0.9" xmlns:dd="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions" xmlns:v2.0="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.0" xmlns:v1.0="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v1.0" xmlns:v2.1="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.1" xmlns:v2.3="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.3" xmlns:v2.4="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.4" targetNamespace="urn:tugraz:ivt:VectoAPI:CustomerOutput:v0.9" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v1.0" schemaLocation="VectoDeclarationDefinitions.1.0.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.0" schemaLocation="VectoDeclarationDefinitions.2.0.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.1" schemaLocation="VectoDeclarationDefinitions.2.1.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.3" schemaLocation="VectoDeclarationDefinitions.2.3.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.4" schemaLocation="VectoDeclarationDefinitions.2.4.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions" schemaLocation="VectoDeclarationDefinitions.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationOutput:v0.9" schemaLocation="VectoOutputManufacturer.0.9.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationOutputDefinitions" schemaLocation="VectoOutputDefinitions.xsd"/>
	<xs:element name="VectoOutput">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="AbstractVectoCustomerOutputType"/>
	<xs:complexType name="ConventionalLorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="Conventional_LorryVehicleType"/>
			<xs:element name="Results" type="ResultsType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_Px_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="HEV_Px_IHPC_LorryVehicleType"/>
			<xs:element name="Results" type="ResultsType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_S2_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="HEV_S2_LorryVehicleType"/>
			<xs:element name="Results" type="ResultsType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_S3_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="HEV_S3_LorryVehicleType"/>
			<xs:element name="Results" type="ResultsType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_S4_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="HEV_S4_LorryVehicleType"/>
			<xs:element name="Results" type="ResultsType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_IEPC_S_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="HEV_IEPC_S_LorryVehicleType"/>
			<xs:element name="Results" type="ResultsType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_E2_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="PEV_E2_LorryVehicleType"/>
			<xs:element name="Results" type="ResultsType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_E3_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="PEV_E3_LorryVehicleType"/>
			<xs:element name="Results" type="ResultsType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_E4_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="PEV_E4_LorryVehicleType"/>
			<xs:element name="Results" type="ResultsType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_IEPC_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="PEV_IEPC_LorryVehicleType"/>
			<xs:element name="Results" type="ResultsType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Conventional_CompletedBusOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="Conventional_CompletedBusVehicleType"/>
			<xs:element name="Results" type="ResultsType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_CompletedBusOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="HEV_CompletedBusVehicleType"/>
			<xs:element name="Results" type="ResultsType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_CompletedBusOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="PEV_CompletedBusVehicleType"/>
			<xs:element name="Results" type="ResultsType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Exempted_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="Exempted_LorryVehicleType"/>
			<xs:element name="Results" type="ResultsType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Exempted_CompletedBusOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="Exempted_CompletedBusVehicleType"/>
			<xs:element name="Results" type="ResultsType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Conventional_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="GeneralVehicleSequenceGroup"/>
			<xs:group ref="LorryGeneralVehicleSequenceGroup"/>
			<xs:group ref="Conventional_LorryVehicleSequenceGroup"/>
			<xs:element name="ADAS" type="mrf:ConventionalADASType"/>
			<xs:group ref="EngineGroup"/>
			<xs:group ref="TransmissionGroup"/>
			<xs:element name="Retarder" type="xs:boolean"/>
			<xs:element name="AxleRatio" type="v1.0:AxlegearRatioType"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:group ref="LorryAuxGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_Px_IHPC_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="HEV_LorryVehicleTypeGroup"/>
			<xs:element name="ADAS" type="mrf:HEVADASType"/>
			<xs:group ref="EngineGroup"/>
			<xs:group ref="ElectricMachineGroup"/>
			<xs:group ref="REESSGroup"/>
			<xs:group ref="TransmissionGroup"/>
			<xs:element name="Retarder" type="xs:boolean"/>
			<xs:element name="AxleRatio" type="v1.0:AxlegearRatioType"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:group ref="LorryAuxGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_S2_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="HEV_LorryVehicleTypeGroup"/>
			<xs:element name="ADAS" type="mrf:HEVADASType"/>
			<xs:group ref="EngineGroup"/>
			<xs:group ref="ElectricMachineGroup"/>
			<xs:group ref="REESSGroup"/>
			<xs:group ref="TransmissionGroup"/>
			<xs:element name="Retarder"/>
			<xs:element name="AxleRatio"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:group ref="LorryAuxGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_S3_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="HEV_LorryVehicleTypeGroup"/>
			<xs:element name="ADAS" type="mrf:HEVADASType"/>
			<xs:group ref="EngineGroup"/>
			<xs:group ref="ElectricMachineGroup"/>
			<xs:group ref="REESSGroup"/>
			<xs:element name="Retarder"/>
			<xs:element name="AxleRatio"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:group ref="LorryAuxGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_S4_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="HEV_LorryVehicleTypeGroup"/>
			<xs:element name="ADAS" type="mrf:HEVADASType"/>
			<xs:group ref="EngineGroup"/>
			<xs:group ref="ElectricMachineGroup"/>
			<xs:group ref="REESSGroup"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:group ref="LorryAuxGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_IEPC_S_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="HEV_LorryVehicleTypeGroup"/>
			<xs:element name="ADAS" type="mrf:HEVADASType"/>
			<xs:group ref="EngineGroup"/>
			<xs:group ref="ElectricMachineGroup"/>
			<xs:group ref="REESSGroup"/>
			<xs:element name="Retarder"/>
			<xs:element name="AxleRatio" minOccurs="0"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:group ref="LorryAuxGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_E2_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="PEV_LorryVehicleTypeGroup"/>
			<xs:element name="ADAS" type="mrf:PEVADASType"/>
			<xs:group ref="ElectricMachineGroup"/>
			<xs:group ref="REESSGroup"/>
			<xs:group ref="TransmissionGroup"/>
			<xs:element name="Retarder"/>
			<xs:element name="AxleRatio"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:group ref="LorryAuxGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_E3_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="PEV_LorryVehicleTypeGroup"/>
			<xs:element name="ADAS" type="mrf:PEVADASType"/>
			<xs:group ref="ElectricMachineGroup"/>
			<xs:group ref="REESSGroup"/>
			<xs:element name="Retarder"/>
			<xs:element name="AxleRatio"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:group ref="LorryAuxGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_E4_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="PEV_LorryVehicleTypeGroup"/>
			<xs:element name="ADAS" type="mrf:PEVADASType"/>
			<xs:group ref="ElectricMachineGroup"/>
			<xs:group ref="REESSGroup"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:group ref="LorryAuxGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_IEPC_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="PEV_LorryVehicleTypeGroup"/>
			<xs:element name="ADAS" type="mrf:PEVADASType"/>
			<xs:group ref="ElectricMachineGroup"/>
			<xs:group ref="REESSGroup"/>
			<xs:element name="Retarder"/>
			<xs:element name="AxleRatio" minOccurs="0"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:group ref="LorryAuxGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Conventional_CompletedBusVehicleType">
		<xs:sequence>
			<xs:group ref="CompletedBusVehicleTypeGroup"/>
			<xs:element name="ADAS" type="mrf:ConventionalADASType"/>
			<xs:group ref="CompletedBusAuxGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_CompletedBusVehicleType">
		<xs:sequence>
			<xs:group ref="CompletedBusVehicleTypeGroup"/>
			<xs:element name="ADAS" type="mrf:HEVADASType"/>
			<xs:group ref="CompletedBusAuxGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_CompletedBusVehicleType">
		<xs:sequence>
			<xs:group ref="CompletedBusVehicleTypeGroup"/>
			<xs:element name="ADAS" type="mrf:PEVADASType"/>
			<xs:group ref="CompletedBusAuxGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Exempted_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="GeneralVehicleSequenceGroup"/>
			<xs:element name="VehicleGroupCO2"/>
			<xs:element name="Manufacturer"/>
			<xs:element name="ManufacturerAddress"/>
			<xs:element name="Model"/>
			<xs:element name="CorrectedActualMass"/>
			<xs:element name="SleeperCab"/>
			<xs:element name="ZeroEmissionVehicle"/>
			<xs:element name="HybridElectricHDV"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Exempted_CompletedBusVehicleType">
		<xs:sequence>
			<xs:group ref="GeneralVehicleSequenceGroup"/>
			<xs:sequence>
				<xs:element name="Manufacturers">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="Step">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Manufacturer"/>
										<xs:element name="ManufacturerAddress"/>
									</xs:sequence>
									<xs:attribute name="stepCount" type="xs:int"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:sequence>
				<xs:element name="CorrectedActualMass"/>
				<xs:element name="ZeroEmissionVehicle"/>
				<xs:element name="HybridElectricHDV"/>
				<xs:element name="ClassBus"/>
				<xs:element name="TotalNumberOfPassengers"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:group name="GeneralVehicleSequenceGroup">
		<xs:sequence>
			<xs:element name="VIN" type="v1.0:VINType"/>
			<xs:element name="VehicleCategory" type="mrf:LegislativeCategoryType"/>
			<xs:element name="AxleConfiguration" type="v1.0:VehicleAxleConfigurationDeclarationType"/>
			<xs:element name="TechnicalPermissibleMaximumLadenMass">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="v1.0:VehicleGrossVehicleMassType">
							<xs:attribute name="unit" type="out:MassUnitType" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="VehicleGroup" type="xs:string"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="LorryGeneralVehicleSequenceGroup">
		<xs:sequence>
			<xs:element name="VehicleGroupCO2"/>
			<xs:element name="Manufacturer" type="v1.0:ManufacturerType"/>
			<xs:element name="ManufacturerAddress" type="v1.0:ManufacturerAddressType"/>
			<xs:element name="Model" type="v1.0:ModelType"/>
			<xs:element name="VehicleTypeApprovalNumber" type="v2.4:VehicleTypeApprovalNumberType"/>
			<xs:element name="CorrectedActualMass">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="v1.0:VehicleCurbMassChassisType">
							<xs:attribute name="unit" type="out:MassUnitType" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="VocationalVehicle" type="v1.0:VocationalVehicleType"/>
			<xs:element name="SleeperCab" type="v1.0:SleeperCabType"/>
			<xs:element name="ZeroEmissionVehicle" type="v1.0:ZeroEmissionVehicleType"/>
			<xs:element name="HybridElectricHDV" type="v1.0:HybridElectricHDVType"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="Conventional_LorryVehicleSequenceGroup">
		<xs:sequence>
			<xs:element name="WasteHeatRecovery" type="xs:boolean"/>
			<xs:element name="DualFuelVehicle" type="xs:boolean"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="HEV_VehicleSequenceGroup">
		<xs:sequence>
			<xs:group ref="Conventional_LorryVehicleSequenceGroup"/>
			<xs:element name="HEVArchitecture"/>
			<xs:element name="OffVehicleChargingCapability" type="xs:boolean"/>
			<xs:element name="OffVehicleChargingMaxPower" minOccurs="0">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:int">
							<xs:attribute name="unit" type="out:PowerUnitType" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="PEV_VehicleSequenceGroup">
		<xs:sequence>
			<xs:element name="PEVArchitecture"/>
			<xs:element name="OffVehicleChargingCapability"/>
			<xs:element name="OffVehicleChargingMaxPower" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="HEV_LorryVehicleTypeGroup">
		<xs:sequence>
			<xs:group ref="GeneralVehicleSequenceGroup"/>
			<xs:group ref="LorryGeneralVehicleSequenceGroup"/>
			<xs:group ref="HEV_VehicleSequenceGroup"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="PEV_LorryVehicleTypeGroup">
		<xs:sequence>
			<xs:group ref="GeneralVehicleSequenceGroup"/>
			<xs:group ref="LorryGeneralVehicleSequenceGroup"/>
			<xs:group ref="PEV_VehicleSequenceGroup"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="CompletedBusVehicleTypeGroup">
		<xs:sequence>
			<xs:group ref="GeneralVehicleSequenceGroup"/>
			<xs:sequence>
				<xs:element name="Manufacturers">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="Step">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Manufacturer"/>
										<xs:element name="ManufacturerAddress"/>
									</xs:sequence>
									<xs:attribute name="stepCount" type="xs:int"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:sequence>
				<xs:element name="CorrectedActualMass"/>
				<xs:element name="ZeroEmissionVehicle"/>
				<xs:element name="HybridElectricHDV"/>
				<xs:element name="ClassBus"/>
				<xs:element name="TotalNumberOfPassengers"/>
				<xs:element name="VehicleTypeApprovalNumber"/>
			</xs:sequence>
		</xs:sequence>
	</xs:group>
	<xs:group name="EngineGroup">
		<xs:sequence>
			<xs:element name="EngineRatedPower">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="v1.0:EngineRatedPower">
							<xs:attribute name="unit" type="out:PowerUnitType" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="EngineCapacity">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="mrf:EngineCapacityType">
							<xs:attribute name="unit" type="out:VolumeUnitType" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="FuelTypes">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="FuelType" type="v1.0:FuelTypeType" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="TransmissionGroup">
		<xs:sequence>
			<xs:element name="TransmissionValues"/>
			<xs:element name="TransmissionType" type="v1.0:GearboxTransmissionTypeType"/>
			<xs:element name="NrOfGears" type="xs:int"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="AxleWheelsGroup">
		<xs:sequence>
			<xs:element name="AverageRRC" type="v1.0:TyreRRCISOType"/>
			<xs:element name="Axle" maxOccurs="unbounded">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="TyreDimension" type="v2.3:TyreDimensionType"/>
						<xs:element name="FuelEfficiencyClass"/>
						<xs:element name="TyreCertificationNumber" type="v1.0:CertificationNumberType"/>
					</xs:sequence>
					<xs:attribute name="axleNumber"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="ElectricMachineGroup">
		<xs:sequence>
			<xs:element name="TotalRatedPropulsionPower">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="mrf:RatedPowerType">
							<xs:attribute name="unit" type="out:PowerUnitType" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="VoltageLevels">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="VoltageLevel" maxOccurs="unbounded">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="MaxContinuousPropulsionPower" type="mrf:RatedPowerType"/>
								</xs:sequence>
								<xs:attribute name="voltage"/>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="REESSGroup">
		<xs:sequence>
			<xs:element name="TotalStorageCapacity">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:int">
							<xs:attribute name="unit" type="out:StorageCapacityUnitType" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="UsableStorageCapacity">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:int">
							<xs:attribute name="unit" type="out:StorageCapacityUnitType" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="LorryAuxGroup">
		<xs:sequence>
			<xs:element name="SteeringPumpTechnology" type="v2.4:AuxSPTechnologyLorryType"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="CompletedBusAuxGroup">
		<xs:sequence>
			<xs:element name="HVAC">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="SystemConfiguration"/>
						<xs:element name="AuxiliaryHeaterPower"/>
						<xs:element name="DoubleGlazing"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<!--Results-->
	<xs:element name="VectoMockResults">
		<xs:annotation>
			<xs:documentation>This element is just for developing the XML Schema of the different types of results - can be removed later on</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Results" type="ResultsType"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:complexType name="ResultsType">
		<xs:sequence>
			<xs:element name="Status">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="success"/>
						<xs:enumeration value="error"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:choice>
				<xs:sequence>
					<xs:element name="Result" type="AbstractResultType" maxOccurs="unbounded"/>
					<xs:element name="Summary" type="AbstractResultSummaryType"/>
				</xs:sequence>
				<xs:element name="ExemptedVehicle">
					<xs:complexType/>
				</xs:element>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="AbstractResultType" abstract="true">
		<xs:attribute name="status" use="required">
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="success"/>
					<xs:enumeration value="error"/>
				</xs:restriction>
			</xs:simpleType>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="ResultSuccessOCVHEVType">
		<xs:complexContent>
			<xs:extension base="AbstractResultType">
				<xs:sequence>
					<xs:group ref="ResultSuccessSimulationParametersGroup"/>
					<xs:element name="OCVMode" minOccurs="2" maxOccurs="2">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="AverageSpeed">
									<xs:annotation>
										<xs:documentation>I.2.2.1 / #60</xs:documentation>
									</xs:annotation>
									<xs:complexType>
										<xs:simpleContent>
											<xs:extension base="xs:double">
												<xs:attribute name="unit" type="SpeedUnitType" use="required"/>
											</xs:extension>
										</xs:simpleContent>
									</xs:complexType>
								</xs:element>
								<xs:element name="Fuel" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="FuelConsumption" type="FuelConsumptionType" maxOccurs="unbounded">
												<xs:annotation>
													<xs:documentation>I.2.3.1 - I.2.3.12 / #69</xs:documentation>
												</xs:annotation>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="type" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="ElectricEnergy" type="ElectricEnergyType" minOccurs="0"/>
								<xs:element name="CO2" type="CO2Type" maxOccurs="unbounded">
									<xs:annotation>
										<xs:documentation>I.2.3.13 - I.2.3.16 / #68</xs:documentation>
									</xs:annotation>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="type" use="required">
								<xs:simpleType>
									<xs:restriction base="xs:string">
										<xs:enumeration value="charge depleting"/>
										<xs:enumeration value="charge sustaining"/>
									</xs:restriction>
								</xs:simpleType>
							</xs:attribute>
						</xs:complexType>
					</xs:element>
					<xs:element name="Total">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="AverageSpeed">
									<xs:annotation>
										<xs:documentation>I.2.2.1 / #60</xs:documentation>
									</xs:annotation>
									<xs:complexType>
										<xs:simpleContent>
											<xs:extension base="xs:double">
												<xs:attribute name="unit" type="SpeedUnitType" use="required"/>
											</xs:extension>
										</xs:simpleContent>
									</xs:complexType>
								</xs:element>
								<xs:element name="Fuel" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="FuelConsumption" type="FuelConsumptionType" maxOccurs="unbounded">
												<xs:annotation>
													<xs:documentation>I.2.3.1 - I.2.3.12 / #69</xs:documentation>
												</xs:annotation>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="type" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="ElectricEnergy" type="ElectricEnergyType"/>
								<xs:element name="CO2" type="CO2Type" maxOccurs="unbounded">
									<xs:annotation>
										<xs:documentation>I.2.3.13 - I.2.3.16 / #68</xs:documentation>
									</xs:annotation>
								</xs:element>
								<xs:group ref="ElectricRangeSequenceGroup"/>
								<xs:element name="UtilityFactor" type="xs:double"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ResultSuccessPEVType">
		<xs:complexContent>
			<xs:extension base="AbstractResultType">
				<xs:sequence>
					<xs:group ref="ResultSuccessSimulationParametersGroup"/>
					<xs:element name="Total">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="AverageSpeed">
									<xs:annotation>
										<xs:documentation>I.2.2.1 / #60</xs:documentation>
									</xs:annotation>
									<xs:complexType>
										<xs:simpleContent>
											<xs:extension base="xs:double">
												<xs:attribute name="unit" type="SpeedUnitType" use="required"/>
											</xs:extension>
										</xs:simpleContent>
									</xs:complexType>
								</xs:element>
								<xs:element name="ElectricEnergy" type="ElectricEnergyType"/>
								<xs:sequence minOccurs="0">
									<xs:element name="FC_ZEV_AuxHeater">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="FuelConsumption" type="FuelConsumptionType" maxOccurs="unbounded">
													<xs:annotation>
														<xs:documentation>I.2.3.1 - I.2.3.12 / #69</xs:documentation>
													</xs:annotation>
												</xs:element>
											</xs:sequence>
											<xs:attribute name="type" type="xs:string" use="required"/>
										</xs:complexType>
									</xs:element>
									<xs:element name="CO2_ZEV_AuxHeater">
										<xs:complexType>
											<xs:sequence>
												<xs:element name="CO2" type="CO2Type" maxOccurs="unbounded">
													<xs:annotation>
														<xs:documentation>I.2.3.13 - I.2.3.16 / #68</xs:documentation>
													</xs:annotation>
												</xs:element>
											</xs:sequence>
										</xs:complexType>
									</xs:element>
								</xs:sequence>
								<xs:group ref="ElectricRangeSequenceGroup"/>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ResultSuccessConventionalType">
		<xs:complexContent>
			<xs:extension base="AbstractResultType">
				<xs:sequence>
					<xs:group ref="ResultSuccessSimulationParametersGroup"/>
					<xs:element name="Total">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="AverageSpeed">
									<xs:annotation>
										<xs:documentation>I.2.2.1 / #60</xs:documentation>
									</xs:annotation>
									<xs:complexType>
										<xs:simpleContent>
											<xs:extension base="xs:double">
												<xs:attribute name="unit" type="SpeedUnitType" use="required"/>
											</xs:extension>
										</xs:simpleContent>
									</xs:complexType>
								</xs:element>
								<xs:element name="Fuel" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="FuelConsumption" type="FuelConsumptionType" maxOccurs="unbounded">
												<xs:annotation>
													<xs:documentation>I.2.3.1 - I.2.3.12 / #69</xs:documentation>
												</xs:annotation>
											</xs:element>
										</xs:sequence>
										<xs:attribute name="type" type="xs:string" use="required"/>
									</xs:complexType>
								</xs:element>
								<xs:element name="CO2" type="CO2Type" maxOccurs="unbounded">
									<xs:annotation>
										<xs:documentation>I.2.3.13 - I.2.3.16 / #68</xs:documentation>
									</xs:annotation>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ResultSuccessNonOCVHEVType">
		<xs:complexContent>
			<xs:extension base="ResultSuccessConventionalType"/>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ResultErrorType">
		<xs:complexContent>
			<xs:extension base="AbstractResultType">
				<xs:sequence>
					<xs:element name="Mission" type="MissionTypeType">
						<xs:annotation>
							<xs:documentation>I.2.1.1 / #56</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="SimulationParameters" type="SimulationParametersType"/>
					<xs:element name="Error" type="xs:string"/>
					<xs:element name="ErrorDetails" type="xs:string"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="SimulationParametersType">
		<xs:sequence>
			<xs:element name="TotalVehicleMass">
				<xs:annotation>
					<xs:documentation>I.2.1.4 / #59</xs:documentation>
				</xs:annotation>
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:double">
							<xs:attribute name="unit" type="MassUnitType" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:choice>
				<xs:sequence>
					<xs:element name="Payload">
						<xs:annotation>
							<xs:documentation>I.2.1.2 / #57</xs:documentation>
						</xs:annotation>
						<xs:complexType>
							<xs:simpleContent>
								<xs:extension base="xs:double">
									<xs:attribute name="unit" type="MassUnitType" use="required"/>
								</xs:extension>
							</xs:simpleContent>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<xs:sequence>
					<xs:element name="MassPassengers">
						<xs:annotation>
							<xs:documentation>I.2.1.2 / #57</xs:documentation>
						</xs:annotation>
						<xs:complexType>
							<xs:simpleContent>
								<xs:extension base="xs:double">
									<xs:attribute name="unit" type="MassUnitType" use="required"/>
								</xs:extension>
							</xs:simpleContent>
						</xs:complexType>
					</xs:element>
					<xs:element name="PassengerCount" type="xs:double"/>
				</xs:sequence>
			</xs:choice>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="CO2UnitType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="g/km"/>
			<xs:enumeration value="g/t-km"/>
			<xs:enumeration value="g/p-km"/>
			<xs:enumeration value="g/m³-km"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="DistanceUnitType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="km"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="EnergyConsumptionUnitType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="kWh/km"/>
			<xs:enumeration value="kWh/t-km"/>
			<xs:enumeration value="kWh/m³-km"/>
			<xs:enumeration value="kWh/p-km"/>
			<xs:enumeration value="MJ/km"/>
			<xs:enumeration value="MJ/t-km"/>
			<xs:enumeration value="MJ/m³-km"/>
			<xs:enumeration value="MJ/p-km"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="FuelConsumptionUnitType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="g/km"/>
			<xs:enumeration value="g/t-km"/>
			<xs:enumeration value="g/p-km"/>
			<xs:enumeration value="g/m³-km"/>
			<xs:enumeration value="l/100km"/>
			<xs:enumeration value="l/t-km"/>
			<xs:enumeration value="l/p-km"/>
			<xs:enumeration value="l/m³-km"/>
			<xs:enumeration value="MJ/km"/>
			<xs:enumeration value="MJ/t-km"/>
			<xs:enumeration value="MJ/m³-km"/>
			<xs:enumeration value="MJ/p-km"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="MassUnitType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="kg"/>
			<xs:enumeration value="t"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="PercentType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="%"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="SpeedUnitType">
		<xs:restriction base="xs:token">
			<xs:enumeration value="km/h"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="MissionTypeType">
		<xs:restriction base="xs:token">
			<xs:minLength value="1"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:complexType name="FuelConsumptionType">
		<xs:simpleContent>
			<xs:extension base="xs:double">
				<xs:attribute name="unit" type="FuelConsumptionUnitType" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="CO2Type">
		<xs:simpleContent>
			<xs:extension base="xs:double">
				<xs:attribute name="unit" type="CO2UnitType" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:group name="ResultSuccessSimulationParametersGroup">
		<xs:sequence>
			<xs:element name="Mission" type="MissionTypeType"/>
			<xs:element name="SimulationParameters" type="SimulationParametersType"/>
		</xs:sequence>
	</xs:group>
	<xs:complexType name="EnergyConsumptionType">
		<xs:simpleContent>
			<xs:extension base="xs:double">
				<xs:attribute name="unit" type="EnergyConsumptionUnitType" use="required"/>
			</xs:extension>
		</xs:simpleContent>
	</xs:complexType>
	<xs:complexType name="FuelType"/>
	<xs:complexType name="ElectricEnergyType">
		<xs:sequence>
			<xs:element name="EnergyConsumption" type="EnergyConsumptionType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:group name="ElectricRangeSequenceGroup">
		<xs:sequence>
			<xs:element name="ActualChargeDepletingRange">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:double">
							<xs:attribute name="unit" type="DistanceUnitType" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="EquivalentAllElectricRange">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:double">
							<xs:attribute name="unit" type="DistanceUnitType" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
			<xs:element name="ZeroCO2EmissionsRange">
				<xs:complexType>
					<xs:simpleContent>
						<xs:extension base="xs:double">
							<xs:attribute name="unit" type="DistanceUnitType" use="required"/>
						</xs:extension>
					</xs:simpleContent>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:complexType name="AbstractResultSummaryType" abstract="true"/>
	<xs:complexType name="ResultSummaryOCVHEVType">
		<xs:complexContent>
			<xs:extension base="AbstractResultSummaryType">
				<xs:sequence>
					<xs:element name="Fuel" maxOccurs="unbounded">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="FuelConsumption" type="FuelConsumptionType" maxOccurs="unbounded">
									<xs:annotation>
										<xs:documentation>I.2.3.1 - I.2.3.12 / #69</xs:documentation>
									</xs:annotation>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="type" type="xs:string" use="required"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="ElectricEnergy" type="ElectricEnergyType"/>
					<xs:element name="CO2" type="CO2Type" maxOccurs="unbounded">
						<xs:annotation>
							<xs:documentation>I.2.3.13 - I.2.3.16 / #68</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:group ref="ElectricRangeSequenceGroup"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ResultSummaryPEVType">
		<xs:complexContent>
			<xs:extension base="AbstractResultSummaryType">
				<xs:sequence>
					<xs:element name="ElectricEnergy" type="ElectricEnergyType"/>
					<xs:sequence minOccurs="0">
						<xs:element name="FC_ZEV_AuxHeater">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="FuelConsumption" type="FuelConsumptionType" maxOccurs="unbounded">
										<xs:annotation>
											<xs:documentation>I.2.3.1 - I.2.3.12 / #69</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
								<xs:attribute name="type" type="xs:string" use="required"/>
							</xs:complexType>
						</xs:element>
						<xs:element name="CO2_ZEV_AuxHeater">
							<xs:complexType>
								<xs:sequence>
									<xs:element name="CO2" type="CO2Type" maxOccurs="unbounded">
										<xs:annotation>
											<xs:documentation>I.2.3.13 - I.2.3.16 / #68</xs:documentation>
										</xs:annotation>
									</xs:element>
								</xs:sequence>
							</xs:complexType>
						</xs:element>
					</xs:sequence>
					<xs:group ref="ElectricRangeSequenceGroup"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ResultSummaryConventionalType">
		<xs:complexContent>
			<xs:extension base="AbstractResultSummaryType">
				<xs:sequence>
					<xs:element name="Fuel" maxOccurs="unbounded">
						<xs:complexType>
							<xs:sequence>
								<xs:element name="FuelConsumption" type="FuelConsumptionType" maxOccurs="unbounded">
									<xs:annotation>
										<xs:documentation>I.2.3.1 - I.2.3.12 / #69</xs:documentation>
									</xs:annotation>
								</xs:element>
							</xs:sequence>
							<xs:attribute name="type" type="xs:string" use="required"/>
						</xs:complexType>
					</xs:element>
					<xs:element name="CO2" type="CO2Type" maxOccurs="unbounded">
						<xs:annotation>
							<xs:documentation>I.2.3.13 - I.2.3.16 / #68</xs:documentation>
						</xs:annotation>
					</xs:element>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="ResultSummaryNonOCVHEVType">
		<xs:complexContent>
			<xs:extension base="ResultSummaryConventionalType"/>
		</xs:complexContent>
	</xs:complexType>
</xs:schema>
