<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2016 rel. 2 sp1 (x64) (http://www.altova.com) by Helmut Eichlseder (TU Graz/Inst. f. VKM und THD) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns="urn:tugraz:ivt:VectoAPI:CustomerOutput:v0.9" xmlns:out="urn:tugraz:ivt:VectoAPI:DeclarationOutput:v0.9" targetNamespace="urn:tugraz:ivt:VectoAPI:CustomerOutput:v0.9" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationOutput:v0.9" schemaLocation="VectoOutputManufacturer.0.9.xsd"/>
	<xs:element name="VectoOutput">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
	</xs:element>
	<xs:complexType name="AbstractVectoCustomerOutputType"/>
	<xs:complexType name="ConventionalLorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="Conventional_LorryVehicleType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_Px_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="HEV_Px_IHPC_LorryVehicleType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_S2_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="HEV_S2_LorryVehicleType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_S3_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="HEV_S3_LorryVehicleType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_S4_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="HEV_S4_LorryVehicleType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_IEPC_S_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="HEV_IEPC_S_LorryVehicleType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_E2_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="PEV_E2_LorryVehicleType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_E3_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="PEV_E3_LorryVehicleType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_E4_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="PEV_E4_LorryVehicleType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_IEPC_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="PEV_IEPC_LorryVehicleType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Conventional_CompletedBusOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="Conventional_CompletedBusVehicleType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_CompletedBusOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="HEV_CompletedBusVehicleType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_CompletedBusOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="PEV_CompletedBusVehicleType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Exempted_LorryOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="Exempted_LorryVehicleType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Exempted_CompletedBusOutputType">
		<xs:sequence>
			<xs:element name="Vehicle" type="Exempted_CompletedBusVehicleType"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Conventional_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="GeneralVehicleSequenceGroup"/>
			<xs:group ref="LorryGeneralVehicleSequenceGroup"/>
			<xs:group ref="Conventional_LorryVehicleSequenceGroup"/>
			<xs:element name="ADAS" type="out:ConventionalADASType"/>
			<xs:group ref="EngineGroup"/>
			<xs:group ref="TransmissionGroup"/>
			<xs:element name="Retarder"/>
			<xs:element name="AxleRatio"/>
			<xs:group ref="AxleWheelsGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_Px_IHPC_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="HEV_LorryVehicleTypeGroup"/>
			<xs:element name="ADAS" type="out:HEVADASType"/>
			<xs:group ref="EngineGroup"/>
			<xs:group ref="TransmissionGroup"/>
			<xs:element name="Retarder"/>
			<xs:element name="AxleRatio"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:group ref="ElectricMachineGroup"/>
			<xs:group ref="REESSGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_S2_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="HEV_LorryVehicleTypeGroup"/>
			<xs:group ref="EngineGroup"/>
			<xs:group ref="TransmissionGroup"/>
			<xs:element name="Retarder"/>
			<xs:element name="AxleRatio"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:element name="ADAS" type="out:HEVADASType"/>
			<xs:group ref="ElectricMachineGroup"/>
			<xs:group ref="REESSGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_S3_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="HEV_LorryVehicleTypeGroup"/>
			<xs:group ref="EngineGroup"/>
			<xs:element name="Retarder"/>
			<xs:element name="AxleRatio"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:element name="ADAS" type="out:HEVADASType"/>
			<xs:group ref="ElectricMachineGroup"/>
			<xs:group ref="REESSGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_S4_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="HEV_LorryVehicleTypeGroup"/>
			<xs:element name="ADAS" type="out:HEVADASType"/>
			<xs:group ref="EngineGroup"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:group ref="ElectricMachineGroup"/>
			<xs:group ref="REESSGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_IEPC_S_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="HEV_LorryVehicleTypeGroup"/>
			<xs:element name="ADAS" type="out:HEVADASType"/>
			<xs:group ref="EngineGroup"/>
			<xs:element name="Retarder"/>
			<xs:element name="AxleRatio" minOccurs="0"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:group ref="ElectricMachineGroup"/>
			<xs:group ref="REESSGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_E2_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="PEV_LorryVehicleTypeGroup"/>
			<xs:element name="ADAS" type="out:PEVADASType"/>
			<xs:group ref="TransmissionGroup"/>
			<xs:element name="Retarder"/>
			<xs:element name="AxleRatio"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:group ref="ElectricMachineGroup"/>
			<xs:group ref="REESSGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_E3_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="PEV_LorryVehicleTypeGroup"/>
			<xs:element name="ADAS" type="out:PEVADASType"/>
			<xs:element name="Retarder"/>
			<xs:element name="AxleRatio"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:group ref="ElectricMachineGroup"/>
			<xs:group ref="REESSGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_E4_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="PEV_LorryVehicleTypeGroup"/>
			<xs:element name="ADAS" type="out:PEVADASType"/>
			<xs:element name="Retarder"/>
			<xs:element name="AxleRatio"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:group ref="ElectricMachineGroup"/>
			<xs:group ref="REESSGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_IEPC_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="PEV_LorryVehicleTypeGroup"/>
			<xs:element name="ADAS" type="out:PEVADASType"/>
			<xs:element name="Retarder"/>
			<xs:element name="AxleRatio" minOccurs="0"/>
			<xs:group ref="AxleWheelsGroup"/>
			<xs:group ref="ElectricMachineGroup"/>
			<xs:group ref="REESSGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Conventional_CompletedBusVehicleType">
		<xs:sequence>
			<xs:group ref="CompletedBusVehicleTypeGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="HEV_CompletedBusVehicleType">
		<xs:sequence>
			<xs:group ref="CompletedBusVehicleTypeGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="PEV_CompletedBusVehicleType">
		<xs:sequence>
			<xs:group ref="CompletedBusVehicleTypeGroup"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Exempted_LorryVehicleType">
		<xs:sequence>
			<xs:group ref="GeneralVehicleSequenceGroup"/>
			<xs:element name="VehicleGroupCO2"/>
			<xs:element name="Manufacturer"/>
			<xs:element name="ManufacturerAddress"/>
			<xs:element name="Model"/>
			<xs:element name="CorrectedActualMass"/>
			<xs:element name="SleeperCab"/>
			<xs:element name="ZeroEmissionHDV"/>
			<xs:element name="HybridElectricHDV"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="Exempted_CompletedBusVehicleType">
		<xs:sequence>
			<xs:group ref="GeneralVehicleSequenceGroup"/>
			<xs:sequence>
				<xs:element name="Manufacturers">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="Step">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Manufacturer"/>
										<xs:element name="ManufacturerAddress"/>
									</xs:sequence>
									<xs:attribute name="Count" type="xs:int"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:sequence>
				<xs:element name="CorrectedActualMass"/>
				<xs:element name="ZeroEmissionHDV"/>
				<xs:element name="HybridElectricHDV"/>
				<xs:element name="ClassBus"/>
				<xs:element name="TotalNumberOfPassengers"/>
			</xs:sequence>
		</xs:sequence>
	</xs:complexType>
	<xs:group name="GeneralVehicleSequenceGroup">
		<xs:sequence>
			<xs:element name="VehicleIdentifiationNumber"/>
			<xs:element name="VehicleCategory"/>
			<xs:element name="AxleConfiguration"/>
			<xs:element name="TechnicalPermissibleMaximumLadenMass"/>
			<xs:element name="VehicleGroup"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="LorryGeneralVehicleSequenceGroup">
		<xs:sequence>
			<xs:element name="VehicleGroupCO2"/>
			<xs:element name="Manufacturer"/>
			<xs:element name="ManufacturerAddress"/>
			<xs:element name="Model"/>
			<xs:element name="VehicleTypeApprovalNumber"/>
			<xs:element name="CorrectedActualMass"/>
			<xs:element name="VocationalVehicle"/>
			<xs:element name="SleeperCab"/>
			<xs:element name="ZeroEmissionHDV"/>
			<xs:element name="HybridElectricHDV"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="Conventional_LorryVehicleSequenceGroup">
		<xs:sequence>
			<xs:element name="WasteHeatRecovery"/>
			<xs:element name="DualFuelVehicle"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="HEV_VehicleSequenceGroup">
		<xs:sequence>
			<xs:group ref="Conventional_LorryVehicleSequenceGroup"/>
			<xs:element name="HEVArchitecture"/>
			<xs:element name="OffVehicleChargingCapability"/>
			<xs:element name="OffVehicleChargingMaxPower" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="PEV_VehicleSequenceGroup">
		<xs:sequence>
			<xs:element name="PEVArchitecture"/>
			<xs:element name="OffVehicleChargingCapability"/>
			<xs:element name="OffVehicleChargingMaxPower" minOccurs="0"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="HEV_LorryVehicleTypeGroup">
		<xs:sequence>
			<xs:group ref="GeneralVehicleSequenceGroup"/>
			<xs:group ref="LorryGeneralVehicleSequenceGroup"/>
			<xs:group ref="HEV_VehicleSequenceGroup"/>
			<xs:sequence>
				<xs:element name="HEVArchitecture"/>
				<xs:element name="OffVehicleChargingCapability"/>
				<xs:element name="OffVehicleChargingMaxPower" minOccurs="0"/>
			</xs:sequence>
		</xs:sequence>
	</xs:group>
	<xs:group name="PEV_LorryVehicleTypeGroup">
		<xs:sequence>
			<xs:group ref="GeneralVehicleSequenceGroup"/>
			<xs:group ref="LorryGeneralVehicleSequenceGroup"/>
			<xs:group ref="PEV_VehicleSequenceGroup"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="CompletedBusVehicleTypeGroup">
		<xs:sequence>
			<xs:group ref="GeneralVehicleSequenceGroup"/>
			<xs:sequence>
				<xs:element name="Manufacturers">
					<xs:complexType>
						<xs:sequence maxOccurs="unbounded">
							<xs:element name="Step">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="Manufacturer"/>
										<xs:element name="ManufacturerAddress"/>
									</xs:sequence>
									<xs:attribute name="Count" type="xs:int"/>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
			<xs:sequence>
				<xs:element name="CorrectedActualMass"/>
				<xs:element name="ZeroEmissionHDV"/>
				<xs:element name="HybridElectricHDV"/>
				<xs:element name="ClassBus"/>
				<xs:element name="TotalNumberOfPassengers"/>
				<xs:element name="VehicleTypeApprovalNumber"/>
			</xs:sequence>
		</xs:sequence>
	</xs:group>
	<xs:group name="EngineGroup">
		<xs:sequence>
			<xs:element name="EngineRatedPower"/>
			<xs:element name="EngineCapacity"/>
			<xs:element name="FuelType"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="TransmissionGroup">
		<xs:sequence>
			<xs:element name="TransmissionValues"/>
			<xs:element name="TransmissionType"/>
			<xs:element name="NrOfGears"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="AxleWheelsGroup">
		<xs:sequence>
			<xs:element name="AverageRRC"/>
			<xs:element name="Axle">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="TyreDimension"/>
						<xs:element name="FuelEfficiencyClass"/>
						<xs:element name="TyreCertificationNumber"/>
					</xs:sequence>
					<xs:attribute name="axleNumber"/>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
	</xs:group>
	<xs:group name="ElectricMachineGroup">
		<xs:sequence>
			<xs:element name="TotalRatedPropulsionPower"/>
			<xs:element name="MaxContinousPropulsionPower"/>
		</xs:sequence>
	</xs:group>
	<xs:group name="REESSGroup">
		<xs:sequence>
			<xs:element name="TotalStorageCapacity"/>
			<xs:element name="UsableStorageCapacity"/>
		</xs:sequence>
	</xs:group>
</xs:schema>
