<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2021 (x64) (http://www.altova.com) by Markus Quaritsch (Technische Universität Graz) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:vectoParam="urn:tugraz:ivt:VectoAPI:ParameterDocumentation" xmlns:di="http://www.w3.org/2000/09/xmldsig#" xmlns:v1.0="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v1.0" xmlns:v2.0="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.0" xmlns:v2.1="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.1" xmlns:v2.11D="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.11" targetNamespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.11" elementFormDefault="qualified" attributeFormDefault="unqualified" xsi:schemaLocation="urn:tugraz:ivt:VectoAPI:ParameterDocumentation ParameterDocumentation.xsd">
	<xs:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v1.0" schemaLocation="VectoDeclarationDefinitions.1.0.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.0" schemaLocation="VectoDeclarationDefinitions.2.0.xsd"/>
	<xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.1" schemaLocation="VectoDeclarationDefinitions.2.1.xsd"/>
	<!--
Changelog:
	03.02.2022: First official version uploaded to CITnet
	04.04.2022: Changes in 'TyreDimensionType': remove space between tyre design code and rim diameter (205/70 R15, 205/80 R15) 
    01.06.2022: Change type of WHTC Correction factors, CFRegPer, BFColdHot: constraint > 0.0
    23.08.2022: Bugfix IEPC standard values: require gear attribute for power map, allow multiple power maps; 
                                             require gear attribute for drag curve, allow multiple drag curves
    04.04.2023: Bugfix: new data type for Battery System with standard values. P520 and P511 are not applicable in case of standard 
                        values
    11.04.2023: Bugfix IEPC standard values: allow only one drag curve, remove gear attribute
-->
	<xs:complexType name="EngineDataDeclarationType">
		<xs:complexContent>
			<xs:extension base="v1.0:AbstractCombustionEngineDataDeclarationType">
				<xs:sequence>
					<xs:element name="Manufacturer" type="v1.0:ManufacturerType">
						<xs:annotation>
							<xs:documentation>P200 - [-]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="Model" type="v1.0:ModelType">
						<xs:annotation>
							<xs:documentation>P201 - [-]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="CertificationNumber" type="v1.0:CertificationNumberType">
						<xs:annotation>
							<xs:documentation>P261 - [-]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="Date" type="v1.0:DateTimeWithTimezone">
						<xs:annotation>
							<xs:documentation>P203 - [-]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="AppVersion" type="v1.0:AppVersionType">
						<xs:annotation>
							<xs:documentation>P204 - [-]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="Displacement" type="v1.0:EngineDisplacementType" nillable="false">
						<xs:annotation>
							<xs:documentation>P061 - [cm³]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="RatedSpeed" type="v1.0:EngineDeclaredSpeedType">
						<xs:annotation>
							<xs:documentation>P249 - [1/min]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="RatedPower" type="v1.0:EngineRatedPower">
						<xs:annotation>
							<xs:documentation>P250 - [W]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="MaxEngineTorque" type="v1.0:EngineMaxTorque">
						<xs:annotation>
							<xs:documentation>P259 - [Nm]</xs:documentation>
						</xs:annotation>
					</xs:element>
					<xs:element name="WHRType" type="v2.11D:WHRTypeType"/>
					<xs:element name="Mode" type="v2.11D:EngineFuelModeType" maxOccurs="unbounded"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	<xs:complexType name="EngineFuelModeType">
		<xs:sequence>
			<xs:element name="IdlingSpeed" type="v1.0:EngineDeclaredSpeedType">
				<xs:annotation>
					<xs:documentation>P063 - [1/min]</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="FullLoadAndDragCurve">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Entry" type="v1.0:FullLoadAndDragCurveEntryType" minOccurs="2" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="Fuel" type="v2.11D:EngineFuelType" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="EngineFuelType">
		<xs:sequence>
			<xs:element name="WHTCUrban" type="v2.11D:EngineWHTCType">
				<xs:annotation>
					<xs:documentation>P109 - [-]</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="WHTCRural" type="v2.11D:EngineWHTCType">
				<xs:annotation>
					<xs:documentation>P110 - [-]</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="WHTCMotorway" type="v2.11D:EngineWHTCType">
				<xs:annotation>
					<xs:documentation>P111 - [-]</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="BFColdHot" type="v2.11D:EngineColdHotBalancingFactorType">
				<xs:annotation>
					<xs:documentation>P159 - [-]</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="CFRegPer" type="v2.11D:EngineCFRegPerType">
				<xs:annotation>
					<xs:documentation>P192 [-]</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="CFNCV" type="v1.0:EngineNCVCFType">
				<xs:annotation>
					<xs:documentation>P260 - [-]</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="WHRCorrectionFactors" minOccurs="0">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Electrical" type="v2.11D:WHRElectricalCorrectionFactorsType" minOccurs="0"/>
						<xs:element name="Mechanical" type="v2.11D:WHRMechanicalCorrectionFactorsType" minOccurs="0"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
			<xs:element name="FuelConsumptionMap">
				<xs:complexType>
					<xs:sequence>
						<xs:element name="Entry" type="v2.11D:FuelConsumptionEntryType" minOccurs="4" maxOccurs="unbounded"/>
					</xs:sequence>
				</xs:complexType>
			</xs:element>
		</xs:sequence>
		<xs:attribute name="type" type="v2.11D:FuelTypeType" use="required">
			<xs:annotation>
				<xs:documentation>P193 [enum]</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="FuelConsumptionEntryType">
		<xs:attribute name="engineSpeed" type="v1.0:EngineSpeedType" use="required">
			<xs:annotation/>
		</xs:attribute>
		<xs:attribute name="torque" type="v1.0:EngineFuelConsumptionMapTorqueType" use="required">
			<xs:annotation>
				<xs:documentation>P073 - [Nm]</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="fuelConsumption" type="v1.0:EngineFuelConsumptionMapFuelConsumptionType" use="required">
			<xs:annotation>
				<xs:documentation>P074 - [g/h]</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="electricPower" type="v1.0:Double2">
			<xs:annotation>
				<xs:documentation>P348 - [W]</xs:documentation>
			</xs:annotation>
		</xs:attribute>
		<xs:attribute name="mechanicalPower" type="v1.0:Double2">
			<xs:annotation>
				<xs:documentation>P349 - [W]</xs:documentation>
			</xs:annotation>
		</xs:attribute>
	</xs:complexType>
	<xs:complexType name="WHRElectricalCorrectionFactorsType">
		<xs:sequence>
			<xs:element name="Urban">
				<xs:annotation>
					<xs:documentation>P338 - [-]</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="v1.0:Double4">
						<xs:minExclusive value="0.0000"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Rural">
				<xs:annotation>
					<xs:documentation>P339 - [-]</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="v1.0:Double4">
						<xs:minExclusive value="0.0000"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Motorway">
				<xs:annotation>
					<xs:documentation>P340 - [-]</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="v1.0:Double4">
						<xs:minExclusive value="0.0000"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="BFColdHot">
				<xs:annotation>
					<xs:documentation>P341 - [-]</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="v1.0:Double4">
						<xs:minExclusive value="0.0000"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CFRegPer">
				<xs:annotation>
					<xs:documentation>P342 - [-]</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="v1.0:Double4">
						<xs:minExclusive value="0.0000"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="WHRMechanicalCorrectionFactorsType">
		<xs:sequence>
			<xs:element name="Urban">
				<xs:annotation>
					<xs:documentation>P343 - [-]</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="v1.0:Double4">
						<xs:minExclusive value="0.0000"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Rural">
				<xs:annotation>
					<xs:documentation>P344 - [-]</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="v1.0:Double4">
						<xs:minExclusive value="0.0000"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="Motorway">
				<xs:annotation>
					<xs:documentation>P345 - [-]</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="v1.0:Double4">
						<xs:minExclusive value="0.0000"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="BFColdHot">
				<xs:annotation>
					<xs:documentation>P346 - [-]</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="v1.0:Double4">
						<xs:minExclusive value="0.0000"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
			<xs:element name="CFRegPer">
				<xs:annotation>
					<xs:documentation>P347 - [-]</xs:documentation>
				</xs:annotation>
				<xs:simpleType>
					<xs:restriction base="v1.0:Double4">
						<xs:minExclusive value="0.0000"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:complexType name="WHRTypeType">
		<xs:sequence>
			<xs:element name="MechanicalOutputICE" type="xs:boolean">
				<xs:annotation>
					<xs:documentation>P335 - bool</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="MechanicalOutputDrivetrain" type="xs:boolean">
				<xs:annotation>
					<xs:documentation>P336 - bool</xs:documentation>
				</xs:annotation>
			</xs:element>
			<xs:element name="ElectricalOutput" type="xs:boolean">
				<xs:annotation>
					<xs:documentation>P337 - bool</xs:documentation>
				</xs:annotation>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:simpleType name="EngineCFRegPerType">
		<xs:annotation>
			<xs:appinfo>
				<vectoParam:description>
					<vectoParam:parameterId component="Engine">192</vectoParam:parameterId>
					<vectoParam:unit>-</vectoParam:unit>
				</vectoParam:description>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="v1.0:Double4">
			<xs:minInclusive value="0.0000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="EngineColdHotBalancingFactorType">
		<xs:annotation>
			<xs:appinfo>
				<vectoParam:description>
					<vectoParam:parameterId component="Engine">159</vectoParam:parameterId>
					<vectoParam:unit>-</vectoParam:unit>
				</vectoParam:description>
			</xs:appinfo>
			<xs:documentation>P159 - [-]</xs:documentation>
		</xs:annotation>
		<xs:restriction base="v1.0:Double4">
			<xs:minInclusive value="0.0000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="EngineWHTCType">
		<xs:annotation>
			<xs:appinfo>
				<vectoParam:description>
					<vectoParam:parameterId component="Engine">109</vectoParam:parameterId>
					<vectoParam:parameterId component="Engine">110</vectoParam:parameterId>
					<vectoParam:parameterId component="Engine">111</vectoParam:parameterId>
					<vectoParam:unit>-</vectoParam:unit>
				</vectoParam:description>
			</xs:appinfo>
			<xs:documentation>P109 - [-]</xs:documentation>
		</xs:annotation>
		<xs:restriction base="v1.0:Double4">
			<xs:minInclusive value="0.0000"/>
		</xs:restriction>
	</xs:simpleType>
	<xs:simpleType name="FuelTypeType">
		<xs:annotation>
			<xs:appinfo>
				<vectoParam:description>
					<vectoParam:parameterId component="Engine">193</vectoParam:parameterId>
					<vectoParam:unit>-</vectoParam:unit>
				</vectoParam:description>
			</xs:appinfo>
		</xs:annotation>
		<xs:restriction base="xs:string">
			<xs:enumeration value="Diesel CI"/>
			<xs:enumeration value="Ethanol CI"/>
			<xs:enumeration value="Petrol PI"/>
			<xs:enumeration value="Ethanol PI"/>
			<xs:enumeration value="LPG"/>
			<xs:enumeration value="NG"/>
			<xs:enumeration value="LPG PI"/>
			<xs:enumeration value="NG PI"/>
			<xs:enumeration value="NG CI"/>
			<xs:enumeration value="H2 PI"/>
			<xs:enumeration value="H2 CI"/>
		</xs:restriction>
	</xs:simpleType>
</xs:schema>
