<?xml version="1.0" encoding="utf-8"?>
<xs:schema
  xmlns="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.6"
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns:vectoParam="urn:tugraz:ivt:VectoAPI:ParameterDocumentation"
  xmlns:di="http://www.w3.org/2000/09/xmldsig#"
  xmlns:v1.0="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v1.0"
  xmlns:v2.0="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.0"
  targetNamespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:DEV:v2.6"
  elementFormDefault="qualified"
  attributeFormDefault="unqualified"
  xsi:schemaLocation="urn:tugraz:ivt:VectoAPI:ParameterDocumentation ParameterDocumentation.xsd"
  >
  <xs:import namespace="http://www.w3.org/2000/09/xmldsig#" schemaLocation="xmldsig-core-schema.xsd"/>
  <xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v1.0" schemaLocation="VectoDeclarationDefinitions.1.0.xsd"/>
  <xs:import namespace="urn:tugraz:ivt:VectoAPI:DeclarationDefinitions:v2.0" schemaLocation="VectoDeclarationDefinitions.2.0.xsd"/>

  <xs:complexType name="AxleWheelsDataDeclarationType">
    <xs:annotation>
      <xs:documentation>Axles &amp; Wheels Component</xs:documentation>
    </xs:annotation>
    <xs:complexContent>
      <xs:extension base="v2.0:AbstractAxleWheelsDataDeclarationType">
        <xs:sequence>
          <xs:element name="Axles">
            <xs:complexType>
              <xs:sequence>
                <xs:element name="Axle" type="AxleDataDeclarationType" minOccurs="2" maxOccurs="4"/>
              </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>
  
  <xs:complexType name="AxleDataDeclarationType">
    <xs:complexContent>
      <xs:extension base="v2.0:AxleDataDeclarationType">
        <xs:sequence>
          <xs:element name="WheelEndFriction" minOccurs="0" maxOccurs="1">
            <xs:simpleType>
              <xs:restriction base="v1.0:Double1">
                <xs:minInclusive value="0"/>
              </xs:restriction>
            </xs:simpleType>
          </xs:element>
        </xs:sequence>
      </xs:extension>
    </xs:complexContent>
  </xs:complexType>

</xs:schema>
