<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>DeclarationCycleZip</RootNamespace>
    <AssemblyName>DeclarationCycleZip</AssemblyName>
    <TargetFrameworks>net5.0</TargetFrameworks>
    <DefineConstants />
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\VectoCommon\VectoCommon\VectoCommon.csproj" />
    <ProjectReference Include="..\..\VectoCore\VectoCore\VectoCore.csproj" />
  </ItemGroup>
</Project>