<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFrameworks />
    <TargetFramework>net45</TargetFramework>
    <AssemblyName>VECTO</AssemblyName>
    <ApplicationIcon>Icon2.ico</ApplicationIcon>
    <PackageIconUrl />
    <RootNamespace>TUGraz.VECTO</RootNamespace>
    <AutoGenerateBindingRedirects>false</AutoGenerateBindingRedirects>
  </PropertyGroup>

</Project>
