<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>GraphDrawer</RootNamespace>
    <AssemblyName>GraphDrawer</AssemblyName>
    <TargetFrameworks>net6.0</TargetFrameworks>
     
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\VectoCore\VectoCoreTest\VectoCoreTest.csproj" />
  </ItemGroup>
</Project>