'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System.CodeDom.Compiler
Imports System.ComponentModel
Imports System.Globalization
Imports System.Resources
Imports System.Runtime.CompilerServices

Namespace My.Resources

	'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
	'-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
	'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
	'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
	'''<summary>
	'''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
	'''</summary>
	<GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"), _
	 DebuggerNonUserCode(), _
	 CompilerGenerated(), _
	 HideModuleName()> _
	Friend Module Resources

		Private resourceMan As ResourceManager

		Private resourceCulture As CultureInfo

		'''<summary>
		'''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
		'''</summary>
		<EditorBrowsable(EditorBrowsableState.Advanced)> _
		Friend ReadOnly Property ResourceManager() As ResourceManager
			Get
				If ReferenceEquals(resourceMan, Nothing) Then
					Dim temp As ResourceManager = New ResourceManager("TUGraz.VECTO.Resources", GetType(Resources).Assembly)
					resourceMan = temp
				End If
				Return resourceMan
			End Get
		End Property

		'''<summary>
		'''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
		'''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
		'''</summary>
		<EditorBrowsable(EditorBrowsableState.Advanced)> _
		Friend Property Culture() As CultureInfo
			Get
				Return resourceCulture
			End Get
			Set(value As CultureInfo)
				resourceCulture = value
			End Set
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property _4x2r() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_4x2r", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property _4x2rt() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_4x2rt", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property _4x2tt() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_4x2tt", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property _6x2r() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_6x2r", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property _6x2rt() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_6x2rt", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property _6x2tt() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("_6x2tt", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property Actions_arrow_down_icon() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Actions_arrow_down_icon", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property Actions_arrow_up_icon() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Actions_arrow_up_icon", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property Actions_document_save_as_icon() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Actions_document_save_as_icon", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property Actions_document_save_icon() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Actions_document_save_icon", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property application_add_icon() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("application_add_icon", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property application_export_icon_small() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("application_export_icon_small", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property blue_document_icon() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("blue_document_icon", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property desktop() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("desktop", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property export_icon() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("export_icon", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property F_ENG() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("F_ENG", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property F_GBX() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("F_GBX", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property F_Graph() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("F_Graph", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property F_VECTO() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("F_VECTO", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property F_VEH() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("F_VEH", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property favorites() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("favorites", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property file_history() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("file_history", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property Help_icon() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Help_icon", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Icon ähnlich wie (Symbol).
		'''</summary>
		Friend ReadOnly Property Icon2() As Icon
			Get
				Dim obj As Object = ResourceManager.GetObject("Icon2", resourceCulture)
				Return CType(obj, Icon)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property Information_icon() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Information_icon", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property IVT_91x44() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("IVT_91x44", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property IVT_About() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("IVT_About", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property JRC_About() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("JRC_About", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property minus_circle_icon() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("minus_circle_icon", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property Misc_Tools_icon() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Misc_Tools_icon", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property new_dir() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("new_dir", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property Open_icon() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Open_icon", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property Play_icon() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Play_icon", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property Play_icon_gray() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Play_icon_gray", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property plus_circle_icon() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("plus_circle_icon", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property Refresh_icon() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Refresh_icon", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property Status_dialog_password_icon() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Status_dialog_password_icon", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property Stop_icon() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Stop_icon", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property TUG_91x34() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TUG_91x34", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property TUG_About() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("TUG_About", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property Undef() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("Undef", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property up_directory() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("up_directory", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property VECTO_About() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("VECTO_About", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property VECTO_ENG() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("VECTO_ENG", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property VECTO_GBX() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("VECTO_GBX", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property VECTO_Mainform() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("VECTO_Mainform", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property VECTO_VECTO() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("VECTO_VECTO", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property

		'''<summary>
		'''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
		'''</summary>
		Friend ReadOnly Property VECTO_VEH() As Bitmap
			Get
				Dim obj As Object = ResourceManager.GetObject("VECTO_VEH", resourceCulture)
				Return CType(obj, Bitmap)
			End Get
		End Property
	End Module
End Namespace
